### ISSUE TITLE
Remove UTC help text from templates

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1009]
In `message-status.html` and `notifications.html`, there is text with UTC-demystifying language from when the UI used UTC. That can be removed now.

**Comment by heyitsmebev** [comment]
Hi @stvnrlly! For this section - A note about timezones within Delivery status, do you want this entire part to be removed or just the last paragraph? 

http://localhost:6012/using-notify/delivery-status

![Image](https://github.com/GSA/notifications-admin/assets/53159604/9358f71a-9a5d-4a4d-a39d-264aee37bae6)
