### ISSUE TITLE
Sentence about 5 minutes til message receipts doesn't appear

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1022]
@ccostino can still see it. I cannot.

![Image](https://github.com/GSA/notifications-admin/assets/6556888/f3aceb5c-3a21-48cf-9287-827795f9e888)

This affects both `prod` and `staging` for me.

The sentence lives in a conditional:

```
{% if notification.status == 'sending' %}
  <p class="notification-status {{ field_status }}">
     Pending. Messages will remain in pending state until carrier status is received, typically 5 minutes.
     </p>
    {% endif %}
```

**Comment by heyitsmebev** [comment]
I'm not able to replicate in prod or staging. It works for me both on the Dashboard and individual text page. @tdlowden  Can you give it a try again?




![Image](https://github.com/GSA/notifications-admin/assets/53159604/45dd44c5-2810-4593-9295-3a0e9e5b4800)


![Image](https://github.com/GSA/notifications-admin/assets/53159604/880d2fb9-f6dd-4af6-b91e-0c88313be9bc)



![Image](https://github.com/GSA/notifications-admin/assets/53159604/590a483e-601b-4f8d-955c-26c8d588bba1)

**Comment by tdlowden** [comment]
@tdlowden try to repro

**Comment by heyitsmebev** [comment]
I added a notification to /services/id/jobs/id view 
"Messages will remain in pending state until carrier status is received, typically 5 minutes."

![Image](https://github.com/GSA/notifications-admin/assets/53159604/1f6feb1d-ffaf-4894-9137-153c82d3ac13)

**Comment by tdlowden** [comment]
I think this is merged?

**Comment by ccostino** [comment]
Yes it is, I merged it earlier today!
