### ISSUE TITLE
Within specific email templates in edit mode, there's is a random "end session" component below the footer

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1025]
(converted from a @heyitsmebev draft)

![Image](https://github.com/GSA/notifications-admin/assets/53159604/70d60996-747f-44d2-bb95-8bb4aa056f14)

![Image](https://github.com/GSA/notifications-admin/assets/53159604/8c29698d-1264-4c91-a3dd-45cb3f4a09f3)

**Comment by heyitsmebev** [comment]
I'm able to replicate this error anymore. I'm thinking maybe it had to with javascript loading error, but it's not happening anymore.
