### ISSUE TITLE
Revise UTC info on Delivery Status page

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1030]

**Comment by maomeara63** [comment]
Current info specifies UTC. Change to info about ET, or info about setting your own timezone. (Solution depends on timing.)

**Comment by tdlowden** [comment]
@maomeara63 can you screenshot this?

**Comment by tdlowden** [comment]
Appears at `/using-notify/delivery-status`

**Comment by terrazoon** [comment]
As of today, this page looks like it's been substantially rewritten and has no references to timezones.
