### ISSUE TITLE
Can't copy template

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1036]

**Comment by maomeara63** [comment]
In production. 
1. Send messages
2. New template
3. Copy existing template
4. Continue
5. Got page not found


![Image](https://github.com/GSA/notifications-admin/assets/65717217/185b1fda-3044-4db7-8e37-eba6751f9f2a)

**Comment by tdlowden** [comment]
I can replicate. Oddly, this passed QA before being pushed to prod.

**Comment by heyitsmebev** [comment]
@tdlowden @maomeara63 
I'm not able to replicate in production or staging. 

What is the URL path?

https://github.com/GSA/notifications-admin/assets/53159604/ee885ce0-9762-4a14-9d01-29177ac90165

**Comment by tdlowden** [comment]
Oy, it works for me now too. Not sure what was going on earlier. 

@maomeara63 can you try to replicate again? If it works we may have to just close and cross our fingers
