### ISSUE TITLE
Change time format from 24 hr clock to 12 hr in reports (to match UX)

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1090]
As a user, I want to see times after 12pm in the standard US format vs. the 24 hour/military time when I download the report
For example: 1:00pm vs. 13:00

**Comment by heyitsmebev** [comment]
This might be slightly outside of this PR but could we also get the date changed as well? from 2024-01-24 to 01-24-2024? @terrazoon 
![image](https://github.com/GSA/notifications-admin/assets/53159604/7f6e8e2c-e943-48bb-a517-404bf4dba52e)
