### ISSUE TITLE
User Story: How many messages have been recently sent across service

### ISSUE THREAD

**Issue by jonathanbobel** [GSA/notifications-admin#1095]
### As a [type of user],

Sender

### I want [an action or feature],

I want to see how many messages have been recently sent across my service

### So that [benefit or value].

I can get a snapshot of what's happening with my service

### Detailed condition or criteria that must be met for the user story to be considered complete.

The sender can log into their account and view the amount of messages that have been sent in the data range decided

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [ ] Decide on level(s) of recency that makes sense for most users (Daily, 7 days, Month?)
- [ ] Create a bar chart for SMS activity based on the decided range
- [ ] Create a legend SMS status (Delivered, Pending, Failed)
- [ ] Create tooltips to explain SMS status

### List any dependencies that need to be resolved before starting or completing this user story.

- Decide on the date range and make sure incoming data supports that range
- Make date range clear to users (lable/title)
- Make data easily consumable for Front-End Developers (API call or available object)
- Styling decisions for data visualizations

**Comment by jonathanbobel** [comment]
![Screenshot 2024-01-17 at 2 47 29 PM](https://github.com/GSA/notifications-admin/assets/1233986/e99eb294-c412-4440-afab-4d483b3f941a)

**Comment by em-herrick** [comment]
@jonathanbobel this seems related to #1102— are you thinking of implementing 1102 now, and following up to adjust the UI to display this bar graph instead of those lovely boxes?

**Comment by em-herrick** [comment]
@jonathanbobel had created code with dummy data, but waiting on the data to be pulled/refactored. Andrew was working on it, in PR, waiting to be reviewed.

**Comment by heyitsmebev** [comment]
@jonathanbobel Are we done with this ticket?
