### ISSUE TITLE
Revise/expand on "Recent Batch" table on the dashboard page.

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1114]
- [x] Add/revise these columns 
&nbsp;-  Uploaded file name
&nbsp;-  Message template
&nbsp;-  Sender
&nbsp;-  Time sent
&nbsp;-  Number of recipients

- [x] Limit to 5 rows
- [x] Link the items to full page individual job dashboard

![image](https://github.com/GSA/notifications-admin/assets/53159604/c271ece9-3f2d-45e7-876b-250d6ad9d78b)

**Comment by heyitsmebev** [comment]
@em-herrick @jonathanbobel @tdlowden 

**Based on the wireframe, here's how it looks updated.** 
![Image](https://github.com/GSA/notifications-admin/assets/53159604/02f69444-c7de-486c-bb7d-44d045e752fa)

**The old table had a download link column. Is this something we are removing? The user can also go to the individual batch job page to download the csv there. Do we need to have it in two spots?**
![Image](https://github.com/GSA/notifications-admin/assets/53159604/1f4847ab-c326-4b2e-8c20-cc4dc51edfff)

**And last question, do we want to keep or remove "since" within the sent time?** 


![Image](https://github.com/GSA/notifications-admin/assets/53159604/032cae7b-a6d2-470e-84c6-891e15b8b991)

**Comment by tdlowden** [comment]
I think for ease of downloading a bunch of those reports, let's keep it in the table! Apologies for missing this comment last week!

**Comment by tdlowden** [comment]
As for `since`.... yeah that doesn't make sense. go ahead and remove it!

**Comment by heyitsmebev** [comment]
![Image](https://github.com/GSA/notifications-admin/assets/53159604/7de74d4a-6715-401c-b0ee-25cc9de1059d)

Recent Batches updated
