### ISSUE TITLE
Bug: App is randomly erroring and preventing use

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1122]
### Who discovered this?

Tim L

### What happened?

I went to try to repro failed message sends by logging into `staging` and trying to navigate to the `Colorado WIC` service. I am met with the following error:

![Image](https://github.com/GSA/notifications-admin/assets/6556888/c7ab3c44-ca40-477d-a03a-f727deadf9f1)

Other services appear to be unaffected.

### Environment

staging

### What pages did this appear on?

https://notify-staging.app.cloud.gov/services/2f3ece4c-cfcf-4a26-be10-6512abe3995e

### Detail the steps for someone to reproduce

1. Log in to staging env
2. Click `Colorado WIC` 
3. View error

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

NA

**Comment by tdlowden** [comment]
This now appears to be happening at random places across multiple services in `staging`, and is not limited to `Colorado WIC`. It also happened to me when clicking `Current Service` to return to the main screen after attepting to send messages in the `Team Testing` service.

**Comment by terrazoon** [comment]
I think this was resolved.  Other bugs are being found in the latest QA round, but this particular bug was solved around a week ago (like 1/19).

**Comment by tdlowden** [comment]
ok thanks @terrazoon! @ccostino do you concur? if so I will close

**Comment by ccostino** [comment]
Yes, that is correct - that was due to some of the other things we fixed last week!

**Comment by tdlowden** [comment]
Solid ty
