### ISSUE TITLE
Bug: Messages are not being delivered from file uploads in staging

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1123]
### Who discovered this?

Tim L

### What happened?

Yesterday, when using the `Colorado WIC` service in staging, I attempted to send multiple messages via csv upload that immediately failed and had a status of "Phone is not accepting messages right now".

Today, in an attempt to replicate that behavior, I tried sending more messages in the Team Testing service. Twice I tried uploading a csv and the message stayed in `pending` status indefinitely, and I never received the message on my phone. 

I also tested one-off sends which were delivered, so It appears this is only affecting file uploads.

Unfortunately, I have no screenshots because the service eventually errored irrevocably, leading to another bug report I have filed.

### Environment

staging

### What pages did this appear on?

Cannot get URLs anymore, but in the `Team Testing` service of staging.

### Detail the steps for someone to reproduce

1. Log in to staging
2. choose a template and attempt to send a message via upload
3. Notice that the message is not delivered

### What browsers are you seeing the problem on?

Chrome

**Comment by ccostino** [comment]
@stvnrlly is this still an issue based on recent QA?

**Comment by stvnrlly** [comment]
This is not and issue now 👍🏻
