### ISSUE TITLE
Bug: SMS message fragment counts in platform do not match calculated value

### ISSUE THREAD

**Issue by anagradova** [GSA/notifications-admin#1125]
### Who discovered this?

Anastasia 

### What happened?

When exploring the calculation of SMS message fragments for multiple character sets, it became clear the calculation used by notification-utils produced a different segment count than should be expected. 

### Environment

production

### What pages did this appear on?

/templates/add-sms

### Detail the steps for someone to reproduce

Input a non-GSM and GSM combined char string into the message box and the SMS part calculator. It will produce different values.

### What browsers are you seeing the problem on?

Chrome

**Comment by ccostino** [comment]
[Several adjustments have been made in `notifications-utils`](https://github.com/GSA/notifications-utils/pull/100) and are now merged in the admin, so we should be able to see if the calculations are more accurate now!

**Comment by ccostino** [comment]
This is still an issue, but it's going to be superseded by the work in https://github.com/GSA/notifications-api/issues/1427, so we're closing it!
