### ISSUE TITLE
Get notify.gov domain

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#113]
- [x] #347 
- [x] #340 
- [x] #283
- [x] #281 
- [x] #284
- [x] #285
- [x] #286

**Comment by tdlowden** [comment]
met with Matt Jadud on 11/24. He provided background and the template he used for FAC. I copied and started work on the letter for us:
https://docs.google.com/document/d/1Srp3XvVn4vDM8sxiF77zRN_lAmCb1CoYb0CpFuOC5K8/edit

Still need to decide how to acculturate TTS LT to the idea and move forward.

**Comment by alexpandel** [comment]
here's the latest update from Nina on next steps; not sure the best way to update this epic and the corresponding issues accordingly, but would welcome your brain on that @tdlowden!

> we are going to put a stake in the ground that we'd like to go with notify.gov(or whichever URL you prefer).  it's less risky from a tech perspective, has a lower likelihood of rework, and it's not like it's the first time we went with a domain but should have thought it through a bit more.
> 
> for the financials: you have financials for the next 2 years.  beyond that, we've done scenario planning.  TTS plan is to either secure FCSF approps to keep going or use carry-forward to wind the pilot down.
> 
> so then our work is just getting with GSA to figure out how to move this forward expeditiously.
> 
> to get a URL, you need to go through [the DLP / EDX process](https://insite.gsa.gov/employee-resources/communications/digital-website-communication/policies-and-guidelines/digital-lifecycle-program?term=).  Star advises that you want to have your case solid _before_ meeting with EDX officially.
> so in keeping with what they've outlined, **these seem to be the next steps:**
> 
> - **Step 1:** Studio to draft internal memo to get approval to request notify.gov URL.  Explain what they need the URL for.  Explain what URL options they considered.  Explain their financial plan (and the scenario planning for post-ARP).  Get Ashley's ok, and Ann's.  Goal: sign off ASAP, no later than end of week (assuming Studio can draft the memo that fast.)
>   - **Step 1.5:** Get Ashley and LBS sign offs on the Notify pilot plan doc.  They've given them verbally months ago, they just won't type their names.
> - **Step 2:** Connect with EDX.  Work out how to get this going faster than what the DLP process seems to imply.
> - **Step 3:** Fill out the form that's the first step in DLP, or otherwise start the process in whatever way EDX recommends for a fast resolution.
> - **Step 4:** Connect with OGC (Dan N) to do due diligence on notify.gov.  This can be done concurrent with the above steps 2 & 3.
>   - Per Star: "The team can work directly with Dan N to make the request and let him know the details. I can be CCed as this is relevant to Outreach but more OGC's lane. Before that though, Ashley needs to be on board with the name and getting OGC involved."

**Comment by rahearn** [comment]
Note for if we're getting a new domain (rather than a subdomain of digital.gov): if the CISA app requires (or allows) us to specify the top level NameServers to use, coordinate with @rahearn to get them managed via https://github.com/18f/dns before submitting to CISA
