### ISSUE TITLE
E2E Test Improvement:  get WebKit support working

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1152]
E2E tests are now working in the CI/CD pipeline for pull requests! 🎉 However, they currently do not run correctly in the WebKit browser for an unknown reason and we'd like to make sure we include that coverage in addition to Firefox and Chrome since [Playwright](https://playwright.dev/python/) supports all three browsers.

## What currently happens with WebKit vs. Chrome or Firefox

There is a bypass mechanism worked into the application to allow the E2E test user to sign into the site without going through the full authentication flow.  This includes a [convenience method in the E2E tests](https://github.com/GSA/notifications-admin/blob/main/tests/end_to_end/test_accounts_page.py#L8-L21) that should be called at the start of any test that needs the user logged in.

In Chrome and Firefox, the test runner will perform this action and receive a 200 response from the local server running the Admin app and all is well.  Test continue to wherever they need to go and the user can perform actions as they are authenticated.

In Webkit, the server returns a 302 response and kicks the user back to the home page, never actually signing them in.  However, if the `FLASK_DEBUG` environment variable is set to `true`, then the requests work as expected.

## Possible causes and things to look at

At the moment, I surmise one of the following as happening:

- There's an issue with cookies and/or session information that's not being tracked in WebKit like it is in Chrome and Firefox
- Related, there may be a test environment configuration that needs to still be adjusted or that was missed - a new `E2ETest` environment was added in [`app/config.py`](https://github.com/GSA/notifications-admin/blob/main/app/config.py) to specifically handle the E2E tests ([see the PR for details](https://github.com/GSA/notifications-admin/pull/772), and it's possible something still isn't right with it that would impact the cookie/session handling
- Setting `FLASK_DEBUG=true` seems to have some effect here; it's unclear why at the moment, though I don't want to set that outside of a local environment
- Some other interaction taking place between pytest, Playwright, and WebKit that I'm not aware of yet

## Implementation Sketch and Acceptance Criteria

- [ ] Uncover what the issue is with WebKit not being able to sign in the E2E user like Chrome and Firefox
- [ ] Make the adjustments necessary to get the tests to work
- [ ] Update the Makefile `e2e-test` command to include WebKit again:  `poetry run pytest -v --browser chromium --browser firefox --browser webkit tests/end_to_end` ([refer to the PR to see the existing command](https://github.com/GSA/notifications-admin/pull/772))
- [ ] Update the [E2E test documentation](https://github.com/GSA/notifications-admin/blob/main/docs/end_to_end_tests.md) as necessary

## Security Considerations

- We need to be mindful of not exposing debug or log information that would compromise any credentials as we debug this issue.
- Including WebKit support will help our E2E tests cover more bases to potentially expose any issues with future changes.

**Comment by terrazoon** [comment]
The Webkit tests all pass locally on a Mac.  I think the issue is with installing webkit in the Github (ubuntu?) environment.

I can see we are running `poetry run playwright install --with-deps` which in theory should be installing whatever is necessary for Webkit to run, but ... obviously it is not working.

**Comment by ccostino** [comment]
Putting this back in the backlog for when we have more time to investigate and see what's going on with this; perhaps an update to Playwright in the future will fix it as well!

**Comment by ecayer** [comment]
Level of effort means this isn't worth it.
