### ISSUE TITLE
Bug: No way to remove invitees with expired invites from the team members section

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1155]
### Who discovered this?

timothy.lowden@gsa.gov

### What happened?

In the team member section, if a person is invited to a service, but misses the 24 hour window to accept, their user card is indefinitely seen in team members. even if this has happened twice. It gives an option to `resend invite`, but we should also have an option to `delete user`

![Image](https://github.com/GSA/notifications-admin/assets/6556888/d8d7d1ea-c047-4048-800c-c46233217db3)

### Environment

staging

### What pages did this appear on?

https://notify-staging.app.cloud.gov/services/e50562b8-43f6-4063-99cb-f5ab43993b8c/users

### Detail the steps for someone to reproduce

1. Log in
2. Navigate to Team Members section via settings
3. Invite a new user
4. Make sure that new user does not accept until the invite expires
5. the user card will say invite expired but be indelibly present

### What browsers are you seeing the problem on?

Chrome

**Comment by ccostino** [comment]
Noting here that there is an `InvitedUser` object that this is working with, not the regular `User` object.

**Comment by ccostino** [comment]
@anagradova and I have talked through this some more and have confirmed the following:

- `InvitedUser` models keep track of and update state according to active, expired, or cancelled invites
- If a user tries to accept an invite after it's expired, they're presented with a message that tells them it's expired
- If a user tries to accept an invite after it's been cancelled, they're presented with a different message saying that the invite was cancelled

For the moment i's good to have the underlying record persist, at least until we confirm we just no longer need to hold on to it, so in this case it should just a matter of updating the template to not show any invites that have been cancelled; just filter them out from what gets displayed (probably by modifying the query that grabs them all to exclude cancelled ones).

If the user is invited again, we should test how this behaves currently too - does it let you do that, or does it error out?  And if it does let you, does it reuse the existing record or create a new one?  I think it's right that we want it to reuse the existing `InvitedUser` object and just update the timestamps on it where appropriate as well as reactivate it.
