### ISSUE TITLE
Fix date format in Batch review

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1171]

**Comment by tdlowden** [comment]
This is specific to the "Batch dashboard pages" and notably NOT the "Recent Batches" table. So the ask is to make the date formatting consistent. 

So we want it to mirror this format:

![image](https://github.com/GSA/notifications-admin/assets/6556888/5fecad2f-0b77-44c6-910a-dab8fc3a0d24)

An example URL is https://notify-staging.app.cloud.gov/services/e50562b8-43f6-4063-99cb-f5ab43993b8c/jobs/1c9b4056-dd8c-4f3f-b1b9-e428e6c0ab66

aka a "job page"
