### ISSUE TITLE
prep for Web Council Q&A 10/20

### ISSUE THREAD

**Issue by alexpandel** [GSA/notifications-admin#120]
**Context:** we gave [an initial preso](https://docs.google.com/presentation/d/1frFJTyQWkqOQWUH85RhuFrXw4-9Mf0kfzeTlt2CHsCU/edit#slide=id.g149752e63e2_0_195) to the [Federal Web Council](https://digital.gov/resources/federal-web-council/) in Sept and there were a lot of questions and interest, and we ran out of time to get to them all so they invited us back for this one!

From organizer/co-chair Marina Fox: "I envision that you guys would just have a more informal Q&A - we ran out of time last meeting and I felt like this would be beneficial to have agencies ask more questions as part of the discussion. Also if you have any update since last week and wanted to provide any other specifics into the work you've done - it would be great as well."

**To do:**
- [x] decide if we want to give any quick preso at the beginning to share any updates since our last one
- [x] think thru any other details/prep we need ahead of time (who's taking lead on preso, questions, etc)?
- [ ] prep quick deck/prompts to kick off Q&A

**Comment by tdlowden** [comment]
@alexpandel @em-herrick let's talk about this tomorrow during our cowork session?

**Comment by tdlowden** [comment]
@tdlowden Tim will do a brief review and a short demo, then we'll go to Q & A. @em-herrick will round out some questions we'd like to ask the group.
