### ISSUE TITLE
Define, document, and clean up the message limits variables

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1213]
- [x] Document the variables that correspond to the various smart-retention, annual, batch limits
- [x] Make sure their naming is descriptive and rename as necessary (adjust docs if necessary)
- [x] Hand off to front-end to have content and viz reflect necessary limits

**Comment by maomeara63** [comment]
@stvnrlly Please review the message parts limits as described in the [Style Guide](https://docs.google.com/document/d/1XREFnitvK2MFdBu5cV8k6iKAEz5LAoHcMZExBQNYbag/edit?usp=sharing).

**Comment by maomeara63** [comment]
@stvnrlly Can you confirm that the message limits are, currently 250,000 in a year and that there are no daily limits? If that is true, the places this needs to be reflected are:

- Dashboard: Delete Daily limits and updated 2024 limits to 250,000, having them increment with use.
- Usage: This page is inaccurate in many ways. If revising this isn't a short-term priority, I recommend deleted it to avoid confusion.

**Comment by stvnrlly** [comment]
Yes, the way it's described in the style guide is perfect. There is no daily limit.

**Comment by maomeara63** [comment]
@jonathanbobel These changes can be made.
