### ISSUE TITLE
User Story: Introduce Login.gov as a sign-in option

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1216]
### As a [type of user],

any type team member of Notify.gov (whether I use the product often or haven't logged-in in months).

### I want [an action or feature],

Understand that Notify.gov has a new log-in option 
Understand _why_ this has appeared on my log-in screen and what I am suppose to do with it
How long I have to ignore this and when I really need to stwich over

### So that [benefit or value].

I don't feel blindsided by a new interface change right away and feel comfortable with creating a new account when I have the time and brain space.

### Detailed condition or criteria that must be met for the user story to be considered complete.

- [ ] Link to new Login.gov sign-in is displayed
- [ ] Call to action clearly states what is expected of me
- [ ] I understand why this is something Notify.gov is asking of me
- [ ] I know how long I have to do this and what happens after this deadline.

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [x] @jonathanbobel Review Ken's current PR #1204 
- [x] @jonathanbobel to look at other patterns re: "staged roll out"
- [x] @jonathanbobel to mock-up a wireframe, if a staged roll out pattern makes sense and we need more than an alert treatment
- [x] @maomeara63 to draft an announcement for alert content
- [ ] #1262 

### List any dependencies that need to be resolved before starting or completing this user story.

- [ ] #986 

### Any additional information or context that might be useful for the team.

Live Login.gov environment will need to be turned on, this takes two weeks from our request. I am not sure if this is @ccostino or @stvnrlly?

**Comment by em-herrick** [comment]
@maomeara63 Please see Login.gov [Comms Plan](https://docs.google.com/document/d/1JMV6ny0coM21V2LpIwIBmqwRQT9ipl9C6UoaT_F6q0o/edit) and [FAQ document](https://docs.google.com/document/d/1hcvwzEsLiN4lInBYbmeDxp3fX6zpGx7SnGOMLij4RcM/edit) that will be sent to users. Can you use these as starting points to draft some content that will fit into @jonathanbobel wireframes (screen shot below). 

![Image](https://github.com/GSA/notifications-admin/assets/91496588/764ee0ad-8401-4608-ba06-18f0564f4678)

Wireframe of selected option.

**Comment by maomeara63** [comment]
@em-herrick @stvnrlly 

Please review proposed [Sign-in page copy](https://docs.google.com/document/d/1xjDJu8zImnC4R2g_omDDV1Ucenv0KmN95DFx_4JKq6k/edit?usp=sharing)
