### ISSUE TITLE
Update terms of use

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1219]

**Comment by maomeara63** [comment]
In support of Epic #449, 

Two outstanding questions to complete [Terms of use](https://docs.google.com/document/d/1W_SgnzwRPYWWWBtJ83RmXhY-Ya28Z93O_63NHl7vYnk/edit?usp=sharing):

1. Should this page be deleted or not? Tim thought maybe, and there is an argument to be made for not duplicating content. Em thought maybe not, since not all teammates will have access to the MOU. 
2. Need to define the process re data deletion when an account is deactivated. 
- Is this on Notify? Is it a manual process?
- Is there a "deactivate" interaction that automatically wipes the data? Do we need a ticket to develop that functionality?
- Is this the responsibility of the partner?

@stvnrlly

**Comment by em-herrick** [comment]
@stvnrlly should make the call here.

**Comment by maomeara63** [comment]
@jonathanbobel Per @stvnrlly, let's delete this page. We may repurpose later.
