### ISSUE TITLE
Update Pricing page

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1220]

**Comment by maomeara63** [comment]
In support of Epic #449.

To complete revisions to the [Pricing](https://docs.google.com/document/d/1MAr2oc3-D0FREYk8FPueWHHrSGJHHqopJcspzJ_zUws/edit?usp=sharing) page:

1. Need confirmation on impact of non-Latin scripts/logographic languages on pricing:
- Use of non-Latin scripts/logographic languages has similar impact to using Latin characters with accents/special characters as documented on existing page.
- Are there any know limitations on languages we can support?

@stvnrlly

**Comment by em-herrick** [comment]
Change `Pricing` to `Message Parts` (at least for pilot). Hold non-Latin scripts for next sprint of content work.

**Comment by maomeara63** [comment]
@jonathanbobel This is ready to have the content changes made. Changes are highlighted one way or another.

**Comment by jonathanbobel** [comment]
Addressed with #974
