### ISSUE TITLE
Update Delivery status page

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#1221]

**Comment by maomeara63** [comment]
In support of Epic #449.

To revise [Delivery status](https://docs.google.com/document/d/1nKnszv8VQ5JbM379ExIxfsiaw865hotXVx1Bnitgrxk/edit?usp=sharing) page:

1. Review revised content, which focuses only on the content on the Delivery status page. @em-herrick @stvnrlly 
2. Determine if we should add on this page or elsewhere information about the content available in the downloadable report.
- This page or repurpose Features.
- Confirm which columns are static and which change with format of partner's table
- Confirm additional notifications that may come through with some carriers

**Comment by em-herrick** [comment]
Hold report content for the next sprint of static work.

**Comment by maomeara63** [comment]
@jonathanbobel This is ready for content loading.
