### ISSUE TITLE
Bug: Phone numbers switch columns in downloadable report

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1228]
### Who discovered this?

Em

### What happened?

A bug happened! There are two places to download report data via the recent batch table and the full 7-day CSV report. Right now, depending on where you download the report from the phone numbers switch from the left to the right.

In both places, the other report updates have been made, so the issue is specifically with the phone numbers. 

### Environment

production

### What pages did this appear on?

Dashboard > Batch Table > Batch CSV download
Dashboard > Full 7-day CSV download

### Detail the steps for someone to reproduce

[Discussion in Slack](https://gsa-tts.slack.com/archives/C0107UC0W1M/p1708468105553959?thread_ts=1708462972.771279&cid=C0107UC0W1M) on desired state and solution diagnostic

**Comment by terrazoon** [comment]
I changed the batch report columns to match the columns in the full report:

"Recipient", "Template", "Sent by", "Batch File", "Carrier Response", "Status", "Time", <anything else in the csv other than phone>
