### ISSUE TITLE
Dashboard, step 1: Create new base template

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1234]
Base templates are located in `/app/templates`. We currently have a number of them, which are layered on each other based on the view. We think we may end up with one `base.html` and 2-3 variations for different page styles. Page styles should have names based on their layout rather than their usage.

The base template should contain the top nav, the side nav, and the footer. Basically, all of the page elements that are not view-specific. If we need to change this for specific views, we will prefer adding some logic in the base template rather than layering a intermediate template between the base and the view.

To complete:
- [ ] Update wireframe for dashboard
- [x] Create a new template alongside the existing base templates
- [x] Populate template with components, creating new ones rather than porting UK-based ones
- [ ] If useful, separate out components and reference them in the template
---
Update tasks: 2/26/2024

- [x]  Create a new base.html that consolidates templates with similar layouts
- [x]  Create a /new directory
- [x]  Create new directory of possible folder structures
- [x]  The base template should contain the top nav and the footer.

**Comment by heyitsmebev** [comment]
Based on my investigation, there are several templates that share similar layouts, therefore, we will not need some of the current layouts or we can move them to their respectable folders that make more sense. 

In addition, the new `base.html` template will have a combination of `main_template`, `admin_template`, `settings_template`, and `content_template`. 

Possible templates that could be it's own separate layout is `withnav_template` and `org_template`. Even then, we can work to simply these templates. 

### Old Layout Templates We Don't Need
- `withoutnav_template`.html Delete
- `main_template`.html Delete
- `settings_templates.html` Delete
- `settings_nav`.html (move to /new/navigation directory)
- `main_nav`.html (move to /new/navigation directory)
- `service_navigation.html` (move to /new/navigation directory)
- `org_template`, could be under it's own directory called /organization
- `org_nav.html` (move to /new/navigation directory)
- `content_template.html `Delete and consolidate to base template
