### ISSUE TITLE
Additional formatting within email template is expanded for some templates

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1253]
Are these suppose to be expanded? on other views it's not expanded 

![Image](https://github.com/GSA/notifications-admin/assets/53159604/186f1ef4-6361-480b-be16-fe89de9d34f9)

**Comment by heyitsmebev** [comment]
Not able to replicate. These expanded boxes seems like it's working as it should 


![Image](https://github.com/GSA/notifications-admin/assets/53159604/a9282b81-1fad-4abd-855e-a0fa9add2ba6)
