### ISSUE TITLE
Update Notify.gov logo on Login.gov sign-on page

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1262]
Pending approval and before we launch Login.gov. Change the flag icon to our Notify.gov logo.

![Image](https://github.com/GSA/notifications-admin/assets/91496588/b0a429e7-0a07-4bea-8b3a-df0642c798fe)

**Comment by jonathanbobel** [comment]
![Image](https://github.com/GSA/notifications-admin/assets/1233986/a623f6cf-a3e2-4341-b70d-d84379f9b8d4)

**Comment by terrazoon** [comment]
I submitted a Zen request to deploy the new logo to production.

**Comment by terrazoon** [comment]
#8082
