### ISSUE TITLE
User Story: Update 'change email' flow in Settings to include Login.gov

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1269]
**As an existing Notify.gov user, I want to change my user name and password (which in the future will be managed/connected to Login.gov)**

**UX/UI Tasks:**
- [x] Draft notice that if a user wants to change their password or email they should do so in Login.gov
- [ ] Display alert/notice copy on Settings page
- [ ] Remove user ability to `change password` and `change email ` from Settings menu

**Dev Tasks:**

**Comment by em-herrick** [comment]
From Ken:

## Description

Right now when we log in with login.gov, we have everything keyed to the user's email address:

1. Redirect user to login.gov
2. User logs in at login.gov
3. We get back the user's email address
4. We look in the database for the user by email address
5. If we find a match, we activate that user


This has the disadvantage that if the user changes their email address in login.gov, they will no longer be recognized in our app.

Login.gov actually recommends that we not use the email address in this way.  Instead they also return a UUID for the user, and we should use that instead.  The new flow should be:

1. Redirect user to login.gov
2. User logs in at login.gov
3. We get back the user's uuid
4. We look up the user by uuid (new column in users table in db)
5. If we find a match, we activate that user
6. We also check to see if the user's email has changed, and if it has we update it accordingly.

**Comment by ccostino** [comment]
Based on the notes that @terrazoon wrote up, there's a separate API task that has to happen as well that we'll need to write an issue for.  This involves at least the following:

- Adding support for a new column in the `Users` table in the database for the UUID from Login.gov
- Adjusting the user look-up code to work off of the Login.gov UUID (if it exists)
- Adding support to update the email address if it's been changed during the login flow

@terrazoon did I miss anything?  Let me know if there's anything else to consider for the API side, and we'll get an issue written up for that work. 🙂

**Comment by em-herrick** [comment]
Content for user alert about username/password/2fa: https://docs.google.com/document/d/1IhBuJVZEakJClpf4yMEJXAY89mc_skV7DNT1wLubCSI/edit

**Comment by maomeara63** [comment]
@em-herrick I updated the content. Please review.

**Comment by em-herrick** [comment]
Looks good to me, thanks for the edit! @jonathanbobel consider this final copy for palcement.
