### ISSUE TITLE
Update service invitation email template to include Login.gov information

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1270]
To complete:

- [x] Review existing email template
- [x] Revise to better convey information to both new and existing Notify.gov users
> If new: create an account, then join a service.
> If existing: just join new service
- [x] Add copy for new users about login.gov
- [x] Update copy in `/app/config_files/templates.json`
- [x] Run template update Flask command after deployment

New copy for "Service Invite" email being drafted here: https://docs.google.com/document/d/1gcj7ID_S5AgwhiRTfl9n6Z6959EvFUaH_FE81pszM7w/edit

**Comment by em-herrick** [comment]
Create two new email templates

- one for new users
- one for existing users

**Comment by em-herrick** [comment]
Update on comment above—Jon and Em have decided to start with one email template with an extra line of content for new users and see what kind of feedback we get.

**Comment by jskinne3** [comment]
The text of the email I see matches [the drafted text google doc](https://docs.google.com/document/d/1gcj7ID_S5AgwhiRTfl9n6Z6959EvFUaH_FE81pszM7w/edit) except for one part: the text under the horizontal line in the google doc is not included in the email.

This is the text missing from the email:
> Notify.gov uses Login.gov to allow you to sign in safely. Login.gov is a secure sign in service to help you access participating government agencies’ digital touchpoints.

This is a screenshot of the email I see:
![Screenshot 2024-04-17 at 10 11 22 AM](https://github.com/GSA/notifications-admin/assets/546123/79a0e4e3-7359-45e1-9e11-eb75e0a70aba)

**Comment by em-herrick** [comment]
There is also some additional copy that should be removed above the `Join Service ` link.

We need to understand if this is a code/template issue or just missing pieces when copy and pasting the new copy. 

Please review template code and verify new text has been copied over:

> [Name] has invited you to collaborate on [service] on Notify.gov.
> 
> Notify.gov makes it easy to keep people updated by helping you send text messages.
> 
> Join Service <link>
> If you’re new to Notify.gov, you will first be directed to Login.gov to create an account with us. 
> 
> This invitation will stop working at midnight tomorrow. This is to keep [service] secure.
> 
> ______________________________
> Notify.gov uses Login.gov to allow you to sign in safely. Login.gov is a secure sign in service to help you access participating government agencies’ digital touchpoints. 
> 




`

**Comment by em-herrick** [comment]
@ccostino yes, just did a QA—this looks great!  we're good to go.

**Comment by ccostino** [comment]
Well at least the email looks good! 😆 😭 

Thanks for following up with these, @em-herrick!  I think they might be separate errors and if so, we should create a new issue for those.  I'll take a look to confirm.

**Comment by ccostino** [comment]
Oh, wait @em-herrick - in that first message it looks like it was telling you that you can't accept the invite for another user.  You were probably already logged in to the site in one account and tried to accept a service invite for a different account in the same window; had you done this in an incognito window or a different browser and signed in fully with the other user, it would have worked.

This is a known issue, where the user invite check is happening _after_ we ask the user to fill in info, and we know it's not ideal.

**Comment by em-herrick** [comment]
ah yes, duh. Let me check

**Comment by em-herrick** [comment]
@ccostino yes it worked well when I was in incognito mode! I need to remember this when doing QA.

**Comment by ccostino** [comment]
Woohoo!  Okay - I think we have an issue already written up for the profile piece but if not we'll write one.  In the meantime, we'll do a final test of this once we have our next prod deploy and close this out!  Thanks, @em-herrick! 🙂

**Comment by ccostino** [comment]
Invitation issue is now captured here! https://github.com/GSA/notifications-admin/issues/1501

**Comment by ccostino** [comment]
This is now live and the updated content is in place with the service invite email template!  The other issue with the complete your profile step when accepting an invite for someone else is also done and in place.

I'm closing this out as I think all things are now accounted for!  @em-herrick, please feel free to re-open or create a new issue if there are still any lingering problems or you notice something else. 🤞 that's not the case! 🙂
