### ISSUE TITLE
Login.gov handle email changes

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#1277]
## Description

Right now when we log in with login.gov, we have everything keyed to the user's email address:

1. Redirect user to login.gov
2. User logs in at login.gov
3. We get back the user's email address
4. We look in the database for the user by email address
5. If we find a match, we activate that user

This has the disadvantage that if the user changes their email address in login.gov, they will no longer be recognized in our app.

Login.gov actually recommends that we not use the email address in this way.  Instead they also return a UUID for the user, and we should use that instead.  The new flow should be:

1. Redirect user to login.gov
2. User logs in at login.gov
3. We get back the user's uuid
4. We look up the user by uuid (new column in users table in db)
5. If we find a match, we activate that user
6. We also check to see if the user's email has changed, and if it has we update it accordingly.

**Comment by em-herrick** [comment]
Issue being tracked in #1269 . Copied Ken's notes from this issue to the other one.
