### ISSUE TITLE
About Delivery Statuses - Copy ready for implementation

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1305]
### Problem or Need
Based on engaging with partners so far, we've discovered that information about delivery statues is unclear. Users lack clarity on:

- What delivery statuses are (how we get them, what kinds exist, how they are
- How they are displayed (timing, how we get them, what each mean)
- how they can use them in their outcome tracking

### Benefit
If we solve this:

- Users will be able to view descriptions of each specific delivery status (delivered, pending, and states of failed)
- Users will be able to view description of what backend actions are involved in delivery statues and our relationship with phone carriers/AWS

### Acceptance Criteria

- [x]  Review statuses returned by AWS and how they are used in Notify (in app and in reports)
- [x]  Map returned statuses to desired state to be presented to partners
- [x]  Provide description of what is in each state
- [x]  Review documentation
- [ ]  Implement

###

**Comment by em-herrick** [comment]
As part of our delivery status clean-up effort, can we also summarize the concept and process that our delivery status go through? The below pieces of content is the only thing that exists about delivery statuses in the sending workflow and its confusing. 

`Messages remain in a pending state until carrier status is received, typically 5 minutes.`


What's a carrier? What is a carrier status? How does it relate to Notify?
Is this a place to add an overview of our sending process? Something like:

`Notify.gov sends messages directly to indvidual phone carriers...`



![Image](https://github.com/GSA/notifications-admin/assets/91496588/8e6deb18-d15c-4ec0-80ff-75d3c0372f14)

**Comment by maomeara63** [comment]
@em-herrick @stvnrlly 

I've drafted a revision to the delivery status page to reflect both the statuses on the dashboard and those that user might see in reports. Please review.

[Delivery status](https://docs.google.com/document/d/198Faep7Aqsl8Hqp4b45y74tlgcWt5CPsNnnogteJHHY/edit?usp=sharing)

**Comment by em-herrick** [comment]
Sorry for my delay in reviewing this!! It's looking good. @stvnrlly I have some outstanding questions for you if you could take a look before @maomeara63 does another pass?

**Comment by em-herrick** [comment]
Do we still need want/need  indvidual issue? It seems similar to this content

-  #1011

**Comment by maomeara63** [comment]
I think #1011 is too much info for users. I could be wrong, but I rec closing #1011.

**Comment by em-herrick** [comment]
@jonathanbobel Can you please replace the existing Delivery Status content page with this new copy:

https://docs.google.com/document/d/198Faep7Aqsl8Hqp4b45y74tlgcWt5CPsNnnogteJHHY/edit#heading=h.axmt6rx1wx
