### ISSUE TITLE
Add information about federal connection to landing page

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1334]
We want to make it clear that Notify.gov can work with the various levels of government, but needs a federal connection. This is covered well in the partnership process, but it would be helpful to have that up front as well.

- [x] Provide link to description in partnership documentation @em-herrick 
- [x] Draft content @maomeara63 
- [x] Review content
- [ ] Add content to home page

**Comment by maomeara63** [comment]
@stvnrlly Do you envision this information on the landing page or in the additional "sales" content that will be added for self-serve?

**Comment by stvnrlly** [comment]
Both. I think we'll want to highlight this information briefly on the landing page and then in more detail in partnership-specific content. Once the additional content is public, we might be able to move it off the landing page and just link to the additional stuff.

**Comment by em-herrick** [comment]
This text looks good from my end, I think we can move to getting this on the website.

This additional text should be a new paragraph at the bottom of the landing page under the `About` section:
```
Eligible partners include federal agencies as well as state, local, territorial, tribal agencies
administering federally funded programs. As part of the onboarding process, non-federal
programs must specify the federal program that the messages they want to send are related
to. TTS will also seek concurrence from the federal funder.

We prioritize partnerships focused on use cases related to increasing transparency and
reducing the burden of navigating government programs for low income individuals and
families.

```
