### ISSUE TITLE
User story: View Dashboard as a User

### ISSUE THREAD

**Issue by VRagulina** [GSA/notifications-admin#1367]
Epic: #1302 

_**As a user, I want to access a comprehensive dashboard so that I can view a high level of service activity.**_

### **Acceptance Criteria:** 

- [ ] The dashboard must only be accessible to authorized personnel.
- [ ] #1484
- [ ] #1485
- [ ] #1486
- [ ] #1487
- [ ] #1488
- [ ] #1489
- [ ] #1490

Figma: https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?type=design&node-id=3047-4580&t=qTagD5WTtNcuKF7q-0&scaling=scale-down&page-id=3047%3A4396&starting-point-node-id=3047%3A4580
![Image](https://github.com/GSA/notifications-admin/assets/53159604/fc159f90-2f77-4490-8c0d-e0f4716b61fa)

**Comment by heyitsmebev** [comment]
https://github.com/GSA/notifications-admin/issues/1492

move it here
