### ISSUE TITLE
Bug: User reports issues downloading 7-day CSV

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1381]
We've decided to adjust the cache used to store the information that the reports pull in the 7-day report to provide a bit of a relief and workaround for users while we continue figuring out our options and path forward for a longer-term solution.

## Implementation Sketch and Acceptance Criteria

- [x] Adjust the cache used for the reports to live longer, e.g., 7 days (or whatever makes the most sense)
- [x] Test that the reports continue to work and attempt to recreate the performance issues in staging to see if the extended cache helps at all
- [x] Adjust any tests as needed

## Security Considerations

- Some PII may stay within the cache for the extended period of time, but this is a trade-off we're willing to make at the moment while we work on a long-term solution.  Once we have decided on our future approach, we'll revisit this and readjust the cache again.

## Original bug report details

The information below is the original bug report and information we had of this issue.

### Who discovered this?

frank.li@dshs.wa.gov

### What happened?

A bug happened! From partner: We are experiencing the system hiccups when we download the U.S notify response report from the Text messages portal. I’m able to download the large files from the other systems; so, it’s not network issue of our system.

Follow-up email a few hrs later: The download stuck spinning after click; and I can see the speed dropping from 30 B/s till 0; then stop completely. However, the download can work after trying multiple times. The issue started since Last Fri; and everything was fine before it.

### Environment

production

### What pages did this appear on?

7-day download

![Image](https://github.com/GSA/notifications-admin/assets/91496588/5b4b4d86-c5dc-4afb-bfa5-133e3bc38efe)

### Detail the steps for someone to reproduce

1. Navigate from dashboard to reports
2. Download 7-day report

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by em-herrick** [comment]
@ccostino I added the ticket from frank here, given his last message not sure if its needed, but I will let you decide about that. :)

**Comment by ccostino** [comment]
Thanks, @em-herrick!  This is warranted given it's intermittent but is happening; when I tried it myself in production I encountered the same issue.  It's unclear what might be happening other than "a network blip" at the moment, no errors were showing up in the logs or anything, and we've not seen any other reports of this behavior.

My other underlying suspicion is something is stalling with the data processing when generating the report and it's just long enough that it causes the browser request to timeout, but it eventually completes anyway in the backend and then is cached to some degree server-side, so the following requests work fine.

If this is the case and there's no easy performance fix to be made, we probably need to shift the reports to be an asynchronous task with a front-end polling mechanism to check on the report status and present the user with an option to download it when it's ready.

FEC does this with their API! 🙁 For reference:  [the download view resource](https://github.com/fecgov/openFEC/blob/develop/webservices/resources/download.py) and [the download task](https://github.com/fecgov/openFEC/blob/develop/webservices/tasks/download.py)

**Comment by ccostino** [comment]
Thanks, @em-herrick! @terrazoon confirmed that this the search by phone number feature has more or less stopped working based on the recent changes we've made.  We should get a separate issue written up to figure out what to do with it and if we want to just remove it or make it work again.

**Comment by ccostino** [comment]
I think I've also uncovered a possible error that is taking place with the report generation.

Here's the stack trace:

```
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/eventlet/greenthread.py", line 221, in main
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 157, in handle
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 55, in handle
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 115, in handle_request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/newrelic/api/wsgi_application.py", line 44, in __iter__
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/helpers.py", line 118, in generator
File "/home/vcap/app/app/utils/csv.py", line 110, in generate_notifications_csv
File "/home/vcap/app/app/notify_client/notification_api_client.py", line 49, in get_notifications_for_service
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/notifications_python_client/base.py", line 41, in get
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/notifications_python_client/base.py", line 60, in request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/notifications_python_client/base.py", line 99, in _perform_request
```

It results in a `503 - Request failed` error, and the URL that triggered it was `/services/<SERVICE_ID>/download-notifications.csv` (Washington State's service ID in this case).

**Comment by stvnrlly** [comment]
I think our approach here should be that time-based reports are always deidentified, so they should not include any CSV extraction. If users want to get more detailed information, they can use the batch report (while the CSV is still available).

**Comment by em-herrick** [comment]
With the delivery status redesign epic in progress, we are def going to get much more information about how we should treat these reports in the future, so I'd like to focus on a short term fix here vs. a long term (read: high effort) one.

 I don't exactly know user need between batch and time based report, but I am a bit worried about having now way to easily pull phone number data from 10 one-off batches without going in and downloading each 1 by 1, that feels like a pain. Could we split the difference here (if I am following)?

- Data wranglers that want phone number data should default to the batch reports
- Time-based reports are deidentified and can be downloaded directly in the app 
- Time base reports that can be requested via email download with all information (unless this is big effort?)

More long term, UX would like to move towards look up tables that are filterable, so users can download a selection of batches or phone numbers that meet their needs.

**Comment by ccostino** [comment]
@em-herrick, @stvnrlly and I caught up about this some more today and talked through a variety of options for what's possible.  We settled on the following to focus on for the short term:

- Offer options to generate 1, 3, and 5 day reports in addition to the 7 day report
- Identify any possible performance improvements to be had with the CSV processing

Furthermore, we found out that one partner is already looking at the report daily, so having a 1 day report if possible makes sense here, especially if it'd help cut down on the amount of processing that needs to be done (they also liked the prospect of having these options available).

We should create separate issues for these two tasks while we continue to work toward a desired long-term solution.  @em-herrick or @stvnrlly, did I miss anything?

**Comment by ccostino** [comment]
I created the following two issues for this work:

- https://github.com/GSA/notifications-admin/issues/1403
- https://github.com/GSA/notifications-api/issues/910

**Comment by terrazoon** [comment]
I did some profiling locally after doing 50 one-off messages:


the downloads (if the job is not in the cache) take anywhere from 250 milliseconds to 1400 and average out at about 400, which is 90% of the time the report needs to generate.
So there is no optimization available in the code itself.  I think the options might be:
increase the cache time to 7 days (hmmm)
increase the cache time to 1 day and make a one day report with phone numbers, then remove phone numbers from the 7 day report
just remove the phone numbers from the 7 day report

**Comment by ccostino** [comment]
I'm moving this back into `Up Next` - let's get the cache adjusted for the interim to provide a bit of a boost/relief to folks while we work on sorting out the other long-term options!

**Comment by ccostino** [comment]
@terrazoon I added more details in the issue summary and description; please feel free to add any other context I missed!

**Comment by ccostino** [comment]
The update to increase the life of the cache has been deployed to staging and is ready for testing! (cc @stvnrlly)

**Comment by ccostino** [comment]
This is now live!
