### ISSUE TITLE
User Story: Alter our sign-in page after we switch over to Login.gov so as to not confuse our users

### ISSUE THREAD

**Issue by jonathanbobel** [GSA/notifications-admin#1423]
### As a [type of user],

Text Sender

### I want [an action or feature],

A page after I click "Sign In" from the home page to tell me what Login.gov is before I agree to use it to sign in

### So that [benefit or value].

I am not confused by the changeover on Notify.gov from a native login to the Login.gov experience

### Detailed condition or criteria that must be met for the user story to be considered complete.

- Remove native user name and password fields as well as the button to Sign In
- Change content to reflect that we are now using Login.gov
- This change is time-boxed, in 1 month we will switch over from this experience to the user clicking straight from the Home page to go to Login.gov

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [ ] Delete native user name and password fields as well as the button to Sign In
- [ ] Change content to reflect that we are now using Login.gov

**Create an issue to be done in 1 month to:**
- [ ] Remove this page
- [ ] Have Sign In button on Home Page go directly to Login.gov

### List any dependencies that need to be resolved before starting or completing this user story.

April 16th switchover date to happen

**Comment by em-herrick** [comment]
@jonathanbobel We'll also need to consider an additional sign-on page we need to add login.gov. The page thats for folks who have not signed-in in a while (if this still applies with our new time out):

<img width="1070" alt="Screenshot 2024-04-16 at 12 44 35 PM" src="https://github.com/GSA/notifications-admin/assets/91496588/f39b9866-35ba-4c6f-b3f8-ff58cadcb80f">
