### ISSUE TITLE
Bug: Replace inaccurate copy on Create Profile page

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1443]
### Who discovered this?

Em

### What happened?

A bug happened! Added a new `Create your profile` page as part of Login.gov deploy. Currently displaying inaccurate copy under `Mobile number`.

Remove: `We'll send you a security code...`
Replace with: `We need your number so you can send yourself test texts.`

![Image](https://github.com/GSA/notifications-admin/assets/91496588/fe75fd01-ee39-4d47-be5a-3a4e37fffc18)

### Environment

production

### What pages did this appear on?

Set up your profile

### Detail the steps for someone to reproduce

This page appears when:

1. A user has been invited to a Notify Service and doesn't yet have a Notify profile (so considered a new Notify.gov user)
2. They creates an account/ sign-in on Login.gov
3. They are redirected to Notify.gov for the first time

**Comment by heyitsmebev** [comment]
![Image](https://github.com/GSA/notifications-admin/assets/53159604/4e316d23-5b83-494d-ba27-813e3eeaa4a9)

@em-herrick Seems like the text was already updated. I cannot reproduce. It could have been a caching thing.
