### ISSUE TITLE
Bug: A invitedUser with a cancelled invite is still able to register after the cancellation

### ISSUE THREAD

**Issue by anagradova** [GSA/notifications-admin#1445]
### Who discovered this?

Anastasia 

### What happened?

An invited user is created and the invite is sent. The user's invite is canceled. The system still allows the invited user to complete registration. 
![image](https://github.com/GSA/notifications-admin/assets/108748167/233117db-2b74-4440-9962-fe440dda8b72)

### Environment

staging

### What pages did this appear on?

manage-users.html template

### Detail the steps for someone to reproduce

1. Invite user
2. Cancel invite
3. Utilize link to register
4. Complete registration
5. Look at team members

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by ccostino** [comment]
Thanks for catching this, @anagradova!  I have a PR ready to fix this: https://github.com/GSA/notifications-admin/pull/1582
