### ISSUE TITLE
Service invitations aren't working properly

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#1447]
## Description

1. Receive an invite from someone else for their service on staging ('A1').
2. Use the invite email and log in.  Observe that you are not looking at service A1, you are looking at your own service ('B1').

It appears like, even though the login step goes through successfully, you are not always added to the service you've been invited to.

## Security considerations

At this time it looks like you are either added to the service you're invited to, or you are looking at your pre-existing services, so there do not appear to be any security considerations.

It might be worth looking at organization invites as well.

**Comment by ccostino** [comment]
Organization invites are definitely wonky still, though we aren't using them at the moment.
