### ISSUE TITLE
Scope duties and skill sets for potential 18F staffing

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#145]
- [ ] 2 engineers vs 1 engineer (led by @stvnrlly)
- [x] content designer and product designer (led by @em-herrick)

**Comment by stvnrlly** [comment]
Draft is here: https://docs.google.com/document/d/1I_K3JkpdSLT9g72gcOUIRvCXzw5LYwFnUrQH9eVwnw8/edit
