### ISSUE TITLE
Update the lodash JS library

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1460]
We need to update the `lodash` JS library ([see Dependabot for details](https://github.com/GSA/notifications-admin/security/dependabot/61)).

This might result in opening a much larger can of worms with our JS dependencies, so hopefully we can keep it to just this for now but use it as a basis for updating other libraries in the new future.

## Implementation Sketch and Acceptance Criteria

- [x] Investigate what it would take to get `lodash` updated on our side, and just `lodash` and whatever it requires.
- [x] Make the necessary changes
- [x] Make sure the site still builds properly (especially static assets)
- [x] Make sure the site still functions correctly
- [x] Make sure all tests pass

## Security Considerations

- We need to make sure we're keeping our libraries up-to-date to address security advisories.

**Comment by terrazoon** [comment]
I think this is a false alarm from dependabot:

The latest version of lodash is 4.17.21 ... we are on it
The latest version of lodash.template is 4.5.0 ... we are on it

I think dependabot is confusing lodash.template with lodash and thinking it should be 4.17.21, but that's not possible.

**Comment by ccostino** [comment]
Thanks for taking an initial look at this, @terrazoon!  I dug into it a bit more myself and there seem to be a few pieces with this that are tangled together; you're right that the report is confusing the packages it seems.

We're going to put this back into the backlog for a frontend engineer to take a closer look at as a part of updating our JavaScript dependencies.
