### ISSUE TITLE
When user invite members, user does not get redirected

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1468]
### Who discovered this?

Beverly

### What happened?

I get an error message when I invite a user. The invitation gets sent, but the UI shows error message. 

![Image](https://github.com/GSA/notifications-admin/assets/53159604/f5ad7e71-94ef-4365-b744-fab8beee54fa)

### Environment

staging

### What pages did this appear on?

http://localhost:6012/services/b1226555-1f1a-472c-9086-043b0a69f4ec/users/invite

![Image](https://github.com/GSA/notifications-admin/assets/53159604/b56c960b-ad89-4ee2-bba2-73681ba24aba)

### Detail the steps for someone to reproduce

Settings => Team members => Invite a team member

**Comment by ccostino** [comment]
@heyitsmebev, when you have a free moment, would you mind taking a look in staging again and seeing if this is still an issue or if it's been fixed with the recent updates?  Thank you!

**Comment by heyitsmebev** [comment]
@ccostino I'm no longer having this issue. It's working as expected
