### ISSUE TITLE
Visualization tools: A recent activity bar chart that displays the total number of messages within given timeframe

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1484]
As part of the larger redesign, create a display that reflects the total messages sent.

- [x] The user should be able to view a chart that represents the messages data
- [ ] #1884
- [x] Connect frontend with new API endpoints #1558 

![image](https://github.com/GSA/notifications-admin/assets/53159604/d5509091-220d-4dff-b0c5-70b733a90dba)

Related:
User Story: How many messages have been recently sent across service GSA/notifications-admin#1095
User Story: How many messages are sent by year GSA/notifications-admin#1093

Backend ticket that relates to this issue: https://github.com/GSA/notifications-admin/issues/1513

**Comment by heyitsmebev** [comment]
From what I've gathered when looking into API calls:

We can retrieve jobs from the past 7 days but not from 30+ days ago, likely due to a pagination limit set to page=1.

You can use the get_jobs method in job_api_client to obtain the delivery status. For example, the response might include:
`'statistics': [{'count': 1, 'status': 'delivered'}]`

However, you may want to consider filtering out the scheduled jobs that were canceled.

Alternatively, you can use **get_immediate_jobs** to retrieve all jobs without having to filter out the scheduled jobs that were canceled.

**Comment by ccostino** [comment]
Hi @heyitsmebev and @jonathanbobel!  This issue is in review, is everything ready to go with it?  Or was this already deployed with the last production release?

**Comment by heyitsmebev** [comment]
@ccostino I will move the last item that’s has not been checked out of this ticket. Overall this ticket is complete.
