### ISSUE TITLE
Sort feature: Users should be able to sort through recent jobs and templates by header

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1488]
User should be able to sort through recent jobs and templates table 

![image](https://github.com/GSA/notifications-admin/assets/53159604/9571d389-a15d-4f89-94e9-e58e802bf411)
![image](https://github.com/GSA/notifications-admin/assets/53159604/d67b6d63-d151-495e-ac20-7d485374ba9b)

**Comment by em-herrick** [comment]
Seems like @heyitsmebev was able to get this feature working as part of her Activity page exploration.

**Comment by em-herrick** [comment]
yep!
