### ISSUE TITLE
Upgrade Node.js to the latest stable release

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1495]
We need to upgrade our [Node.js](https://nodejs.org/en) version in the admin project to the latest stable release.  This may require a bit of extra project configuration and it should also prepare us to update our JavaScript packages as well, but the package updates should be handled separately.

## Implementation Sketch and Acceptance Criteria

- [x] Update our project's use of [`nvm`](https://github.com/nvm-sh/nvm) to the latest version
- [x] Using `nvm`, update the project to the latest stable release of Node.js
- [x] Ensure that `npm` is also updated as part of this (it often gets updated beyond what's in the latest Node.js release)
- [x] Modify any project configuration (environment variables, application configuration, etc.) that requires updating to support the new release
- [x] Update the admin project's [README](https://github.com/GSA/notifications-admin/blob/main/README.md) to reflect any changes in set up and version numbers

## Security Considerations

- We need to make sure we're running supported versions of Node.js; even though it's not used to run any application code, it is used to manage our JavaScript packages and static assets.
- Updating Node.js helps our project stay secure with the latest updates and patches that address security vulnerabilities and stability issues.

**Comment by ccostino** [comment]
Adding @alexjanousekGSA to this issue to help review and test!
