### ISSUE TITLE
What is priority queue (for templates) and do we want to keep it?

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#150]

**Comment by rahearn** [comment]
Looks like priority queue can be set by platform admins, and puts the resulting messages in a fast track (theoretically, I don't think our current celery use actually prioritizes any queues).

I think we should leave it in for now. It's hidden from end users and doesn't feel like it's worth the effort to do anything with it

**Comment by rahearn** [comment]
@stvnrlly assigning to you for review and if you think anything else should be done with this.

**Comment by stvnrlly** [comment]
Cool, I captured that in some docs and otherwise it sounds like we're good.
