### ISSUE TITLE
Remove PDF preview functionality

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-admin#151]
Follow up work from https://github.com/GSA/notifications-admin/pull/148#discussion_r1004886528

Investigate template preview feature and decide if it should be removed, commented out, or left in.

**Comment by stvnrlly** [comment]
This is the repo in question: https://github.com/alphagov/notifications-template-preview. I'm in favor of using it, but we don't have it up and running yet.

**Comment by stvnrlly** [comment]
I believe this is just for letters, so we should be able to remove it entirely.

**Comment by stvnrlly** [comment]
This may just be a matter of removing `TEMPLATE_PREVIEW_API_*` from `config.py` but this should be confirmed as part of removal.
