### ISSUE TITLE
API Research - Notification Stats by User / Service

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1529]
## Acceptance Criteria

We're looking for a back-end engineer to help the front-end with a bit of stock-taking research. For the following feature:

- [ ] Review the API structure of relevant APIs (Messages, Services, Stats, Quotas etc.)
- [ ] Document your findings and recommendations in a new markdown file in the [`docs/` directory](https://github.com/GSA/notifications-api/tree/main/docs)

We'll be reviewing these together to determine our next steps for implementation work.

## Implementation Sketch

When researching the API and documenting your findings, please keep these things in mind:

- [ ] What’s currently available in the API?
   - This could mean a couple of things: actual endpoints that already exist, and/or underlying parts of the data model that exist but are not exposed yet.  Be sure to look at both!
- [ ] What might we be able to consolidate or clean up?
   - Again, take into account both the existing API endpoints and the underlying data model for things that exist but aren't currently exposed.
- [ ] What might we need to do/create?
   - Things to consider:  is it just a new endpoint(s)?  Do we need new data model properties that then need to be exposed (and if so, what kind of migration(s) might that entail)?
- [ ] What work might already be in flight and incomplete/not reviewed yet?
   - Be sure to [check existing open PRs](https://github.com/GSA/notifications-api/pulls) to see what might have been done already but isn't finished/tested/reviewed!
- [ ] What is an estimated level of effort for each feature based on the previous questions?
   - This is just a high level estimate, nothing super fancy.

## Feature 1: Notification Stats - Activity Snapshot:
At the top of the page, we would like to display a bar chart that allows users to view:

- indvidual user activity
- Entire service activity 

data from different periods
- 7 days, 30 day period, and 12 month period within a given year.

Each bar will show totals of **messages delivered/failed/requested** within a given date range and resource. 

<img width="679" alt="image" src="https://github.com/GSA/notifications-admin/assets/53159604/95db1a7c-c240-446a-bcce-4137d302db5a">

<img width="652" alt="image" src="https://github.com/GSA/notifications-admin/assets/53159604/36325dfa-92af-45de-a106-6457ad26ad10">

<img width="662" alt="image" src="https://github.com/GSA/notifications-admin/assets/53159604/beeea4d6-e1dd-4837-b229-869241421838">

Possible endpoints: 

```json
curl --location -g '{{base}}/service/{{service_id}}/statistics’
```

I found this endpoint that provides stats within a given 7 day period, the problem with this endpoint is that it doesn’t provide a daily break down.

```json
{
  "data": {
    "email": {
      "delivered": 0,
      "failure": 0,
      "requested": 0
    },
    "sms": {
      "delivered": 3,
      "failure": 0,
      "requested": 3
    }
  }
}
```

`{{base}}/service/{{service_id}}/notifications/monthly?year=2024
`
`{{base}}/service/monthly-data-by-service?start_date=2024-01-01&end_date=2024-05-31

**Comment by ccostino** [comment]
Noting here that once we shift to implementation of any new endpoints we need for this work we'll be splitting the work up and focusing on pieces at a time, even though we're capturing everything with the research and documentation here.

**Comment by ecayer** [comment]
We believe this is done now!
