### ISSUE TITLE
API Research - Allowance Count Down

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1534]
## Acceptance Criteria

We're looking for a back-end engineer to help the front-end with a bit of stock-taking research. For the following feature:

- [x] Review the API structure of relevant APIs (Messages, Services, Stats, Quotas etc.)
- [x] Document your findings and recommendations in a new markdown file in the [`docs/` directory](https://github.com/GSA/notifications-api/tree/main/docs)

We'll be reviewing these together to determine our next steps for implementation work.

## Implementation Sketch

When researching the API and documenting your findings, please keep these things in mind:

- [x] What’s currently available in the API?
   - This could mean a couple of things: actual endpoints that already exist, and/or underlying parts of the data model that exist but are not exposed yet.  Be sure to look at both!
- [x] What might we be able to consolidate or clean up?
   - Again, take into account both the existing API endpoints and the underlying data model for things that exist but aren't currently exposed.
- [x] What might we need to do/create?
   - Things to consider:  is it just a new endpoint(s)?  Do we need new data model properties that then need to be exposed (and if so, what kind of migration(s) might that entail)?
- [x] What work might already be in flight and incomplete/not reviewed yet?
   - Be sure to [check existing open PRs](https://github.com/GSA/notifications-api/pulls) to see what might have been done already but isn't finished/tested/reviewed!
- [x] What is an estimated level of effort for each feature based on the previous questions?
   - This is just a high level estimate, nothing super fancy.

## Feature 4: Total Message Allowance:

Lastly, the total message allowance.

Follow-up question: Are the different accounts/resources affected by this total?

<img width="368" alt="image" src="https://github.com/GSA/notifications-admin/assets/53159604/9eb608b3-af34-4ebe-90da-a33455f8ee4d">

Possible endpoint: 
`{{base}}/service/{{service_id}}/billing/monthly-usage?year=2024
`

**Comment by xlorepdarkhelm** [comment]
In admin:

/services/<uuid:service_id>
service dashboard
{job_id, time_left, download_link, view_job_link, created_at, notification_count, created_by, notifications}

/services/<uuid:service_id>/template-usage
template_usage
{id, name, type, requested_count}

/services/<uuid:service_id>/usage
usage
-> (get_annual_usage_breakdown) {emails_sent, sms_free_allowance, sms_sent, sms_allowance_remaining, sms_cost, sms_breakdown}
* where are the templates this renders? `views/usage.html`

--------------------

In api:

billing_blueprint.route("/monthly-usage")
get yearly usage by monthly from ft billing
{month, notification_type, chargeable_units, notifications_sent, rate, cost, free_allowance_used, changed_uinits}

billing_blueprint.route("/yearly_usage_summary")
get yearly billing usage summary from ft billing
{notification_type, chargeable_units, notifications_sent, rate, cost, free_allowance_used, charged_units}

billing_blueprint.route("/free-sms-fragment-limit")
get free sms fragment limit
{free_sms_fragment_limit, financial_year_start}

performance_dashboard_blueprint.route("")
performance dashboard
{total_notifications, email_notifications, sms_notifications, notifications_by_type, processing_time, live_service_count, services_using_notify}

platform_statistics_blueprint.route("volumes-by-service")
volumes by service report
{service_name, service_id, organization_name, organization_id, free_allowance, sms_notifications, sms_chargeable_units, email_totals}


models:

AnnualBilling
service_id, financial_year_start, free_sms_fragment_limit, updated_at, created_at

FactBilling
local_date, template_id, service_id, notification_type, provider, rate_multiplier, international, rate, billable_units, notifications_sent, created_at, updated_at

FactNotificationStatus
local_date, template_id, service_id, job_id, notification_type, key_type, notification_status, notification_count, created_at, updated_at

**Comment by xlorepdarkhelm** [comment]
Service
id, name, created_at, updated_at, active, message_limit, total_message_limit, restricted, email_from, created_by_id, created_by, prefix_sms, organization_type, contact_link, volume_sms, volume_email, consent_to_research, count_as_live, go_live_user_id, go_live_user, go_live_at, organization_id, organization, notes, purchase_order_number, billing_contact_names, billing_contact_email_address, billing_reference, email_branding

**Comment by xlorepdarkhelm** [comment]
FactProcessingTime
local_date, messages_total, messages_within_10_secs, created_at, updated_at

**Comment by ccostino** [comment]
We're good for now with this and the documentation provided by https://github.com/GSA/notifications-admin/pull/1547, thanks!
