### ISSUE TITLE
Remove "Effective April 16" Login Landing Page

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1546]
Now that we have fully switched over to Login.gov and effectively communicated to users why we're doing it, it's time to remove our interim "announcement" landing page.

**Desired state/to close:**

- [x] Remove Announcement page (pictured below) 
- [x] Replace Landing Page `sign in` button with something similar to: ![Image](https://github.com/GSA/notifications-admin/assets/91496588/90f77a28-2309-4793-b1e3-d66c7a5e7839)
- [x] Redirect users from Landing Page to `https://secure.login.gov/`
- [x] Remove announcement on tangential sign-on pages like: `You need to sign-in again` which currently still have the announcement banner.

--------------------------
![Image](https://github.com/GSA/notifications-admin/assets/91496588/31b63e61-b233-46c8-8d61-fc791ae6ee0e)

**Comment by heyitsmebev** [comment]
Here's how the new button could look with the suggested changes. 
![image](https://github.com/GSA/notifications-admin/assets/53159604/8fc4dd5e-6ff8-4400-b86e-673dbca43e56)

**Comment by heyitsmebev** [comment]
@em-herrick 
Do we want to keep the create login.gov button? 

![Screenshot 2024-06-11 at 12 19 39 PM](https://github.com/GSA/notifications-admin/assets/53159604/0c41be21-8604-428c-9e19-68185ba7bfda)

**Comment by heyitsmebev** [comment]
@ccostino Making a note here from what we discussed in demo, we'll need another ticket to address the technical debt related to refactoring or removing the sign-in page and moving the login logic to the landing page.

**Comment by heyitsmebev** [comment]
> @ccostino Making a note here from what we discussed in demo, we need another ticket to address the technical debt to refactor or removing the sign-in page and integrating the login logic into the landing page. This will ensure that the login is intact and functioning as before, given its complexity.
