### ISSUE TITLE
Bug: Forced Sign Out

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1587]
### Who discovered this?

sherry.dale@dshs.wa.gov

### What happened?

A bug happened! We've heard from a user in WA that she has been experiencing the forced sign-out problem,  (that I believe sometimes happens when we do a deploy). This started on Friday May 31

> I just started sending texts to our clients. It does appear that notify is still forcing me to sign in over and over while trying to send text messages. I thought it was due to the large volume of texts but so far I have only tried to send a total of 4 texts. It is not happening in the same spot. It is happening when I’m pushing the EBT language and preview buttons. It is not forcing me to actually sign in with my password after signing me out but it does start me back over at the dashboard screen.

### Environment

production

### What pages did this appear on?

All pages

### Detail the steps for someone to reproduce

x

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by xlorepdarkhelm** [comment]
I think at this point, we will need something logging the state of the env vars when the system is started. Been reading a lot of stuff from people with this issue, and there's a theme of "the env vars are OK", and the solution doesn't seem to be applicable. But I'm beginning to suspect that yes, this is where we need to be looking.

**Comment by ccostino** [comment]
The recent addition of the logs that show whether the environment variables are set or not are indicating that these are being set, so it appears that we do not have an issue with the app starting up without the information it needs.

**Comment by ccostino** [comment]
Also noting here that this bit us again twice in the last 24 hours with our other deploys!

**Comment by ccostino** [comment]
With this continuing to bite us, we want to get a good solid handle on what's happening and try and fix it for good.  Going to bring this back into the `Up Next` column as it's now being tracked in this epic: https://github.com/GSA/notifications-api/issues/1161

**Comment by ccostino** [comment]
One other quick hypothesis that just came to mind while speaking with someone about this:  could we possibly be dealing with a time drift issue between servers here that are affecting this every now and then?  It'd certainly explain the randomness/inconsistency of when this happens!

**Comment by ccostino** [comment]
It has been several months since we've seen this issue at this point, and I'm comfortable saying we can close it out.  I suspect one of the following (or, more likely, a combination of) has led to the elimination of this bug:

* Finalizing our switch to using Login.gov for authentication
* Making adjustments to the session management in the application
* Adding more worker instances for Celery in production

If we see it crop up again, we'll open a new issue for it!
