### ISSUE TITLE
Change error message when system is down

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#164]
Here is the current message:

![Image](https://user-images.githubusercontent.com/6556888/199266022-be00c9b6-85e1-4657-9343-5d72238a497e.png)

**Comment by tdlowden** [comment]
Since we don't have a system status page yet, it would make sense to remove the second sentence and update the email address in the last sentence.

**Comment by tdlowden** [comment]
This should be addressed in #166

**Comment by rahearn** [comment]
Looks like this was indeed fixed in #166. Current message is:


![Image](https://user-images.githubusercontent.com/285842/212174898-5990ea7e-2d9b-4fab-b207-059b2cc49143.png)
