### ISSUE TITLE
Document core Notify user stories

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1640]
The personas work documented the core roles and needs of people who need to interact with Notify content or team: https://docs.google.com/presentation/d/1vq24dIDbYb0sB1Zi8T3rydV6iU4NClwkdnLfBfwpl9E/edit#slide=id.g2cadf3ff202_0_41

This personas work stopped short of capturing the ways the Notify product meets the core user needs today. This feature-level product description would be useful for
- Onboarding new team members. 
- Agreeing primary use cases for different kinds of testing (e.g. pre-deployment regression testing, post-deployment smoke test, E2E)
- Informing a UX testing strategy 
- Instrumenting and evaluating feature usage (to answer questions like, "where do new users get stuck during evaluation?") 

We currently think the Notify product description will be expressed in two levels: core stories and core journeys. Core stories will be tasks like "send message from template" basic actions which might be done by different personas under different circumstances. Core journeys will be higher-level goals that may involve more than one core story or persona.

Relevant collateral: 
* End-to-end tests https://github.com/GSA/notifications-admin/tree/main/tests/end_to_end

**Comment by sheevdave** [comment]
Core User-Story Doc: https://docs.google.com/document/d/1AYNQM7hZP8vCByJXQhyra2tgqb5TfNVy52dPdfU1W_w/edit

Possible Options for next steps: 
- Deliberately focus on 1 core user and build out the capabilities for it
- Prioritize and rank the core user stories and start developing acceptance criteria for the roles

**Comment by ecayer** [comment]
I think the immediate next step should still be to tie a bow on it! Or more specifically, combine these with personas into some longer-term collateral. Did you hand that off, @sheevdave ?

**Comment by ecayer** [comment]
Other longer-term options for next steps (from issue description),
* integrate into onboarding materials
* use as a framework for QA review
* inform user testing strategy
* begin instrumenting workflows to visualize feature usage

The QA option is strong right now, given the quality focus of this quarter's milestones!

**Comment by ecayer** [comment]
This has now been crystallized into a deck. It will get iterated on, but I think this part of the job is done!  https://docs.google.com/presentation/d/1vq24dIDbYb0sB1Zi8T3rydV6iU4NClwkdnLfBfwpl9E/edit#slide=id.g2f32496f311_0_505
