### ISSUE TITLE
Self-guided: Get new partners into Notify.gov with the right feedback and touchpoints along the way

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1646]
As new Notify Admin, I want to understand how to get started testing out Notify.gov and then understand what I'll need to do to use it to communicate for real with program participants. I want to be able to do this with confidence, so I need to know where to get answers to any additional questions that might come up as I'm doing it. 

As Notify.gov team member, I want to understand what our self-guided onboarding process looks like, what tasks I need to be aware of and what tools and templates are available to me.

Preconditions: MOU is signed, admin is named, services are set up, number is assigned (invite is sent?)

Key stories:
 **Onboarding Experience**
- [x] #1527 
- [x] #1655 
- [x] #1679 

- [ ] User testing
   - [x] Arizona
   - [x] HHS - ONC
   - [x] GSA - 25 Federal Plaza

**Impact Measures + Collection Methods**
- [x] #1695 
    - [x] #1696 

**Process and Procedures**
- [x] #1694 
- [ ]  #1759 
- [ ] Measure the process, durations, team time spent, etc.

**Comment by ecayer** [comment]
I think this is done for now? @em-herrick ?

**Comment by em-herrick** [comment]
yeahhh!
