### ISSUE TITLE
Make adjustments to IGCA doc

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#167]

**Comment by tdlowden** [comment]
made some initial changes based on Micah's feedback. @amyashida  is re-working the cost charts

**Comment by amyashida** [comment]
AH is now driving this through TTS/GSA approvals. The latest update I have: 

It's been reviewed by Laurie and Nina and AH sent to LBS/Ann on 12/5. Looks like we might still be waiting on Micah, but I believe AH is planning to send to John Peters (Micah's boss) this week either way. Then it will go to Robin.
