### ISSUE TITLE
Update tables to match wireframes

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1671]
Epic Goal:
When this Epic is implemented, tables will be visually consistent with wire frames

### Features and User Stories

**Recent Activity** 
- [x]  #1674
- [x]  #1669  
- [ ]  #1675

**All Activity** 
- [x] #1677 
- [x] #1717 
- [x] Add pagination

**Most Used Templates**
- [x] #1487 

**Across all Tables**
- [x] #1488  
- [ ] #1871 
- [x] Implement a new "Job ID" strategy to help users better identify jobs and remove our reliance on "uploaded file" -->this will need to be a change across both Recent Activity table and All Activity table
- [x] https://github.com/GSA/notifications-admin/issues/1490

**Comment by ecayer** [comment]
To do: close out epic, put filter/search in backlog and do some research on high-volume use cases.
