### ISSUE TITLE
User Story: Match 'Recent Batches' table to wireframes

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1674]
### Detailed condition or criteria that must be met for the user story to be considered complete.

Update the "Recent Batches" Table, displayed on the Dashboard to match the [wireframes](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-5637&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580)

![Image](https://github.com/GSA/notifications-admin/assets/91496588/63d403b0-8fba-4dcc-8d31-ffdec7b9cfa9)

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [x] Rename Table to: "Recent Activity"
- [x] Replace existing columns with: `Uploaded File,` `Job Status`,` Sender`, `# of recipients`
- [x] Remove column: "Reports"
- [x] Adjust time/date format to display as "sent on" in the "Status" column to match wireframe
- [x] Within the "Uploaded File" column: This link should lead users to viewing the single job/batch. Add icon or instructions to "view batch" (can/should match what is currently on production in this column)
- [x] Move table to sit underneath 7-day data viz and push "Messages sent by template" to bottom of Dashboard, just above the Message Allowance disclaimer.
- [x] Replace UI display to match table style of wireframe

### List any dependencies that need to be resolved before starting or completing this user story.

This should be a relatively small user story that gets us closer to wireframes and prepares us to make the following larger UX changes for this table:

- #1669 
- #1675 

### Any additional information or context that might be useful for the team.

This ticket purposely excludes dealing with/adding in "scheduled messages" to this Activity table. We're hoping to adjust the "status" column to make room to shift towards this, so expect additional work adjusting how date/time is displayed so that it aligns closer to what is on the wireframe.

**Comment by em-herrick** [comment]
@heyitsmebev one thing we should talk about at UX sync next week is agreeing on what UI table style the group wants to adhere to. Should we keep the line, no border style of tables that exists in the product currently, or do we want to move towards the table boarder style in the wireframes?

LMK if you'll need a decision on this before next wednesday.

**Comment by heyitsmebev** [comment]
@em-herrick We don't need to make a decision before our meeting on Wednesday. That's something that can easily be changed. I'm going to focus more on making sure we have all the data we need. 

Question: For the 'status' column, does "sent on" mean the time a notification message was **delivered/failed** or the time it was **sent** aka created at?

**Comment by em-herrick** [comment]
sounds good! 
The "sent on" column is for an entire job with multiple rows of data. Ideally, this would display when every row of data has been sent to AWS, but not sure we can be _that_ accurate. So I'd be good if we displayed the time when the job was created/the first message was sent (for example, if it was scheduled i'd want it to display when the messages were actually sent). 

But would be open to other ideas based on what we have available!

**Comment by heyitsmebev** [comment]
@em-herrick 

Based on what we have available, it looks like we can gather the time for when a **job starts** or when the **job is complete**. Do you have a preference for which one we should display? There's another datetime for when a **job is created** -- the time the service sent the request. However, sounds like you're going for more when job starts or finishes.

**Comment by em-herrick** [comment]
excellent. Let's display when a job is **complete** for any "status" column.

**Comment by em-herrick** [comment]
@alexjanousekGSA we discussed last week at UX sync changing our approach to our Job sorting away from using "File Name" towards a "Job ID". We currently don't have a Job ID function available so this is going to be something that will need to be created. 

@jonathanbobel updated our [Figma wireframes to reflect our new desired state](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-5482&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580) here. As @heyitsmebev is going to be working on another version of this table, you two should link up to discuss how we want to approach switching over to the Job ID approach.
