### ISSUE TITLE
User Story: View table of all jobs sent with my service

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1677]
### Detailed condition or criteria that must be met for the user story to be considered complete.

Users should have a historic record of aggregate level data of jobs completed. Because we delete phone number record data after 7-days, this table provides a history of system usage beyond this timeframe.

If indvidual jobs are less than 7-days old, users can access invidual job reports from this table. If the jobs are older than 7 days, summaries of the job information should still be viewable.

_Eventually_ Users should be able to search these records and sort table columns as needed. Pagination should also be included.

![Image](https://github.com/GSA/notifications-admin/assets/91496588/3bd71540-31e8-42d7-aed1-b9e9fb566188)

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [x] Review [Jobs page in wireframe](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?node-id=3047-7482&t=WNfyj0s1XDaaS0cc-0&scaling=min-zoom&content-scaling=fixed&page-id=3047%3A4396&starting-point-node-id=3047%3A5482) and match UI styles.
     - _Note: we're replacing the word "Job" with "Activity" as we implement this page_
- [x] Create a new page (that will be linked in our side navigation) for a new jobs page, to be titled "Activity": `notify.gov/activity` 
- [ ] Build this page as a prototype. We will be testing this page with users before deploying.

- [x] Build a table labeled `All Activity` that displays all jobs sent within a specific Service instance.
     - [x] Columns should include: `Job Number`, `Template`, `Time Sent`, `Sender,` `Report`, `# of Recipients`, `Delivery Rate`,  and `Message Parts Used`
     - [x] In "Reports" column: Add a download icon/option for jobs less than 7-days old. Display a `N/A` in this column if job is older than 7-days.
     - [ ] Explore/talk to Bev if existing endpoint exists for "Message parts used per job" _see note below._

- [ ] Review Search and Pagination functions available on other pages in the application.
     - [ ] Test out search function, assess what it would take to get this working
     - [x] Ensure pagination is cleaned up and working (also test and gather level of effort to fix, if broken)

### List any dependencies that need to be resolved before starting or completing this user story.

Please explore level of effort needed for both of these things, and we can prioritize whats most needed first:

- [ ] We may need a new endpoint for **Message Parts** for a whole Job—this would be an aggregate number of: # of phone numbers in the job [times] # of message parts per phone number. I don't believe this exists.
- [ ] **Delivery rate** is not shown in the wireframes. This has emerged another metric worth showing in this table. Delivery rate is % of total job delivered. I am not sure if we have an endpoint for this.
- [ ] **Search and Pagination**—these things are displayed but not currently functional. We're looking for an assessment on what is needed to make them work and how long it make take.

### Any additional information or context that might be useful for the team.

Please ignore the "View Scheduled Jobs" button for now, this will be added later after we have an MVP of this page.

**Comment by em-herrick** [comment]
Em to add:

- do we charge for message parts delivered? or sent?
- Add delivery rate to column

**Comment by heyitsmebev** [comment]
@em-herrick 

Update on activity: 
![image](https://github.com/user-attachments/assets/070d1612-044e-475b-99c3-27aec6b0de31)

Still in progress:
- [ ] Sort isn't correctly "sorting" for JobID
- [ ] Add in pagination 
- [ ] Add testing
- [ ] Add in "loading" ui

**Comment by heyitsmebev** [comment]
New Update on the activity page: I got the pagination to work just fine. I will return to figuring out why JobID isn't sorting as expected 

https://github.com/user-attachments/assets/eba5a1eb-327f-4bf6-8852-b17f3e9c5c40

**Comment by em-herrick** [comment]
@heyitsmebev its looking GREATTTT! A few questions/comments:

- What are the mechanics behind the sort feature? Is it just alphabetical and reverse alphabetical order?
- Looking at Figma, Let's replace the `status` column name with `time sent`
- For the reports column, let's use the singular so swap to: `Report`
- With Jonathan's updated ["Job Status"](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-7769&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580) page to include a lot of this same table data I think we can simplify the columns. Let's go from 8 to 5 and only display:
    - `Job ID`, `Template`, `Time Sent`, `Sender`, and `Report`
- I'd like to avoid a horizontal scroll if possible, so in addition to the above change I am wondering about setting a max column width and some rules for stacking text similar to the prototype? I think our longest columns will always be Template and Time Sent.

**Comment by heyitsmebev** [comment]
@em-herrick 
- Mechanics behind sort feature: A sorted column changes the row ordering based on alphabetical or numeric cell values.
- Here's a screenshot of the adjusted column widths and headers based on the Figma updates. 

![localhost_6012_activity_services_78409625-0c0a-485e-b82c-b19c8f4b1bdb_page=2](https://github.com/user-attachments/assets/b22c040d-fb73-47b9-bae3-7a225a549bee)


> @heyitsmebev its looking GREATTTT! A few questions/comments:
> 
> * What are the mechanics behind the sort feature? Is it just alphabetical and reverse alphabetical order?
> * Looking at Figma, Let's replace the `status` column name with `time sent`
> * For the reports column, let's use the singular so swap to: `Report`
> * With Jonathan's updated ["Job Status"](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=3047%3A4396&type=design&node-id=3047-7769&viewport=1545%2C-388%2C0.39&t=hcILYUjGtf62EHzn-1&scaling=min-zoom&starting-point-node-id=3047%3A4580) page to include a lot of this same table data I think we can simplify the columns. Let's go from 8 to 5 and only display:
>   
>   * `Job ID`, `Template`, `Time Sent`, `Sender`, and `Report`
> * I'd like to avoid a horizontal scroll if possible, so in addition to the above change I am wondering about setting a max column width and some rules for stacking text similar to the prototype? I think our longest columns will always be Template and Time Sent.

**Comment by heyitsmebev** [comment]
This ticket is ready for review: https://github.com/GSA/notifications-admin/pull/1743

When @jonathanbobel has a color ready for the **sort** blue column color, we can add that in
