### ISSUE TITLE
add content: as a user, i'd like understand what each permission grants before i invite team members

### ISSUE THREAD

**Issue by dmvancura** [GSA/notifications-admin#1687]
**what needs to be done?**

- [x] add content introducing and explaining permissions, to help system admins understand each one's purpose
- [x] Remove a piece of content in the Permissions section on the `Features` page

**where does it need to be done?**

- [x] 'Invite a team member' sitepage ([behind the login](https://beta.notify.gov/services/0444a1f6-29ac-45fd-84ea-491a2c4fa802/users/invite) or notify.gov/services/settings/users/invite
- [x] [Features page](https://beta.notify.gov/features) --> H1: Permissions

**what it should look like**
just below page title/H1 a hyperlink says 'Learn more about user permissions.' that text anchors to the H2 'Set up user permissions'
then the new content (outlined in the copy doc), goes below the page's current button – 'Send invitation email.'
note: the table content in the copy doc is ideally placed in an accordion component on the sitepage. preferred is the Bordered accordion component https://designsystem.digital.gov/components/accordion/

![Image](https://github.com/GSA/notifications-admin/assets/171041398/394e048c-6f2d-4e92-a45a-e96c7b465c87)

copy doc is [set up user permissions](https://docs.google.com/document/d/1MMiXFd_BIX18NyQQdJEIAc8Detm-5wxFoh1R02KaG7o/edit?usp=sharing)

-----

Remove following content from features page (image below): `invite team members who do not have a government email address`

![Image](https://github.com/user-attachments/assets/1b02d24f-9e25-427d-a71c-6ba5b64093be)

**Comment by heyitsmebev** [comment]
@dmvancura 
FYI: The bordered style has the first content open within the accordion.

https://github.com/user-attachments/assets/b142efd3-3109-4421-9513-086417732c6e

![Image](https://github.com/user-attachments/assets/8d37d1dc-9bbe-4202-83ad-ae4c0d1b7202)


![Image](https://github.com/user-attachments/assets/54d04522-e361-4913-93fb-4e080ab1579f)

**Comment by dmvancura** [comment]
yay! awesome
