### ISSUE TITLE
Content Add: New content to Features page about Organizing Content

### ISSUE THREAD

**Issue by dmvancura** [GSA/notifications-admin#1708]
### Who discovered this?

Em and Deana

### What happened?

**what needs to be done?**
add content explaining how to organize templates and folders, to help campaign managers understand how to keep their folders tidy

### Environment

staging

### What pages did this appear on?

**where does it need to be done?**
[Features](https://beta.notify.gov/features) sitepage, behind the login. Specifically, after ‘Reusable message templates’ paragraph and before ‘Personalized content' H2 line.
![Image](https://github.com/GSA/notifications-admin/assets/171041398/129e1c84-10cb-4c68-8330-7da92cc439d5)

### Detail the steps for someone to reproduce

**what should it say?**
H2: Organizing your content
Paragraph: You can organize your content by grouping templates, and putting them into folders.
Paragraph: Set up folders within the Send message section of Notify, where you find templates. You can choose to create a Folder before or after a template is made. If you want to change a user’s ability to view or edit folders, you may control this through their individual team member permissions.

**Comment by heyitsmebev** [comment]
@dmvancura 

Updated! Take a look at the changes in this screenshot here. 
![image](https://github.com/user-attachments/assets/31e2dc70-3308-4b65-9296-1314e33e461e)

**Comment by dmvancura** [comment]
yay yay! thank you
