### ISSUE TITLE
Investigate an apparent timing issue with invites

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1730]
We recently [merged a fix for invites](https://github.com/GSA/notifications-admin/pull/1728/) that was related to the session management work we recently did, and we'd like to understand more about what's happening with the suspected timing issue we're experiencing.

## Implementation Sketch and Acceptance Criteria

* [ ] Look at the fix that was done in [this PR](https://github.com/GSA/notifications-admin/pull/1728/) and try to reproduce the issue
* [ ] Dig more into what might be happening and trace the invite processing flow to see if there's anything else amiss
* [ ] Make any fixes or adjustments necessary
* [ ] Add and/or update tests as necessary

## Security Considerations

* The behavior with this is due to other recent fixes we made to address a security concern.
* We'd like to make sure our app is functioning properly for users while also remaining secure.

**Comment by ecayer** [comment]
Is this still valid after other invite fixes?

**Comment by ccostino** [comment]
I don't think so - the only one that remains open now to my knowledge is the expiration window being wrong, and the cause of that is now known.  Closing this one!
