### ISSUE TITLE
John hands over infrastructure work

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1794]
Spread the knowledge widely and ensure key ongoing tasks are in someone's hands.

John IDs tasks, team makes sure they can do the tasks John IDs.

Also a team presentation, [which can be found here](https://drive.google.com/file/d/13SR3M8IowYBa4Wp_YEcuAURZ74EcCYoc/view?usp=drive_link).

John's end date is **AUGUST 2**

**Comment by ccostino** [comment]
I added a link to the copy of the recording in our team drive folder in the issue description above.  Thanks again, @jskinne3!

**Comment by jskinne3** [comment]
In addition to the video and the working sessions I've had with coworkers to transfer knowledge, I've written up the two outstanding / ongoing tasks I know of:
* https://github.com/GSA/notifications-api/issues/1235
* https://github.com/GSA/notifications-api/issues/1236

**Comment by ecayer** [comment]
Thanks again for your service @jskinne3!
