### ISSUE TITLE
Bug: Recent Batches table not displaying most recent jobs

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1795]
### Who discovered this?

Em

### What happened?

A bug happened! Recent batches  table is not updating with accurate view of the most recent jobs sent by service. Washington sent messages today 8/1, but the table is displaying messages only from June

![Image](https://github.com/user-attachments/assets/c9f6fd79-fe8a-4cda-bd43-32676a6d1834)

### Environment

Production

### What pages did this appear on?

Dashboard

### Detail the steps for someone to reproduce

TK

**Comment by heyitsmebev** [comment]
https://github.com/user-attachments/assets/f6d03f07-4c9b-4a8f-b2d5-98ff819893da

I'm not noticing any obvious patterns why this bug could be happening.

Here are some of the scenarios I'm seeing:
- When I'm on a specific service, the jobs are populating properly.
- When I switch services, the jobs are not populating as expected.

I will continue to look into this bug
