### ISSUE TITLE
Activity page updates

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1817]
Activity Page

- [x]  Add options for 1,5,7 day reports downloadable reports at bottom of page 
- [x]  Stack time sent column for more real estate
- [x] -Add  two additional columns 
     - [x] Delivered - number of delivered messages by job
     - [x] Failed - number of failed messages by job

**Comment by heyitsmebev** [comment]
@em-herrick 

Currently, the job data returns basic statistics for each job, grouping them by count and status. While we could create separate columns for "Delivered" and "Failed," I don't think it would be the best approach, as some jobs might only have delivered counts. Instead, we could consider having a single "Status" column that displays both the count and the corresponding status (e.g., "5 Delivered", "3 Failed"). This would not only save space but also present the information more concisely. I do think the two column is helpful if the user would like a quick scan and if that's the intent, then this approach works. 

![Image](https://github.com/user-attachments/assets/aaa108e2-321b-4dc5-b291-e203c1ebed04)

**Comment by heyitsmebev** [comment]
@em-herrick 
this is also how it looks when  a job is in a "sending" state


![Image](https://github.com/user-attachments/assets/e93b7fd2-79b1-4a73-9a43-a8f2ab8ea453)

**Comment by em-herrick** [comment]
@heyitsmebev thanks for your work on this. I agree with your assessment, not sure if two columns is the most beautiful solution, and yes the intention is a quick scan of job success so I think two columns is better than combining into one. 

Let's ship it in this two column format and see how it plays out for our users, many of which are sending hundreds, if not thousands of messages at one time and might have at least 1 failed. I am also still wondering if delivery rate could help us in the future here...but for another day.

I like leaving the columns blank when in sending state. Could we display a 0 if there are no failed messages?

**Comment by heyitsmebev** [comment]
@em-herrick 

I've added in the 0 if no failed messages

![Image](https://github.com/user-attachments/assets/84df5be4-69de-478d-86e3-20a0dac502f2)
