### ISSUE TITLE
QA for prod push: Aug 14 / Admin #[insert PR number], API #[insert PR number], Utils #[insert PR number

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1843]
API PR:  TBD
Admin PR:  TBD

QA testers should use the QA Testing Service on Staging to complete the following actions. Any errors or seen issues should be added to comments of this ticket to resolve.

### Log In

- [x] notify-staging.app.cloud.gov resolves
- [x] Clicking sign in takes you to login page
- [x] 2FA code is sent promptly
- [x] 2FA code input screen appears as expected
- [x] After code is entered, you are brought to the “choose service” screen
- [x] Choosing a service brings you to the dashboard for that service

### Create a template and send

- [x] Clicking “Send messages” brings you to templates page
- [x] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [x] Uploading a csv is quick and automatically directs you to the preview/send page
- [x] Formatting looks clean and in place
- [x] Message dashboard populates and shows “pending” until call is made to AWS for delivery receipt

### Send a message from copied template

- [x] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [x] Clicking “copy an existing template” allows you to choose from pre-existing template
- [x] After editing, the new template saves and you prepare to send

### Send a message from existing template

- [x] Clicking on existing template brings you to preview screen with `prepare to send` button
- [x] All else above persists as true (formatting, send, dashboard, etc)

### Download the csv delivery report

- [x] Clicking on the csv download directly after a message send downloads a report that contains the data we expect
- [x] The batch report appears on the main dashboard batch table with accurate information
- [x] Clicking on the csv download link from the main dashboard downloads a report that contains the data we expect

### Invite a team member
You can use an alias email address to do this. Go to My Google Account > Personal Info > Contact Info to find your GSA email aliases (ie: your.name@cio.gov OR your.name@connect.gov ... etc.)

- [x] Clicking on “Team” in settings brings you to team member screen
- [x] Clicking “Invite a team member” brings you to email and permissions screen
- [x] Clicking invite team member sends an invite and shows confirmation
- [x] Invite email provides live link that works to register new team member

### Delete a team member

- [x] From team member screen, clicking “Change Details” on a specific profile brings you to that person’s profile
- [x] Clicking on “Remove this team member” prompts a confirmation
- [x] Clicking the confirmation removes the team member

### Sign Out

- [x] Hitting “Sign Out” takes you back to the homepage and logs you out

----

### Specific QA Focuses for this Release

 **7-Day Chart: Data Viz**
- [x] Send a batch of messages (more than one-offs), force some fails - You can use this [QA phone number](https://docs.google.com/spreadsheets/d/1jRVEtMcKrr6aTVFZu07zg6SUoeMOTCWMxTdrH5Ebi-w/edit?gid=193751236#gid=193751236) list as your upload file.
- [x]  Check tables against messages that were sent

**View New Activity Page**

- [x]  make sure pagination works
- [x]  Download a delivery report CSV file
- [x]  New jobs should list at the top of table
- [x]  Date and time should be accurate

**Comment by em-herrick** [comment]
Looks like the GSA logo image is not loading.

![Image](https://github.com/user-attachments/assets/cf3b1111-8b0f-4eb9-a63e-6321230946bc)

**Comment by em-herrick** [comment]
On the Dashboard: `All Activity` table should be relabeled as `Recent Activity`

**Comment by em-herrick** [comment]
On Activity page, for time based reports, we need to add in the 3-day report option (right now its 1,5,7 day only).

**Comment by sheevdave** [comment]
How long are messages supposed to take to send? 10 min and still showing pending delivery status 
![Image](https://github.com/user-attachments/assets/5b8ac7b4-692c-4db0-963f-b5407085ba62)

**Comment by dmvancura** [comment]
maybe refresh the page @sheevdave , mine started to show then

**Comment by dmvancura** [comment]
QA done for me, no bugs

**Comment by ecayer** [comment]
I'm also getting a long-pending one... 17 minutes and counting. This was my first send from this account, and subsequent ones have succeeded. 

![Image](https://github.com/user-attachments/assets/d141e5dc-7ff2-4f98-b675-770dd816512f)

**Comment by ecayer** [comment]
Also, any chance we can add "EST" to the times? I'm assuming that's too widespread to add at this point, but... :-)

**Comment by heyitsmebev** [comment]
> * [x]  On Activity page, for time based reports, we need to add in the 3-day report option (right now its 1,5,7 day only).
I'll have a PR go out for this @em-herrick 
![Image](https://github.com/user-attachments/assets/43b38ff0-e27b-42a4-b6ac-230b848383dd)

**Comment by em-herrick** [comment]
> Also, any chance we can add "EST" to the times? I'm assuming that's too widespread to add at this point, but... :-)

We made the decision NOT to include time zone codes a while back because of the visual clutter they can create. AND because users can technically set their own timezone in the app so everything should appear in their local time. 

...but this is not very visible to people right now...I even wonder if @ecayer you have done so for yourself. We might want to revisit how we convey timezone options.

**Comment by heyitsmebev** [comment]
We have a couple of tickets related to the messaging on the status page. When we revisit the timezone, this could also be something to look into, especially if we are focusing on the message bar.
https://github.com/GSA/notifications-admin/issues/1706
https://github.com/orgs/GSA/projects/20/views/1?filterQuery=status%3A&pane=issue&itemId=64427363

**Comment by sheevdave** [comment]
QA is done for me

**Comment by heyitsmebev** [comment]
There should be "No batched job messages found...etc" on an empty state

![Image](https://github.com/user-attachments/assets/d9592af7-d865-46ea-ba4b-ae9e4f6255e1)

**Comment by ecayer** [comment]
As mentioned on Slack, the favicon seems to have vanished!

Otherwise, no showstoppers from my perspective, but a few issues that were probably already present in prior releases:(and if you disagree about the showstoppiness, obviously please say! cc @em-herrick)

If the user is created without dashboard access, they can click on "Sent Messages" and get an unhelpful "Sorry, we can't deliver what you asked for right now" message.

If I look at User profile -> team members without having chosen a service, I get "Page not found" 

If I delete a user when the user is logged in, they can still do all the things (create a new service, templates, send, etc) in their current session.

There is still at least one vestigial Password request (if you try to change your phone number). 

I'm happy to create actual reproduce steps if any of these aren't known! 

Otherwise, I'm done with my testing. Nice work. 👍

**Comment by ccostino** [comment]
Whoops, PR automation flow closed this issue a bit ahead of time! 🙂

**Comment by em-herrick** [comment]
> There should be "No batched job messages found...etc" on an empty state
> 

Yeah good call. I'd like any display text to read: `No messages sent in the last 7-days`. Do we think we just hide the graph? keep it visible? 
I don't think it is a show stopper to keep the 0-message graph as is for this release, but defer to @jonathanbobel here.

Additionally, now that we've  hit the upper double digits of our graph, looks like some of the axis numbers are being clipped:

<img width="253" alt="Screenshot 2024-08-15 at 9 39 40 AM" src="https://github.com/user-attachments/assets/03b39474-3806-426a-a14a-a32da08004f9">

**Comment by em-herrick** [comment]
> I'm happy to create actual reproduce steps if any of these aren't known!

Yes @ecayer I don't think any of these are known/documented issues. Do you want to write up a tickets for them for us to tackle soon?
