### ISSUE TITLE
Data visualization bar chart isn't show clearly

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1862]
The data visualization doesn't display the bar chart clearly when the delivery or fail count is low. 

![Image](https://github.com/user-attachments/assets/4126f9e0-9b91-470a-afb9-e7f11c52563e)

**Comment by em-herrick** [comment]
@heyitsmebev can we also address the allowance bar as part of this ticket. Similar issue to the one above. If a service has sent zero text messages, can we have the allowance bar look like its fully empty? Right now we get a default blue bar, even at zero.



![Image](https://github.com/user-attachments/assets/a10d4381-f2e9-4498-b129-f1c86d9255ae)

**Comment by em-herrick** [comment]
One more quick change while you're here. Can we replace the heading `Activity Snapshot` with `Recent Activity`

**Comment by heyitsmebev** [comment]
@em-herrick @jonathanbobel 

Does the scale look odd if we exaggerate the smaller bars compared to the taller ones? 

D3 has a method called d3.scaleSqrt that can help maintain proportions when there are large differences between values. 

What we are currently doing is using a linear scale, this can make smaller values appear almost invisible when compared to much larger values.

Another option is to add a minimum height to the small bars without changing the scales. This might improve the visibility of the small bars, but it may vary because it depends on the overall distribution of values

![Image](https://github.com/user-attachments/assets/61794026-c65a-4021-9fe2-6e81c5eedd96)

**Comment by jonathanbobel** [comment]
@heyitsmebev that's not a bad solution above, worth trying out
