### ISSUE TITLE
Self-Guided UX research & enhancements

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1865]
### Epic Goal
When we implement this epic, new users will:

1. Understand what core Notify.gov features exist in a way that helps them prepare their texting campaign
2. Feel confident enough to send a (test OR live) first text
3. Know where to look to get their most pressing questions answered

### Epic Why

To surface unknown gaps in the UX experience that are preventing partners from feeling comfortable in sending their first live text message without any hand holding support

### To complete
- [x] #1889
- [x] #1891
- [x] Surface/prioritize additional enhancements

**Comment by em-herrick** [comment]
--> Onboarding video / tour, document key steps 
--> automate and make available and persistent
--> user test some sort of prototype
--> document known steps for getting start

**Comment by em-herrick** [comment]
Need to talk to Studio team about research goals for fall quarter to pace out who we're talking to and why.
This epic can focus on getting our machine up and running

**Comment by ecayer** [comment]
3 interviews set up for next week! Hooray!

**Comment by ecayer** [comment]
Closing in favor of the issues issue! [#2035]
