### ISSUE TITLE
Check and make updates to UI to meet accessibility standards

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#1920]
For a more comprehensive manual audit: (Notify - Accessibility Audit - Spreadsheet)
https://docs.google.com/spreadsheets/d/1CxCxae-RqzHAEB5IOgD-G2nScCJIxP-Pkkvg4HF85s8/edit?usp=sharing 

Quick HTML to make sure these are implemented: 
- [ ] Add proper id to html tags 
- [ ] Add caption to tables such as Jobs and Recent Batch table
- [ ] Descriptive text on links and not "click here"
- [ ] Scale up in text, does any text break? 200% zoom test

More research around 
- [ ] Do we have more than one way to locate a page within a site?
- [ ] Can a user quickly skip to the main relevant content on a page? (skip link)

**Comment by sheevdave** [comment]
Perhaps starting with "Level A" standards would also be a good starting point.

**Comment by heyitsmebev** [comment]
this now seems like a duplicate to the a11y epic, going to close this ticket
