### ISSUE TITLE
User Story: Implement backstopJS

### ISSUE THREAD

**Issue by alexjanousekGSA** [GSA/notifications-admin#1927]
### Detailed condition or criteria that must be met for the user story to be considered complete.

BackstopJS is implemented in gulp that can be run as an individual task that tests basic functionality of most pages.

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- Add backstopJS to gulp
- Reuse authentication logic to be able to login to the app
- Write test cases for multiple pages

### Any additional information or context that might be useful for the team.

This is satisfying [ADR 9](https://github.com/GSA/notifications-api/blob/main/docs/adrs/0009-adr-implement-backstopjs-to-improve-qa.md)

**Comment by ccostino** [comment]
@alexjanousekGSA and @ecayer - let's convert this issue into the epic for the BackstopJS implementation!  Then we can turn the list of specific tasks above into the user stories to track the work itself. 🙂 

Does this sound good to both of you?

**Comment by heyitsmebev** [comment]
@alexjanousekGSA 

I just want to make a note here that I pulled in your branch and when I run the command gulp backstopTest, it seems like it's working-kind-of. I get these errors and when I go to change the threshold, I'm not seeing any changes to the sensitivity 
![Image](https://github.com/user-attachments/assets/6ea0f563-6231-476f-8545-d60345c22252)
![Image](https://github.com/user-attachments/assets/3ec7f7b1-e842-4dbe-a6ec-10474fbddfdc)
![Image](https://github.com/user-attachments/assets/ea0b1e5d-592d-4491-8ccc-65b20ba14048)
