### ISSUE TITLE
Adjust financial year settings

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#193]
The current financial year is set to UK:

![Image](https://user-images.githubusercontent.com/6556888/200006948-0e39868e-6113-4e80-93e9-45f16bc258fd.png)

We should also remove the previous financial years from before US Notify was created:

![Image](https://user-images.githubusercontent.com/6556888/200007075-de3f835f-2c58-4632-b9c2-e282f7b7cf5f.png)

These exist on `Usage` page

**Comment by rahearn** [comment]
Some (maybe all) admin side changes were made for this already, but the API still thinks the fiscal year goes april -> march

**Comment by tdlowden** [comment]
Ok, I will close this card and create a new one in `api` repo to address
