### ISSUE TITLE
Bug: Navigating directly to features page redirects to services

### ISSUE THREAD

**Issue by alexjanousekGSA** [GSA/notifications-admin#1942]
### What happened?

While setting up backstopJS tests, I noticed that actions regarding routing were not being performed as expected. When I navigate to one page, I keep getting directed to the services page. 

### Environment

staging

### What pages did this appear on?

This was found locally and it appears when trying to navigate to a route besides services. http://localhost:6012/features for example. 

### Detail the steps for someone to reproduce

- Run admin and api app locally. 

- Open incognito browser. 

- Navigate to "http://localhost:6012/features"

- It should instantly redirect you to something like "http://localhost:6012/services/a6ce0793-baa2-40e9-9a0f-34c2fa4b622a". If it doesn't, maybe a service needs to be created first. 

- If you navigate back to "http://localhost:6012/features" then the page should load. 

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by alexjanousekGSA** [comment]
Found where the problem is:

in the index.py on line 93ish under the features route, there is a annotation for "@user_is_logged_in", if you remove that then it works. So without the user being logged in, it redirects to services for some reason.

**Comment by heyitsmebev** [comment]
@alexjanousekGSA Do we need not need "@user_is_logged_in" as part of permissions?

**Comment by alexjanousekGSA** [comment]
Yes, we need it. I should have clarified that that is how I found the bug, the solution is not to remove the annotation!
