### ISSUE TITLE
User test new static content experience with at least 4 users

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1989]
@dmvancura to define research plan for user testing guidance section with at least 4 users.

**Comment by dmvancura** [comment]
hi @heyitsmebev this is the one, i'm wondering how to get to on the notify site. i believe there is a feature flag involved. yes? either way, i'd like to make it east for the tester to log in a view the content. thanks!

**Comment by dmvancura** [comment]
tested with one external user on 12/2

**Comment by dmvancura** [comment]
testing to conclude at close of business on 12/12
