### ISSUE TITLE
Onboard content support from The Clearing

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#200]
So we're ready to take advantage of their help!

To do:

- [x] prep for kickoff
- [x] Get TC team access to our Drive (move procurement info out first)
  - [x] Pull together links to files/folders that we’d want them to look at first
- [x] Add TC team to the right Slack channels
- [x] Add TC team to the right Github org
- [ ] Decide if TC team needs Airtable access, & if so, get it
- [ ] Add top tasks to Github project board/flesh out scope for each?
- [x] Schedule meet & greet with rest of team for week of 2/27 (maybe @ Monday standup?)

**Comment by alexpandel** [comment]
for context on what they're expecting to be tackling, what we originally asked for is [here](https://docs.google.com/document/d/1LvFjH6Bz94bqGLKLauaO3Yu4DYLuNaK_XqfkDsYzQDo/edit), and their proposal in response is [here](https://docs.google.com/document/d/1nw69fEZzawf5ffABs_69jeos_oUcXtr9/edit).

**Comment by tdlowden** [comment]
PoP starts maybe 2/1.

**Comment by em-herrick** [comment]
Notify Content strategy thoughts are in issue #217 

Could the clearing staff support here?

**Comment by DanRaudonisTC** [comment]
Confirming I'm now a part of the GH org. and have the permissions necessary to comment and add items on the Project. We'll let you know once Aleida has access, too.

**Comment by alexpandel** [comment]
closing this one for now since we're rolling! we can start tracking individual tasks in individual cards moving forward
