### ISSUE TITLE
User Story: Add New Link to Best Practices page

### ISSUE THREAD

**Issue by alexjanousekGSA** [GSA/notifications-admin#2069]
As a user, I want to see the new best practices page. 

I want a link that allows me to navigate there without having to link directly. 

So that users know the pages exist. 

### Detailed condition or criteria that must be met for the user story to be considered complete.

- Link would look like notify.gov/guides/best-practices
- Link would be between Using Notify and Features (If that takes more time, add it after User Profile

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- Add new link to best practices page

**Comment by dmvancura** [comment]
hi @alexjanousekGSA i see this is done, but hooow do i see it? because right now i'm seeing page not found messages![Image](https://github.com/user-attachments/assets/793fc20c-e9df-4ce5-a395-8be0417c4edb)
p.s. i have Bev tagged on another ticket and carlo is looking into it via slack
