### ISSUE TITLE
Add an 'About the Studio' page to Notify

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#2072]
The Public Benefits Studio leadership and Research and Development teams would benefit from a page nested in the Notify.gov footer to hold a broader set of content about the other projects/activities the Studio is working on beyond Notify.

To complete:

- [ ] Build template for this page: notify.gov/studio
- [ ] Link in footer: `About the Pubic Benefits Studio`
- [ ] Add and style written content: https://docs.google.com/document/d/1lP8I0Jxu0B26cmTGBQcoHCbfSvKKHQBE6gzTL9HUheE/edit?tab=t.0#heading=h.4hjk4us33ypg

**Comment by em-herrick** [comment]
As of 11/5 we're waiting final approval from TTS outreach on the content. Can get started building the page when there is free time, but will need final approval before going live.

**Comment by dmvancura** [comment]
this content is approved up to Liz Camerlin as of 11/12

**Comment by dmvancura** [comment]
requesting mockup - About Public Benefits Studio footer link leading to the sitepage
