### ISSUE TITLE
Document feature flag creation process

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#2077]
Following https://github.com/GSA/notifications-admin/pull/1949, we should document our process over in https://github.com/GSA/notifications-api/blob/main/docs/all.md while it's fresh.

It may fit best in/near the "Deploying" section.

**Comment by alexjanousekGSA** [comment]
So we have this documentation here https://github.com/GSA/notifications-admin/blob/main/docs/feature-flagging.md What was your vision for updating the "all" readme?

**Comment by ccostino** [comment]
The documentation updates have been completed!
