### ISSUE TITLE
Update README.md for creating the first user

### ISSUE THREAD

**Issue by xlorepdarkhelm** [GSA/notifications-admin#2086]
The README.md documentation needs to be updated to reflect how the system currently works, when creating the first user in a local environment. The following lines:

---

## Creating a 'First User' in the database

After you have completed all setup steps, you will be unable to log in, because there
will not be a user in the database to link to the login.gov account you are using. So
you will need to create that user in your database using the 'create-test-user' command.

Open two terminals pointing to the api project and then run these commands in the
respective terminals.

(Server 1)
env ALLOW_EXPIRED_API_TOKEN=1 make run-flask

(Server 2)
poetry run flask command create-admin-jwt | tail -n 1 | pbcopy
poetry run flask command create-test-user --admin=True;

---

This is overly complicated and doesn't even work any more, since the switch to using login.gov. The documentation should be changed to:

---

## Creating a 'First User' in the database

After you have completed all setup steps, you will be unable to log in, because there
will not be a user in the database to link to the login.gov account you are using. So
you will need to create that user in your database using the 'create-test-user' command.

Open a terminal pointing to the api project and then run this command.

```poetry run flask command create-test-user --admin=True;```

---

Since the integration into login.gov, the previous additional steps has become unnecessary, and even more, it is interfering with the ability to get prompts for the user's name, email, password, etc. and silently fails. By making this change, the first user can be created easily, and everything works as expected.

**Comment by ccostino** [comment]
This is now merged!
