### ISSUE TITLE
Join Notify

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#2104]
Definition of Done

-  Should be able to easily navigate to Join Notify content
-  Should meet a11y standards

[how it currently looks.pdf](https://github.com/user-attachments/files/17851930/screencapture-localhost-6012-about-join-notify-2024-11-21-12_57_00.pdf)

Figma:
https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=2339%3A3817&node-id=5392-875&node-type=frame&viewport=2870%2C-701%2C0.48&t=nfkxOXnOCIFQB1yK-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5392%3A875

Content:
https://docs.google.com/document/d/1lP8I0Jxu0B26cmTGBQcoHCbfSvKKHQBE6gzTL9HUheE/edit?tab=t.0#heading=h.icyigvoln8tg

**Comment by heyitsmebev** [comment]
@dmvancura @CathyBeil 

Hi, I'm placing this ticket in block/waiting until there's more clarity on where to place and move the new Join Notify page on the app.

**Comment by heyitsmebev** [comment]
[how it currently looks.pdf](https://github.com/user-attachments/files/17851930/screencapture-localhost-6012-about-join-notify-2024-11-21-12_57_00.pdf)

**Comment by dmvancura** [comment]
hi! commenting here agin to make sure i'm supporting as much as possible. see the screen capture for where the About Notify nav item link is expected. ![Image](https://github.com/user-attachments/assets/a72da24b-5b46-4f55-9f52-c10f97abd57e)
here is the prototype link https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=2339%3A3817&node-id=5884-16771&node-type=frame&viewport=2911%2C-7403%2C0.67&t=TpGSCkllSIAYHJb0-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5884%3A16771&show-proto-sidebar=1
