### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by heyitsmebev** [GSA/notifications-admin#2105]
Definition of Done

-  Should meet a11y standards

<img width="713" alt="image" src="https://github.com/user-attachments/assets/8e8472f2-021f-4501-ada2-23b17987f3a4">

Figma:
https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=2339%3A3817&node-id=5392-875&node-type=frame&viewport=2870%2C-701%2C0.48&t=nfkxOXnOCIFQB1yK-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5392%3A875

Content:
https://docs.google.com/document/d/1lP8I0Jxu0B26cmTGBQcoHCbfSvKKHQBE6gzTL9HUheE/edit?tab=t.0#heading=h.icyigvoln8tg

**Comment by heyitsmebev** [comment]
@dmvancura @CathyBeil 

Hi, I'm placing this ticket in block/waiting until there's more clarity on where to place and move the new Contact page on the app. If we are replacing the current one, I can also do that.

**Comment by dmvancura** [comment]
Ah, yes. Contact is a nav item, so it's in line with About Notify and Join Notify (see image of the formerly-known-as Guidance doc when the site nav is listed. @jonathanbobel, this is correct, yes? thanks!
<img width="627" alt="Screenshot 2024-11-21 at 4 30 59 PM" src="https://github.com/user-attachments/assets/55285695-40fe-48c1-ab21-4bf30997d700">
