### ISSUE TITLE
Remove cookies settings banner and the radio button from the cookies page

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#212]
https://notify-staging.app.cloud.gov/cookies

**Comment by tdlowden** [comment]
I don't think we need this banner or page with an option, specifically. But, we should have a privacy policy page. Going to open an issue for that.

**Comment by rahearn** [comment]
Adding security flag because there is a moderate OWASP ZAP finding on this page, and removing it will effectively remediate that.
