### ISSUE TITLE
Submit reassignment form

### ISSUE THREAD

**Issue by amyashida** [GSA/notifications-admin#214]
Outline our alternative paths forward (reassignment and details) including roles, processes, and timelines so that we can decide which path(s) we want to use for which roles. 

To do:

- [x] draft performance profiles for potential roles ([Python dev](https://docs.google.com/document/d/1dNsWOvZhtskQyHyUwWq77NDU6LNsQv5Yo_NrMmhFutA/edit) & [KM/strategy](https://docs.google.com/document/d/1WDS7kN--sLuDxqkb20c1YcfyTIGUXI1VdzUBekSQZPo/edit))
- [x] run by Amy/team for review
- [x] then submit [this form](https://docs.google.com/forms/d/e/1FAIpQLScSxq-34p128M5i632va5SfHmDRUX-GDvah4mGH5REPZpF8EQ/viewform) to start the process
- [x] update this card as next steps emerge :)

**Comment by alexpandel** [comment]
@amyashida rescoped this card a bit and removed you from it since for now, I'm holding the next steps (though it might be smart to _additionally_ map out _all_ our staffing options, from 18F to internal hiring to contracting, and review those as a team?)

**Comment by amyashida** [comment]
Form has been submitted - will create new cards for follow on actions.
