### ISSUE TITLE
User Story: Update Home Page Phase s1

### ISSUE THREAD

**Issue by alexjanousekGSA** [GSA/notifications-admin#2175]
### Detailed condition or criteria that must be met for the user story to be considered complete.

Page should look like the wireframes in - https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/notify.gov?page-id=2339%3A3817&node-id=6311-6722&node-type=frame&viewport=2911%2C-7403%2C0.67&t=TpGSCkllSIAYHJb0-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6311%3A6722&show-proto-sidebar=1

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- Get images and icons to upload
- Update homepage code to implement new content changes

**Comment by dmvancura** [comment]
link to copy doc https://docs.google.com/document/d/1fn3eHUjyJJcdZUnpqhp_q_sUddRZBK4pbs0SA-Zl7rU/edit?usp=sharing
