### ISSUE TITLE
Assess Pricing and Payment coumn

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#218]
![Image](https://user-images.githubusercontent.com/6556888/199283523-0e57bcf4-8ed5-45e8-9d9b-68ba75644338.png)

**Comment by stvnrlly** [comment]
This is now just "Pricing", folded into the "Using Notify" column

**Comment by tdlowden** [comment]
Given that pilot will be free and we are exploring longer free options, should we hide this page in the short term?
