### ISSUE TITLE
content changes to Using Notify and Best practices

### ISSUE THREAD

**Issue by dmvancura** [GSA/notifications-admin#2188]
content changes:

Using Notify content updated

1. The "Notify product modes" sub-page content is now moved to the "Using Notify" landing page (see [Using Notify copy doc](https://docs.google.com/document/d/1-_qUwyAVhHyvuWX7G3PbmnrtzcRaQH2J2uwoUCt8CSU/edit?usp=sharing) for details noted with tracked changes).
2. Six "Using Notify" landing page links (that go to the sub-pages) are updated, i.e., the descriptive text is static and the "label" is linked
3. Then, the "Notify product modes" sub-page is being deleted from the IA.

Best practices content moved

1. Best practices site section, as it is with the IA setup, moves under the nav header/item Using Notify. it is a sub-section now (reference the [Notify.gov sitemap spreadsheet](https://docs.google.com/spreadsheets/d/1VCW4c7ZfM_gik-YrtCBkJqXUmRx32McXP8mY4qntjuw/edit?usp=sharing) for URL and sitemap

Guides nav item sunsetted

1. Guides nav item goes away (the word and the function of it, i.e., it's not being used as a nav item anymore)

@jonathanbobel is creating an updated main nav and side nave to reference for the section as well

background:
these content change decisions came after discussing learnings from our initial user test. this occurred in a work session with jonathan, deana, cathy, and sheev. it's to minimize/eliminate confusion for a users who may wonder why "guides" and "using notify" were similar but different. any questions? chat below! thank you

**Comment by dmvancura** [comment]
i did assign priority and size to this, but would like to know if it's appropriate. who can help me with that? @stvnrlly

**Comment by ecayer** [comment]
Hi @dmvancura ! We haven't been using the priority label regularly. For the most part, priority is represented by order in the columns, particularly the Epics - Now column (and to a lesser extent, Up Next) 

If you are asserting priority - which is appropriate for work you are blocked on - it should go in Up Next as soon as you feel it is ready!

**Comment by dmvancura** [comment]
ah, good to know @ecayer! thank you for the direction

**Comment by dmvancura** [comment]
closing this issue as all of these plus additional changes to the content are being addressed with all of the new Using Notify content
