### ISSUE TITLE
Draft template for pilot agreement

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#225]

**Comment by tdlowden** [comment]
draft at: https://docs.google.com/document/d/1xhnkj8N28yCMx2w15L54rD_bGDhDcdtUxYHMrkUZtYs/edit#heading=h.30j0zll

**Comment by stvnrlly** [comment]
To pick up again after #251

**Comment by amyashida** [comment]
Alternative process outlined [here](https://docs.google.com/document/d/13hgJQlxgFwkNpghvn6WxRb7oyJkBzjlNGKJIKwPgSmk/edit#heading=h.kxk0021c528i)

**Comment by tdlowden** [comment]
Also pending OGC meeting

**Comment by tdlowden** [comment]
Sent to Tech Law Div for review/comment

**Comment by tdlowden** [comment]
Drafted but not yet approved. moving to close
