### ISSUE TITLE
prep for partner agreement call 12/13

### ISSUE THREAD

**Issue by alexpandel** [GSA/notifications-admin#232]
So that we get clarity & buy-in from TTS leadership on what's possible in terms of coming up with a minimally-burdensome agreement structure for providing Notify to partners.

To do:

- [x] @alexpandel take first pass at "read ahead" for meeting attendees, spelling out our preferred paths and posing our questions we have for the group
- [x] @amyashida / @tdlowden take second pass at "read ahead", and ship to attendees no later than noon ET on Monday
- [x] prep meeting agenda, including who's leading what parts
- [x] make new cards for any action items coming out of the meeting :)

**Comment by tdlowden** [comment]
#251 & #252
