### ISSUE TITLE
Add documentation about what opt-out (STOP & UNSTOP) information is available from AWS

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-admin#235]
Key questions:
- Can we get opt-out information by phone number?
- Does sending to an opted-out number count as a failure?

To complete:

- [x] Check AWS docs about what we can get from AWS
- [ ] Document what it looks like in AWS when users are opted out
- [ ] Document what happens in AWS when an opted-out user send "UNSTOP"
- [ ] Document the method for retrieving opt-out records
- [ ] Add public-facing content to site based on what we learn
- [ ] Scope follow-up tasks to pull opt-out records from AWS based on what we learn

**Comment by tdlowden** [comment]
Maybe these help?

https://docs.aws.amazon.com/sns/latest/dg/example_sns_ListPhoneNumbersOptedOut_section.html

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sns/list-phone-numbers-opted-out.html

https://docs.aws.amazon.com/sns/latest/api/API_ListPhoneNumbersOptedOut.html

**Comment by tdlowden** [comment]
Sidenote: Does the carrier honor UNSTOP?

**Comment by tdlowden** [comment]
- [ ] Research spike to determine what we can get from AWS and/or what carriers send to AWS
- [ ] Translation to write content to set partner expectations

**Comment by terrazoon** [comment]
1.  We can check if individual phone numbers are opted out by using a boto3 sns client:

response = client.check_if_phone_number_is_opted_out(
    phoneNumber='string'
)

**Comment by terrazoon** [comment]
Regarding opting back in, I think we should do nothing other than document that opting back in is not guaranteed.   In theory AWS handles it for us -- if the carrier supports opting back in.  I don't see how we could have any kind of self-made opt-in workflow because we don't have true two-way communication with the user.

**Comment by terrazoon** [comment]
> Thanks @terrazoon! I think what @rahearn meant with `Can we get opt-out information by phone number?` was:
> 
> Can we get opt-out information by sender phone number?
> 
> i.e. Can we get lists of opt-out for the Minnesota partner vs the Texas partner by their individual sender phone numbers?

Ah, pretty sure the answer to that is no but will drill down on that.
