### ISSUE TITLE
Draft federal-level passthrough agreement

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#252]
document our intentions around a federal pass-through model (citing past precedent, like Login/DOL MOU and 2016 CMS IAA) and have convo with OGC about where the line is

- [ ] Draft MOU for this that is not the above - build from the CMS example 
- [ ] Review with OGC
- [ ] Get feedback from ACF Lawyers 

(from https://docs.google.com/document/d/13AXmk_shYyXwaj59ZdAMAR3B0Mk6WoUQSFB0S9dB5Zo/edit#)

**Comment by alexpandel** [comment]
@amyashida CMS 2016 agreement docs are [here](https://drive.google.com/drive/folders/0B1ldQcLYjdJEMllNbzJLUFZ2Y1E?resourcekey=0-9xIODoHjzAdFus9nvJ7ytg) (signed IAA [here](https://drive.google.com/file/d/0B1ldQcLYjdJEcU92ZjAyYy1RdFFYTXVoeTJCU0JweXJCd3gw/view?usp=sharing&resourcekey=0-9wyTZkdWI0ymQo2MS8fRbw))

**Comment by tdlowden** [comment]
Raise question with OGC about need for 2 separate styles of agreements vs one.

**Comment by tdlowden** [comment]
This may be unnecessary given the ongoing legal conversations

**Comment by alexpandel** [comment]
good call @tdlowden; closing this in favor of #349
