### ISSUE TITLE
Split up outreach ownership across outreach strategies

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#260]

**Comment by alexpandel** [comment]
@em-herrick @stvnrlly is this done after our convo on Mon? or are there more steps here before we call this issue done?

**Comment by stvnrlly** [comment]
I'll defer to @em-herrick, and if the answer is "yes" let's link to the relevant doc in this thread before closing.

**Comment by alexpandel** [comment]
I've been thinking the "team owners" section of the "[engagement approach V2](https://docs.google.com/document/d/1LZKxLKHRi8lfTrW9ZZZlhK8DpgBt4Ei-CYQQhQFK9_M/edit#heading=h.kqqmk1qpccfq)" delineates it pretty well, but I'll let @em-herrick make the final call (and decide if any specific follow-up cards should get spun up as a result, in addition to #268 !)

**Comment by em-herrick** [comment]
Yes the final documentation is the V2 of the Engagement Approach, thanks for linking alex! Let's close!
