### ISSUE TITLE
Draft research plan about local program delivery

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#261]
Research Plan draft here: https://docs.google.com/document/d/1AGkydjupEu6-WAg2L8fpdeY-D_-eW5Qlq5dA3TCNgjM/edit#

**Comment by em-herrick** [comment]
@amyashida would appreciate a review/feedback on this doc if you have time next week.

Additionally, Sheev and I are gathering a list of local connections we can send some emails to early in 2023. If you have time and space would you be able to go through the the [Outreach Tracker](https://docs.google.com/spreadsheets/d/19Paw-ItuW1VACUT1DxHq_Sk5_43_a97EZFIZTdPeASU/edit#gid=0) and help prioritize connections in the Bet Vetting Summer Outreach tab? 

Other next steps around gathering contacts are listed in the research plan.

**Comment by em-herrick** [comment]
@tdlowden and @alexpandel would be great to have your eyes and thoughts on this research plan when you all get back in!


I'd like to have some wider team co-working time in early jan to shake out where "conference hopping " might converge with this more indvidual research.

**Comment by tdlowden** [comment]
Reviewers:

- [ ] Alex
- [ ] Tim

**Comment by tdlowden** [comment]
Thanks for the walkthrough @em-herrick !
