### ISSUE TITLE
Add Sheev and Ana as a Notify users

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#267]
- [ ] Pre-register your email when @rahearn or @stvnrlly sends you the pre-registration email
- [ ] Create an account using your @gsa.gov email address and the phone number where you'd like to receive 2FA texts
- [ ] Create a "service" using whatever options you'd like

That's it! Note that, while emails can only go to pre-registered addresses, SMS can go to any number, so please be mindful to only send to numbers you know.

**Comment by tdlowden** [comment]
@stvnrlly @rahearn as per @amyashida, moving this up in priority. Can one of y'all take this on next chance you get?

**Comment by amyashida** [comment]
Can we also add ana.monroe@gsa.gov? She is going to tag in with Sheev on the UX Audit.

**Comment by tdlowden** [comment]
@stvnrlly re:

> Create a "service" using whatever options you'd like

After they complete the AWS sanbox pre-registration, could we invite them as members to an existing service(s) we already created, or do they have to create their own? I think if the former, I'll just do that.

**Comment by stvnrlly** [comment]
Sure, we can invite them to existing services, but I imagine that they'll also want to set up a service to get a sense of the UX.

**Comment by rahearn** [comment]
AWS pre-registration verification emails sent.

**Comment by tdlowden** [comment]
As of 1/19, looks like Ana has not yet created an account.
