### ISSUE TITLE
Get TTS approval to attend Aspen

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#270]
- [ ] Travel Approval
- [ ] Speaking Approval
- [ ] Conference attendee approval?

**Comment by amyashida** [comment]
We need to get an invite in writing from the organizers. I asked for this [ here ](https://gsa-tts.slack.com/archives/C044NEX1R47/p1671739878646019)but it could probably use a nudge post holidays.

**Comment by tdlowden** [comment]
Received invite from Ginny Hunt and added to [Aspen folder](https://drive.google.com/drive/folders/1PGVwhBTkjDhpLiXdQhIRRvOhauhw6vWa)

**Comment by tdlowden** [comment]
Info for speaking request was shared with Jessi Bull and she said she'd complete it this week.

**Comment by tdlowden** [comment]
Sarah Crane sent her approval by email on 12/30. Tim will follow up to see if we need anything else other than speaker approvals.

**Comment by alexpandel** [comment]
FYI @tdlowden, re: travel approval vs event approvals, [this](https://handbook.tts.gsa.gov/training-and-development/conferences-events-training/#booking-travel) is all the Handbook says. Seems like there's some ambiguity about how to handle things if you're only traveling to _speak_ at a conference, not to _attend_ it. So it may be worth asking in #trainings-conferences to confirm if anything else is needed _beyond:_ 

1. Sarah's email approval for travel
2. speaker approval via [the process outlined here](https://handbook.tts.gsa.gov/training-and-development/external-speaking-request-playbook/#steps)?

[Here's](https://docs.google.com/document/d/1dDi7q2dUIRTN7RIu9yS2ywnOGN03pdPkobzbYkyftE8/edit#heading=h.q99i89ccqpk7) where Amy left things w/ Aspen approvals, fwiw!

**Comment by alexpandel** [comment]
Also @tdlowden it makes me a lil nervous waiting til next week for y'all to start submitting your speaker approvals, if we already have the talking points and now the invite ready to go (just since Outreach says it can take 3-6 weeks to get thru the approval process, and the event is in 4 😅 )... LMK if I can help with anything this week while Amy is out!

**Comment by tdlowden** [comment]
@alexpandel Amy, myself, and I believe Steven have already sent the speaker forms. And Jessi said she'd complete hers this week. So hopefully we are good

**Comment by em-herrick** [comment]
Allison Abbot is on deck to be extra facilitator (outside of TTS) does not need approval!

**Comment by alexpandel** [comment]
this happened, so calling it done! :)
