### ISSUE TITLE
Create Aspen talking points and justification docs

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#271]
- [x] Draft talking points
- [x] Draft justification
- [x] Review from @stvnrlly, @tdlowden, and @em-herrick

**Comment by amyashida** [comment]
Talking points are[ here](https://docs.google.com/document/d/1bw1UAuPBKvg6nFk3KBWY-ObOIArHCTHYwpIiwwA2YXs/edit#heading=h.wfixk93of3yj)

**Comment by amyashida** [comment]
Justification draft is[ here](https://docs.google.com/document/d/1aBjIM9gEdHjRun60Vdy4lqH2TVxG94EQJABzgdHe-I0/edit)

**Comment by tdlowden** [comment]
Reviewed and added a couple comments.

**Comment by em-herrick** [comment]
looks good to me!
