### ISSUE TITLE
Complete travel requests to DC for Aspen

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#277]
- [x] Fill out [travel estimator](https://docs.google.com/spreadsheets/d/1OQIfvakLRTNYcCYkMu2E5DE9lWr1-zy1uRxYxhCMjB0/edit#gid=278849937)
- [x] Submit concur requests (Tim and Amy) 
- [x] Send estimator to travel team (@amyashida)

**Comment by amyashida** [comment]
My concur request is sent - @tdlowden please check the box and close this card when yours is submitted.

**Comment by tdlowden** [comment]
Submitted request KYMNWD. Closing issue!
