### ISSUE TITLE
Get thumbs-up to proceed on notify.gov request from TTS leadership

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#283]

**Comment by amyashida** [comment]
Asked Ashley about this and she is supportive, but wants Star to review. Sent Star a message on 12/30.

**Comment by tdlowden** [comment]
- [ ] Respond to comments outreach (tim)
- [ ]  Nudge Star for concurrence (amy)
- [ ] Amy bring to Ann at 3/27 meeting

Closing #428 to de-dupe
