### ISSUE TITLE
Draft & Submit task order for development support

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#292]
- [x] Draft task order
- [x] share with OA team
- [x] revise SOO (or PWS, if taking that approach) & IGCE to include [content scope](https://docs.google.com/document/d/112kUBwbVuQ1e1WvNd87N8hpIvMVpwdnpJh73XpsATyE/edit) as well 
- [x] submit SOO/PWS & IGCE to OA for review
- [x] OA submits task order

**Comment by alexpandel** [comment]
update: they're assigned, woo! are you cool running with this? LMK if you need me to hop in on anything!

**Comment by tdlowden** [comment]
Closing #293 in favor of third acceptance criteria.

**Comment by alexpandel** [comment]
@stvnrlly I tried updating the individual to-dos in here based on our convo with OA today; LMK if/when you want a second brain on this!

**Comment by tdlowden** [comment]
@stvnrlly it feels like we may be further along on this than currently marked? Can you update or confirm this is where we are?
