### ISSUE TITLE
Onboard new ISSO

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#294]
Tasks:

- [x] setup ongoing meeting cadence
- [ ] decide on ways of working
- [x] request templates

**Comment by stvnrlly** [comment]
Should be happening tomorrow!

**Comment by rahearn** [comment]
Met with Fred, setup a weekly meeting on Thursdays at 4pm eastern. Getting started with FIPS 199 and 4-5 slides for Bo.
