### ISSUE TITLE
Draft SSPP

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#297]
TODO:

- [x] section 1
- [x] section 2
- [x] section 3
- [x] section 4
- [x] section 5
- [x] section 6
- [x] section 7
- [x] section 8
- [x] section 9
- [x] section 10
- [x] section 11
- [x] section 12
- [x] Controls: AC
- [x] Controls: AU
- [x] Controls: CA
- [x] Controls: CM
- [x] Controls: CP
- [x] Controls: IA
- [x] Controls: PL
- [x] Controls: RA
- [x] Controls: SA
- [x] Controls: SC
- [x] Controls: SI

**Comment by rahearn** [comment]
First draft complete
