### ISSUE TITLE
Allow services to move to production

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#301]
In the service settings for a platform admin, there is an ability to set a service to "Live". However, turning that on and saving errors out.

To complete:
- [x] Check the error that's occurring
- [x] Attempt to fix the error
- [x] If necessary, scope a new issue for longer tracking

**Comment by terrazoon** [comment]
Looks like the error is that "international_letters" exists in the list of permissions, but not in the list of allowed permission types.  I added one line to exclude "international_letters" from consideration, and can toggle from Live to Not Live without error.

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/277
