### ISSUE TITLE
Conduct UX audit

### ISSUE THREAD

**Issue by amyashida** [GSA/notifications-admin#331]
We have the following questions, but would like some documentation around what to expect from the UX audit. 

Output: Ideally, a back log of recommendations + pieces that a UX designer could pick up and run with

Questions include: 

- [ ] We're turning off several features that are in the tool (scaling back to SMS only) - what should we do UI wise for the features we're turning off so that our users feel successful and not confused? 
- [ ] Where might users need additional guidance/instruction?
- [ ] Are there user flows that don't make sense? How can they be improved? 

Things to note: 

- We know that we need to update the design system already!
- We have some hunches on new features in our [roadmap](https://docs.google.com/document/d/1CDMOAPwro1VRP1TY9C3DnLZPucOC8QjaSoKvJgI6sLU/edit#heading=h.go9u8yydn0st).

**Comment by em-herrick** [comment]
@sheevdave is coordinating with Ana Monroe Fitzner to conduct an audit of our product. Timeline is generally jan-feb. 

@sheevdave can you update us with a timeline when you and Ana sync on this?
