### ISSUE TITLE
Draft "top agency" MOU

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#349]
This is, in theory, a simple MOU for federal benefits agencies to acknowledge their support of administering agencies in their program using Notify as a means to communicate with program participants. 

- [x] Source info from 10x, who have done this model before
- [x] Draft MOU
- [x] Get team review
- [x] Get OGC Tech Law Div review

**Comment by alexpandel** [comment]
heads up @tdlowdenthat @amyashida & I would love to be able to show at least a draft of this to Rebecca @ FNS in our meeting on 2/7 (slash, we'll want it OGC approved before our 1st regional demo on 2/13)

**Comment by tdlowden** [comment]
https://docs.google.com/document/d/14T7XGxivVb0S5MyRLMZgRPXbWn1JceSZkUclAW7hSUo/edit#heading=h.1fob9te
