### ISSUE TITLE
Get tech law division access to notify

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#351]
john.peters@gsa.gov
daniel.nicotera@gsa.gov
micah.pischnotte@gsa.gov
nabeel.gadit@gsa.gov

**Comment by rahearn** [comment]
This can be done once https://github.com/GSA/notifications-api/issues/180 is complete

**Comment by tdlowden** [comment]
Maybe no longer needed?

**Comment by tdlowden** [comment]
de-prioritizing
