### ISSUE TITLE
Document process for onboarding people to Notify

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#374]
Once we are on our own infrastructure, we should document the process to follow.

**Comment by amyashida** [comment]
Existing instructions[ live here](https://docs.google.com/document/d/1hzdseV3eAjDpp-5Bm-44AW6gb3BxA2o8BfN_cm1iymE/edit)

But that "people" are we referring to?

**Comment by tdlowden** [comment]
I think we need to edit this process based on the new instructions once @rahearn completes AWS migration

**Comment by tdlowden** [comment]
@rahearn made edits to bring up-to-date. @em-herrick, is the plan to run this by @maomeara63 for thoughts and potential placement in site content?

**Comment by tdlowden** [comment]
Initial draft: https://docs.google.com/document/d/1hzdseV3eAjDpp-5Bm-44AW6gb3BxA2o8BfN_cm1iymE/edit#

Still need to figure out where/how to communicate this.
