### ISSUE TITLE
get speaker approval for March 2 Beeck event

### ISSUE THREAD

**Issue by alexpandel** [GSA/notifications-admin#377]
So that we can present to a gathering of state/local CDSOs!

Approval process here: https://handbook.tts.gsa.gov/training-and-development/external-speaking-request-playbook/

To do:
- [x] submit speaker request for myself
- [x] submit for Em & Tim?
- [x] schedule prep call with Kirsten Wyatt
- [x] Alex join "speakers bureau" & prep headshot/bio
- [x] Em join "speakers bureau" & prep headshot/bio

**Comment by alexpandel** [comment]
adding y'all to this card @em-herrick & @tdlowden because according to [the handbook](https://handbook.tts.gsa.gov/training-and-development/external-speaking-request-playbook/), we all need to join the TTS Speaker's Guild:

> If you want to represent TTS at an external event in your official capacity, you will need to be part of the TTS Speaker’s Bureau. In order to join the TTS Speaker’s Bureau you will need to:
> - Create a headshot and bio in the [GSA template](https://docs.google.com/document/d/1QLbn7nwH_kUS3PRVGQcHbu5MPEwdtf_NTAd6WuBoJFQ/edit). [Examples of bios](https://docs.google.com/spreadsheets/d/1QUeodBn_hkCiUfxb8xIsMXxoyxXAorpK3B6ujLQ45ZQ/edit#gid=0)
> - Complete the Join the [TTS Speaker’s Bureau form](https://docs.google.com/forms/d/e/1FAIpQLSfPHm4_tHVst3xXaAfVuY-ggDnpo2fryhMtIvk59HitRjy7Vg/viewform?usp=sf_link)

**Comment by em-herrick** [comment]
Cool! I have created a bio and submitted it to the Speakers Buraeu via google form!
