### ISSUE TITLE
User research insights and deliverables

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#386]
So that we know where people are getting blocked and what types of support they are looking for

**Comment by em-herrick** [comment]
- [ ] Deliverable 1: [Menu of Support for PHE and beyond](https://docs.google.com/document/d/1AnKV18d4bT4_nPX3gn-DdIJ7tlk0we55PMX3MdfXY08/edit#heading=h.ihe2r1fmtr1o)

- [ ] Deliverable 2: Updated Journey Map (w/ new steps and maybe Notify steps?)
- [ ] Deliverable 3: Process / team personas at 10,000 feet
- [ ]

**Comment by em-herrick** [comment]
To close the loop on user research i'd like the team to revew the following deliverables. 

- [ ] @sheevdave 
- [ ] @tdlowden 
- [ ] @amyashida 
- [ ] @alexpandel

**Comment by tdlowden** [comment]
Great work! Made some comments and did my review.

**Comment by amyashida** [comment]
I feel like turning these drafts into a report that we could publish - maybe in relation to the stuff Octavia is doing could be a good potential fit for our Flexion friends to get up to speed on the research.

**Comment by tdlowden** [comment]
@em-herrick any status on this?

**Comment by em-herrick** [comment]
We can close this for now, but we'll be discussing next steps of making some of this research public at our content planning huddle 4/20
