### ISSUE TITLE
Examine `_ga` cookie being placed

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#388]
I don't see a GA account firing on the pages:

![Image](https://user-images.githubusercontent.com/6556888/220383730-cc50b15b-6aa1-455a-9348-83526fef8259.png)

BUT, it appears we are setting a _ga cookie, regardless:

![Image](https://user-images.githubusercontent.com/6556888/220383426-15b6a0e1-0d2a-43e4-927f-d543e424086b.png)

We should examine if this is intended behavior.

**Comment by stvnrlly** [comment]
Closing as this is inactive, but replacing with an issue to remove the old analytics JS entirely.
