### ISSUE TITLE
Remove `cookies_policy` cookie

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#389]
The UK code offered an opt-out of the analytics cookie, as per GDPR requirement, managed by the `cookies-policy` cookie. Currently, few US government websites offer such an opt-out. Do we want to allow this opt-out ourselves? If not, we need to remove the cookie from being placed (or set it to `true` without being alterable).

![Image](https://user-images.githubusercontent.com/6556888/220385081-50a35246-061d-49df-830f-8580555cb9e5.png)

**Comment by tdlowden** [comment]
Deprioritizing after discussion with @stvnrlly and @rahearn

**Comment by tdlowden** [comment]
based on #212 , i think we may leave this for later discussion

**Comment by tdlowden** [comment]
We removed the cookie option banner, but I think the `cookies_policy` still remains. We should revisit it.

- [ ] Determine what the `cookie_policy` controls
- [ ] Decide if we'd like to keep it
- [ ] Document how a user could change it if they like

**Comment by anagradova** [comment]
After investigation using the E2E test login, a new test user in incognito mode, and manually reviewing the code, the cookie does not appear to be getting set anymore before or after login. It is possible it was removed in previous changes. 

![Image](https://github.com/GSA/notifications-admin/assets/108748167/597e34da-37f2-4687-bcde-8a457c4813b0)
