### ISSUE TITLE
Remove text message sender from user settings

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-admin#412]
Currently it is agency-editable and says that it can be any alphanumeric up to 11 characters.

Instead, this needs to be one of the provisioned phone numbers in AWS, so likely should only be editable by our team. (for pilot, can probably leave as-is permission wise, but we should at least update the help text to say that changing the value will not work).

Failure cases:

1) agency enters a non-phone number: their messages will be sent via the main U.S. Notify number
2) agency enters a phone number, but not one we have provisioned in AWS: their messages will not send.

**Comment by rahearn** [comment]
relevant guidance page `/using-notify/guidance/branding-and-customisation` which should also have the default value switched out from the name to the `config["AWS_US_TOLL_FREE_NUMBER"]` that we would actually use

**Comment by rahearn** [comment]
Yeah. Looks like in the UK you can send texts from a name, rather than a number, so this would let agencies identify themselves by name. The code would check to see if the "to" number was a US-based number and send from a specific toll free number instead of the name in that case. This worked fine for demo/staging where there was only one number to begin with, but in production I could see these failure cases popping up.

**Comment by tdlowden** [comment]
I believe the `help text` Ryan was referencing was `/using-notify/guidance/branding-and-customisation`, which now lives here `/using-notify/guidance#branding`. Essentially, we need to lock down how this functionality works in the settings within the code, and then address it accordingly in the guidance (which might just mean removing that text if they have no option to change the setting?)

**Comment by tdlowden** [comment]
As for the `Text Message Sender` row, I think we should just remove it?

**Comment by maomeara63** [comment]
There's a ticket in the backlog to remove Text message sender.

**Comment by tdlowden** [comment]
I closed the backlog ticket and I am moving this one back into "Up Next" for us to tackle
