### ISSUE TITLE
Create a SD README documenting some broader non-pilot work past and future

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#432]
To onboard future designer

- [ ] Link relevant murals
- [ ] Link research efforts to-date
- [ ]

**Comment by tdlowden** [comment]
@em-herrick should we close this?

**Comment by em-herrick** [comment]
Created a Design Onboarding doc here: https://docs.google.com/document/d/1NbV0gIlJIB7LAYsOU9AZXcsoPTz8yUr9ePibDA9Y6Zs/edit
