### ISSUE TITLE
Document how to send SMS via CSV upload

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#44]

**Comment by jimmoffet** [comment]
Worth noting that this is fully captured in a video demo here: https://gsa-tts.slack.com/archives/C0107UC0W1M/p1660937417450519

and also here:

https://drive.google.com/file/d/1eI2JdNczdoVK8zrKbCT3bQ7JxqBPEZzP/view?usp=sharing

**Comment by tdlowden** [comment]
[first attempt here](https://docs.google.com/document/d/1QtgTBVAnT4Dt2IFsniKwDJPaIu_xcb38ii7iCPEKQtQ/edit#heading=h.in37vtihaijv)

@stvnrlly do you think this is detailed enough?
