### ISSUE TITLE
Remove "crown" elements from UI code

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#446]
Along with https://github.com/GSA/notifications-api/issues/224, we will need to clear out the legacy "crown" portions of the UI code. This should happen after the API issue is completed, assuming that doesn't break the UI.

To complete:
- [ ] Remove crown references that call the API
- [ ] Rewrite any pieces that rely on organization or service crown status
- [ ] Remove crown from tests

**Comment by tdlowden** [comment]
@terrazoon, were you tackling this last week or is it a new card pickup? any updates?

**Comment by terrazoon** [comment]
This is in review.  I will move it.
