### ISSUE TITLE
Create content strategy to capture the outcomes/case studies of the pilots

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#464]

**Comment by maomeara63** [comment]
Draft of documents to serve two purposes:

1. Capture observations of partners' interactions with U.S. Notify to inform content or design changes.
2. Provide foundation for case study identification and content.

[Note taking template](https://docs.google.com/document/d/1heLmQ5iy_omPHNYxvcd0wqxTWfhLqIkWZYZSwB-13mg/edit?usp=sharing)
[Pilot feedback tracking template](https://docs.google.com/spreadsheets/d/1IGXfn9KUrg4ZIRtI_T7mdyT4pYQTzEcXsYHnrvj2RkI/edit?usp=sharing)
