### ISSUE TITLE
Add code coverage for JavaScript code

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#473]
This remains after https://github.com/GSA/notifications-admin/pull/472. Code coverage is handled by `jest`.

To complete:
- [x] Add commands to `make test` to check JS code coverage locally
- [x] Add commands to GitHub workflows to automate code coverage check in CI

**Comment by tdlowden** [comment]
Solid @A-Shumway42 ! Can we move this issue to `in review`?

**Comment by A-Shumway42** [comment]
@tdlowden This ticket has been merged to main. Should be in done. Sorry about that.
