### ISSUE TITLE
Update to flask & werkzeug 2.3

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-admin#477]
Flask and werkzeug 2.3.x lead to several test errors on admin app.

tests run with werkzeug 2.3 seem to strip the leading `+` from phone numbers, seemingly replacing it with a space. This leads me to think there's something going on where the test thinks it's a URLEncoded space, rather than a literal `+`

flask 2.3 seems to have issues with re-registering blueprints.

**Comment by davidism** [comment]
The `+` issue will be fixed in Werkzeug 2.3.1.

**Comment by rahearn** [comment]
There's a pip-audit finding on Flask 2.2 so it needs to be updated across both API and admin
