### ISSUE TITLE
Implement new pricing language re:characters 

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#500]
after results of #409 and #199, edit content to reflect language support

**Comment by maomeara63** [comment]
Per discussion with @em-herrick and @stvnrlly, add content to existing page that other characters not listed here will be treated the same -- meaning they invoke the 70-character-per-message-part instance.

**Comment by maomeara63** [comment]
@em-herrick @stvnrlly Please review this proposed copy.

[Pricing revisions](https://docs.google.com/document/d/1OorLzgHSAkxFWD4fSv7uBfAInUOWCTf0rxlkBlA6mzM/edit?usp=sharing)

**Comment by em-herrick** [comment]
Reviewed and added some suggested changes. I did not accept your edits (if it would be helpful for implementation)—but they look good from my end.

**Comment by maomeara63** [comment]
@jonathanbobel This is ready to be implemented. 

[Message parts revisions](https://docs.google.com/document/d/1OorLzgHSAkxFWD4fSv7uBfAInUOWCTf0rxlkBlA6mzM/edit?usp=sharing)
