### ISSUE TITLE
Update content for trial → production process

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#505]
In the service settings (and any other relevant places in the application?), update content to make clear that people should email the team when ready to move out of trial mode. Consider adding any requirements for users to know about beforehand.

**Comment by maomeara63** [comment]
Add note about contacting team to move out of trial mode:

Your service is in trial mode
You can only:

send 50 text messages per day
send messages to yourself and other people in your team
To remove these restrictions, you can send us a [request to go live](https://notify-demo.app.cloud.gov/services/55d8e754-4b06-4f08-84c6-f5e476d5ee99/service-settings/request-to-go-live).

- /services/55d8e754-4b06-4f08-84c6-f5e476d5ee99
- /services/55d8e754-4b06-4f08-84c6-f5e476d5ee99/usage
- /support (see [copy](https://docs.google.com/document/d/1cleomQ-6zu9xeKf-QvDcdUi_SQZZ8revH_2GPfPlfeo/edit?usp=sharing)) @tdlowden Please approve copy change.

**Comment by tdlowden** [comment]
Made a note in the doc, but we should remove that "go-live request" page altogether, given that we aren't enforcing those same requirements. Instead, we can make the link a mailto to notify-support@gsa.gov

**Comment by maomeara63** [comment]
Here's the usage page, @stvnrlly 

![Image](https://github.com/GSA/notifications-admin/assets/65717217/fe60e591-8161-4590-8c95-f277035a5f2b)

**Comment by maomeara63** [comment]
@tdlowden To clarify -- the message is not currently ON the usage page. The original ask (way up at the top) included identifying additional pages this should be on. That was one I thought could benefit from the addition.
