### ISSUE TITLE
Remove inline JS on email-link-interstitial.html

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#517]
This page has a hidden form that auto-executes when the page is loaded. It's used when re-verifying a user's email address. We don't want to run inline JS, and while we're at it we might be able to avoid this workflow.

To complete:
- [ ] Move form logic into view rather than template
- [ ] If not possible, move inline JS to a file in `/app/assets`

**Comment by ccostino** [comment]
Thanks, @A-Shumway42!  As we had discussed earlier together, we'll close out PR #548 in favor of the new work taking place.  Thanks for taking the time to work through this previously and I'm glad we arrived to a clearer (and simpler!) understanding with @stvnrlly. 😄

**Comment by A-Shumway42** [comment]
New PR is here with requested changes: <https://github.com/GSA/notifications-admin/pull/554>
