### ISSUE TITLE
Add DAP tag only for logged-out visits

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#519]
For the Digital Analytics Program, we want to record visits only to public pages. A quick check of the current template setup shows that public-facing pages are using a variety of templates, so it'll be simpler to add the tag to the base template (either `main_template.html` or `admin_template.html`, depending on your mood) with a conditional tag for no logged-in user.

Once we move docs to a separate Jekyll site, this can be simplified and improved by just counting all visits to the landing page.

To complete:

- [x] Get GTM tag (which will contain both DAP and Notify-specific GA tags)
- [ ] Add tests for both logged-in and logged-out users
- [ ] Add GTM tag to one of the base templates
- [ ] Configure GTM to fire DAP tag with conditional logic

**Comment by tdlowden** [comment]
My plan is to implement the tag via Google Tag Manager, so I can create the conditional logic within GTM, if there is something within the DOM for `logged-in` vs `logged-out`. I will change the first criteria from `Get DAP tag` to `get GTM tag` (which needs to be added in two places).

**Comment by tdlowden** [comment]
GTM Tag:

Paste this code as high in the <head> of the page as possible:

`
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WX5NGWF');</script>
`

Additionally, paste this code immediately after the opening <body> tag:

`
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WX5NGWF"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
`

**Comment by tdlowden** [comment]
So, this got hairy, and we found a newer solution:

Instead of relying on conditional logic, which seemed more difficult, I ended up writing a Regex that only fires on documentation pages, and not service-related pages. I think this will suffice for now. All that's left is to implement the GTM tag and publich the GA tags. Closing this issue in favor of creating one for the remaining tasks
