### ISSUE TITLE
Pricing page copy changes

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#523]
- [x] Change first paragraph to: During pilot period, each service has an allowance of 250,000 free text messages. Once this allowance is met, the application will stop delivering messages. There’s no monthly charge, no setup fee and no procurement cost.
- [x] At the end of the first section (prior to subhead "Text messages," add: You’ll use more messages towards the allowance, if you send text messages longer than 160 characters.

**Comment by jonathanbobel** [comment]
(I removed the comma on the second sentence)
