### ISSUE TITLE
Need to remove 'priority' info from Provider tab in platform admin view

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#529]
The Providers tab in the platform admin view shows 'priority' for SMS providers.   Currently it shows our SNS provider with a priority between 20 and 80, but this is all meaningless because, unlike UK Notify, we currently only have one provider which we are going to use 100 percent of the time.

This ticket is to remove priority info from the UI itself.

**Comment by tdlowden** [comment]
@terrazoon this is done, I think. yes?

**Comment by tdlowden** [comment]
ohhh in platform admin. gotcha
