### ISSUE TITLE
Incorporate "UTC" into `_human` time formatter utils

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#546]
It may be more consistent across the UI to just incorporate the timezone directly into the formatter. It also might create weirdness!

This isn't necessary if we tackle #544 first.

## Update on 7/5/23

@A-Shumway42 and @ccostino discussed this further and since we're going ahead with updating the formatter utils here for now, we've talked through what this means for the app currently and added details of what to do below.

## Implementation Sketch and Acceptance Criteria

- [x] Update all of the date, time, and datetime template formatters ([found here](https://github.com/GSA/notifications-admin/blob/main/app/formatters.py)) to include `UTC` in the strings they return.
- [x] Update any and all tests as necessary to account for the change of having `UTC` in the string
- [x] Remove any extraneous `UTC` strings from the templates that may have been added previously if the template formatter is now taking care of the display

For example, the [`format_datetime()`](https://github.com/GSA/notifications-admin/blob/main/app/formatters.py#L36-L40) method currently looks like this:

```python
def format_datetime(date):
    return '{} at {}'.format(
        format_date(date),
        format_time(date)
    )
```

After making the changes, it should look like this:

```python
def format_datetime(date):
    return '{} at {} UTC'.format(
        format_date(date),
        format_time(date)
    )
```

And any tests that require updating after that adjustment will need to be modified as well; any templates that are already adding a hardcoded `UTC` directly in the text will also need to be updated to remove the extraneous `UTC`.

## Security Considerations

- None; this is simply modifying the date/time displays with timezone information to make it clear to users what timezone is being used.

**Comment by ccostino** [comment]
[I attempted to quickly fix the display of the timestamps in the sent messages dashboard](https://github.com/GSA/notifications-admin/pull/555), but it proved to be more work than it was worth given what we'd like to do here.
