### ISSUE TITLE
Select workflows for end-to-end testing

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#549]
We would like a small set of user flows to script for end-to-end testing. What are the key flows for our pilot users?

To complete:
- [x] Identify <5 user flows to test
- [x] Create a new issue to add those tests for PR and daily test suites

**Comment by tdlowden** [comment]
Workflow candidates, per discussion with @em-herrick and @tdlowden 

- Sending a message from existing template
- Creating a template
- Deleting a template or folder (maybe after UI update?)
- Download the csv delivery report
- Invite a team member
- Deleting a team member
- Log-in
- Revalidate email address

If we are shooting for <5, we need to whittle this list a bit.

**Comment by tdlowden** [comment]
I think for now, top 5 are:

- Sending a message from existing template
- Creating a template
- Download the csv delivery report
- Invite a team member
- Revalidate email address
