### ISSUE TITLE
Hide all pages other than beta.notify.gov homepage except when logged-in

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#566]
In order to prepare the US Notify beta site for the official pilot to start, we need to update which content is visible prior to logging in vs. which is behind an authentication check.  This means making sure all routes and views other than the homepage check for user authentication and if a user is not logged in, they should be redirected to the homepage, which will include a sign-in button.

This work is based on [ADR-0004: Designing Pilot Content Visibility](https://github.com/GSA/notifications-api/blob/main/docs/adrs/0004-designing-pilot-content-visibility.md); please see the ADR for specific details.

## Implementation Sketch and Acceptance Criteria

This work will be implementing [Option 2 of ADR-0004](https://github.com/GSA/notifications-api/blob/main/docs/adrs/0004-designing-pilot-content-visibility.md#option-2-a-landing-page-with-sign-in-button-pilot-statement-and-a-small-amount-of-marketing-type-content-completely-removing-the-ability-to-create-a-service-except-if-done-by-a-studio-team-member-all-other-pages-are-only-accessible-after-login), which at a high level involves the following:

- [x] Double checking all views and their associated routes (except for the homepage) to see if they have the [`@user_is_logged_in`](https://github.com/GSA/notifications-admin/blob/main/app/utils/user.py#L9) decorator associated with them (with no options passed in) and adding it if it's not already there; see the [`add_service` view](https://github.com/GSA/notifications-admin/blob/main/app/main/views/add_service.py#L45) for an example.
- [x] Updating tests to make sure any that fail account for the changes and that they function with an authenticated test user as opposed to an unauthenticated user; this _should_ just be a matter of ensuring any simulated requests in a test is now made by an active and authenticated user if it's not already.

**NOTE:**  There are a couple of views that we may need to expose again, such as forgot password; @tdlowden is it possible to get a list of exceptions at all here?  For instance, any HTTP error messages go to an error view and we probably want to keep that open.

**NOTE:**  While ADR-0004 is in a proposed state, preliminary conversations between @tdlowden and @amyashida have landed on option 2, and @stvnrlly and @ccostino agree with this approach.  We'll move forward with it while we finalize the ADR itself.

## Security Considerations

- This will shift pretty much all of the site content behind the need to authenticate, which we realize is not ideal.  For the interim, the homepage will be updated with some basic information and the ability to sign in, and we'll revisit this over time to shift things back outside to public view as we're ready.

**Comment by ccostino** [comment]
Thank you @A-Shumway42 for all of the help in looking into this and working through the tests with me!
