### ISSUE TITLE
Wireframe Send Messages flow

### ISSUE THREAD

**Issue by jonathanbobel** [GSA/notifications-admin#573]
Wireframe the Send Messages landing page and create template flow

**Comment by jonathanbobel** [comment]
[Figma Prototype link](https://www.figma.com/proto/aAWhlPzOP6kfVFnCCAfSZZ/US-Notify-Templates?page-id=375%3A808&type=design&node-id=380-696&viewport=827%2C353%2C0.03&scaling=min-zoom&starting-point-node-id=380%3A696&show-proto-sidebar=1&mode=design&t=9ufrR0gJWJVOv5ZJ-1)

**Comment by tdlowden** [comment]
Reviewed these and made some comments. Also sent to @em-herrick for review. I think I'd also like @stvnrlly and @ccostino to take a look and make comments. Going to assign them as a task while I'm gone
