### ISSUE TITLE
Implement end to end tests for top user flows

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#591]
As a product team, we need to make sure we have adequate test coverage for primary user workflows of the Notify interface so that we are confident any changes we make do not accidentally break those workflows.

There are a variety of tools that existing for conducting end-to-end (E2E) tests with browsers, and our team is going to use [Playwright (Python)](https://playwright.dev/python/) due to the relative ease of setting it up and the integration with our other existing tools and test coverage, namely [`pytest`](https://pytest.org/).

## Implementation Sketch and Acceptance Criteria

- [x] Set up and integrate Playwright with the admin site's existing test configuration
- [ ] Create E2E tests for the following user workflows:
  - [ ] Sending a message from existing template
  - [ ] Creating a template
  - [ ] Download the csv delivery report
  - [ ] Invite a team member
  - [ ] Revalidate email address
- [x] Update documentation with instructions on how to create, run, and maintain the E2E tests
- [x] Add support for the E2E tests in the CI/CD workflow

## Security Considerations

- We may have to do a bit of extra configuration and set up with the CI/CD integration if we have to do something like pull in a different Docker image.

**Comment by ccostino** [comment]
Based on a bit of preliminary research of what we could use to accomplish this, I'm aware of the following tools:

- [Selenium](https://www.selenium.dev/)
- [Cypress](https://docs.cypress.io/guides/overview/why-cypress)
- [Playwright](https://playwright.dev/)
- [Puppeteer](https://pptr.dev/)

Of these, only [Selenium's ChromeDriver](https://www.selenium.dev/documentation/webdriver/browsers/chrome/) appears to be currently approved for use for us.  I've asked others who are more familiar in this space for their guidance and see if there's anything that I'm missing before diving down a deeper rabbit hole of how to get an actual thing going for us.

**Comment by ccostino** [comment]
After talking with some folks across TTS, it seems that E2E tools may fall under the general approval for open source libraries and frameworks, much like the other libraries and modules we pull in.

That said, both data.gov and FAC make use of Cypress, and cloud.gov is leveraging Playwright.  These may be worth looking at more closely since other teams are using them and we may be able to tap into their experience and contribute back our own lessons learned.

**Comment by jonathanbobel** [comment]
FWIW I've messed around with Playwrite on a small internal project before and found it pretty easy to use

**Comment by ccostino** [comment]
I updated the issue after doing a bit more research and will be moving forward with getting Playwright for Python integrated!

**Comment by ccostino** [comment]
🎉 #625 gets this going. :-)

**Comment by ccostino** [comment]
I have most of this in place now!  The big remaining thing at the moment is to see if we can sign in during the tests, and maintain an authenticated session for subsequent tests (but still run them in isolation).  That may prove to be a potential blocker and we'll have to put a pin in it for the future, but I'll spend a bit of time investigating to see if anything is possible.

At the very least, we have the foundation and it's working. :-) 🎉

**Comment by ccostino** [comment]
The foundation for E2E tests is now in place with #625!  We'll create a new PR for subsequent tests.
