### ISSUE TITLE
Determine elements of privacy assessment for ATO

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#62]

**Comment by tdlowden** [comment]
@rahearn, can you toss in a few acceptance criteria for this and move to backlog?

**Comment by stvnrlly** [comment]
Meeting with the Privacy Office on 1/9/23

**Comment by rahearn** [comment]
We'll be filling out the [PTA](https://github.com/GSA/notifications-admin/issues/295) and [PIA](https://github.com/GSA/notifications-admin/issues/296) in archer, and taking further conversations around partner-agency needs from there.
