### ISSUE TITLE
Let platform admins export listing of all users

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#641]
This could be a CSV download in the platform admin's "Reports" tab.

Should include:
- user
- whether user is platform admin
- services where they have any permissions
- services where they have management permissions

**Comment by terrazoon** [comment]
[User Report 2023-07-25 19_40_27.505859.csv](https://github.com/GSA/notifications-admin/files/12165196/User.Report.2023-07-25.19_40_27.505859.csv)
