### ISSUE TITLE
some broken UI on platform admin tab

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#660]
Some of the items like 'Find users by email' and 'Email branding' are broken at least when viewed in Chrome.

**Comment by terrazoon** [comment]
![Image](https://github.com/GSA/notifications-admin/assets/26859290/665e6bcd-9153-464c-8339-024293345e80)



![Image](https://github.com/GSA/notifications-admin/assets/26859290/9f62c690-54f2-4e45-93c0-4e86657f859d)

**Comment by jonathanbobel** [comment]
A previous fix addressed these problems
