### ISSUE TITLE
Change U.S. Notify to Notify on preview

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#667]

**Comment by maomeara63** [comment]
Change U.S. Notify to Notify on [preview screen](

![Image](https://github.com/GSA/notifications-admin/assets/65717217/cd2cf834-c7bb-4a6a-877a-22969fe970ae). Note this appears multiple times in the template creation flow and it isn't clear to me if it exists once or multiple times in the system.




![Image](https://github.com/GSA/notifications-admin/assets/65717217/1a7ebf83-bbdf-4ce8-a219-6bc9d75982c2)

**Comment by tdlowden** [comment]
I can change this as a Platform Admin in `Settings`, `Text Message Sender` for any given individual service, and per #412 conversation, it appears a textual change will not hurt anything. But I cannot change the default value globally, from what I can tell.`US Notify` is being set as a default text message sender somewhere in the code, I believe, and we need to find that and update it to `Notify.gov`. @ccostino or @terrazoon may be able to hunt this down.

**Comment by ccostino** [comment]
At a very quick glance, this appears to be in the [`app/config.py` file in the API](https://github.com/GSA/notifications-api/blob/main/app/config.py#L342); this looks like only for production though, so it might take a bit more digging just to be sure!

**Comment by maomeara63** [comment]
Related to this ticket, in the send a message path (after "review a message" and before you choose a file to upload), the following appears. It has no effect on message sending (as far as I can tell):



![Image](https://github.com/GSA/notifications-admin/assets/65717217/e6343fff-e2cf-4c16-9b13-d0e80503f4f6)

**Comment by tdlowden** [comment]
The default sender has been updated to Notify.gov, which addresses the initial intent of this issue. I believe the radio button issue is separate, so I am going to close this.
