### ISSUE TITLE
Add end-to-end testing workflows

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#677]
With end-to-end testing now in place and supported in our test infrastructure, there are several other user workflows we'd like to add testing coverage for.

This work is dependent on the authentication piece of end-to-end tests being figured out (#676).

## Implementation Sketch and Acceptance Criteria

- [ ] Create E2E tests for the following user workflows:
  - [ ] Sending a message from existing template
  - [ ] Creating a template
  - [ ] Download the csv delivery report
  - [ ] Invite a team member
  - [ ] Revalidate email address

## Security Considerations

- These tests will be running with a simulated authenticated user.

**Comment by VRagulina** [comment]
Check for open issues for E2E, close after referencing tickets

**Comment by ccostino** [comment]
I'm closing this issue in favor of tracking these items in the new epic instead: https://github.com/GSA/notifications-admin/issues/1540

I'll create separate issues for the tests that don't already have them.
