### ISSUE TITLE
Set session timeout to 30 minutes

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#678]
- [ ] Create 30 min inactivity session timeout
- [ ] Adjust and/or create a test to make sure it is happening
- [ ] Implement a warning at 28 minutes and create an option for someone to continue the session

**Comment by tdlowden** [comment]
WCAG resource: https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-required-behaviors.html

**Comment by A-Shumway42** [comment]
Moving this issue into blocked for now. The cookie containing the data with the expiration time (30 min) is set to `secure` and `htttponly`, meaning we can't access the data in the cookie from the client side (using javascript). I was looking into a way around this but came up short. Will work on getting together with others to find a possible work-around/solution.

**Comment by terrazoon** [comment]
I think we can bypass the cookie altogether if we do something like this:

in Flaskland:

set PERMANENT_SESSION_LIFETIME in the app.config to 30 minutes
set SESSION_REFRESH_EACH_REQUEST in the app.config to True

in javascript land:

on every request, restart a 28 minute timer.  When the timer goes off, it displays a 2 minute clock.  If the user clicks 'refresh my session' we close the clock and refresh the page.

We can't lower the security on the cookie, and cookies in general are a pain to deal with so if we can avoid using, that's better.

Regarding synchronization between client and server -- they will resend by default whenever the user moves around or refreshes a page.  For them to get out of sync while they are sitting on a given page, means the user's clock has to be running at a significantly different speed than the server clock (this has nothing to do with the actual time on the clocks, I means the seconds have to be passing at different rates).  I think this would be a rare occurrence and indicate something is wrong with the user's computer, but we could always set the warning period to 5 minutes or something to offset that.
