### ISSUE TITLE
Audit site and CI/CD scans for a11y

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#700]
Identify user flows to audit

**Comment by jonathanbobel** [comment]
Will revisit after the pilot so the site is more aligned with it's live state

**Comment by sheevdave** [comment]
From @jonathanbobel 
> the entire send message flow (with a few branching situations like scheduling a send vs now), template creation (including folder creation, moving them into different folders), and dashboard actions (viewing data, downloading reports)
We can do a crawl of the content pages too but I think we'll only maybe find a few issues there as there's not much to interact with
Robert Jolly from 10x will support site audit

**Comment by sheevdave** [comment]
@heyitsmebev investigating short list of checks we can make for site audit

**Comment by sheevdave** [comment]
### Audit Focus
- the entire send message flow (with a few branching situations like scheduling a send vs now)
- template creation (including folder creation, moving them into different folders)
- dashboard actions (viewing data, downloading reports)
- We can do a crawl of the content pages too but I think we'll only maybe find a few issues there as there's not much to interact with

**Comment by sheevdave** [comment]
closing this as other tickets are addressing these
