### ISSUE TITLE
Investigate and Improve test configuration and initialization (Admin; Python)

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#702]
We've been making several improvements to the app and updating dependencies quite a bit recently, and it's time to review how the tests are currently configured and initialized.  There are a few reasons for this:

- The testing config as it stands is quite complicated and cumbersome and could at least benefit from some cleanup
- Newer versions of dependencies may have different and improved ways of getting things setup
   - In some cases, there may be required changes
   - In others, there might be simpler ways of accomplishing what we need now by leveraging the features of the libraries/modules
- There are other dependencies that we're not currently able to update yet (e.g., SQLAlchemy, gunicorn) until we know for sure our tests are ready for them

**Note:** This is intended for the Python side of things for now.  Separate issues will be written for the JS side once we're ready.

## Implementation Sketch and Acceptance Criteria

- [x] Make sure all dependencies that we can easily update are up-to-date
- [ ] Review the documentation of pytest, Flask, SQLAlchemy, and associated plugins and integrations for recommended application configuration and initialization
- [ ] Update our testing config with an eye toward reducing complexity and cleaning things up as much as possible; reduce moving parts as much as possible
- [ ] Update tests and/or write new tests as necessary with the changes and improvements
- [ ] Update our documentation to reflect any changes related to environment setup, local development setup, etc.

## Security Considerations

- Updating dependencies will make sure we stay ahead of any vulnerability disclosures and help us with app maintenance
- Any changes to sensitive data management with newer module updates will have to be accounted for
- Any documentation updates that touch on sensitive information will have to be handled with care

**Comment by ccostino** [comment]
One major thing to look at here:  getting multiple test runners to work again!

**Comment by ccostino** [comment]
After incorporating `flake8-pytest-style` in the project to just account for style checks of our tests and test config, it's already proven useful in shedding light on the way f[ixtures work in `pytest`](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html), namely the differences between just using `return` vs. `yield`.

**Comment by ccostino** [comment]
Additional reference for testing with Flask and pytest:

- [Flask testing documentation](https://flask.palletsprojects.com/en/2.3.x/testing/)
- [`pytest-flask`](https://pytest-flask.readthedocs.io/en/latest/)
- [`pytest-xdist`](https://pytest-xdist.readthedocs.io/en/stable/)

**Comment by xlorepdarkhelm** [comment]
Fixture generators kinda work like a context manager/with statement. It allows you to set up and tear down whatever the fixture is providing cleanly and simply. I strongly recommend using these whenever possible, especially if we are needing to tear down something after the test is run.

**Comment by xlorepdarkhelm** [comment]
Parametrizing fixtures and functions is something I think is really under-utilized by most teams. If set up right, every test case can be easily configured and added to the parameters to make handling the test cases cleanly.

**Comment by ccostino** [comment]
@xlorepdarkhelm yes, exactly!  I think there's opportunity here to improve the fixtures we have (the test suite has a ton already) and possibly finding ways to pare down a bit and simplify them by parametrizing things more as well.

There's a good amount of this already in the code base for a solid foundation, and we'll want to keep this in mind as we continue to add our own new features and adjust what's already there.

Have you used [`hypothesis`](https://hypothesis.readthedocs.io/en/latest/) with `pytest` at all, by chance?  It was brought to my attention a while back and I haven't had the chance to incorporate it yet, but it seems to be a great way to support parametrizing tests and throwing a bunch of different data sets into them to help catch weirder edge cases and such, in addition to the more standard flows you'd run into.

**Comment by xlorepdarkhelm** [comment]
I have been on a project that used hypothesis. It is good, for what it does, but it can be a little annoying to be able to track down issues it finds with the randomization, since things are randomized. We had on that project several hypothesis tests that were known to just randomly error, and we would need to re-run to get the errors to go away.
