### ISSUE TITLE
Content Changes

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#715]

**Comment by tdlowden** [comment]
### Pricing - revised language - italics mine to show changes. do not add into content with italics.

>During pilot period, each service has an allowance of 250,000 free text messages. Once this allowance is met, the application will stop delivering messages. There’s no monthly charge, no setup fee and no procurement cost.

>_When a new service is added, it will start in [trial mode](https://notify-demo.app.cloud.gov/using-notify/trial-mode). Moving a service out of trial mode is subject to approval by the Notify.gov team._

>You’ll use more messages towards the allowance if you send text messages longer than 160 characters.

### Delivery Status - revised language

I think for right now, we just change `Sending` to `Pending`. Other statuses may appear as a result of failure, and they may all be applicable

### Features - revised language - italics mine to show changes. do not add into content with italics.

>Notify lets you:

- set different permission levels for each team member
- invite team members who do not have a government email address _(after the initial team member registers with a .gov email)_
- choose who else can manage team members

### Dashboard & Usage

We have separate tickets for this and we'll address those changes in those issues

### U.S. Notify as sender
This default needs to be changed and I'll create an issue to address separately

**Comment by tdlowden** [comment]
@jonathanbobel can we close this? If so, can you link the merged PR?
