### ISSUE TITLE
Display problems in Send a Text path

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#758]

**Comment by maomeara63** [comment]
@tdlowden For prioritization

Within the Send a Message path (Staging environment), there are numerous instances of text overlap problems, at least at some resolutions.

**Before uploading a file**


![Image](https://github.com/GSA/notifications-admin/assets/65717217/c296a6c1-7c6d-44a2-91ff-7ec369cf51c2)

**After uploading a file (preview)**



![Image](https://github.com/GSA/notifications-admin/assets/65717217/4353b902-6069-4261-8a34-6852562b652d)





**After uploading a file**


![Image](https://github.com/GSA/notifications-admin/assets/65717217/34bfd6d1-0e1b-48ce-8d40-67b89e02c145)

**Comment by tdlowden** [comment]
For reference, I believe @maomeara63 stated this is in `staging` env
