### ISSUE TITLE
Highlight template variables

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#766]
Previously, the application would highlight variables or conditionals in the template. I think this went away in some styling changes, but it would be worthwhile to re-implement unless we have feedback that says it is unnecessary.

![Image](https://user-images.githubusercontent.com/6556888/267979371-069dda2e-6129-4076-9ba6-7f1596f48a63.png)

**Comment by jonathanbobel** [comment]
I noticed this too and already fixed it - will put in review to make sure everything is good in staging

**Comment by tdlowden** [comment]
Not seeing this depicted @jonathanbobel, so maybe still outstanding?

**Comment by tdlowden** [comment]
NVM it does work! Closing

![Image](https://github.com/GSA/notifications-admin/assets/6556888/e6723e2f-6220-4ffe-b075-8d12d2cd02ae)
