### ISSUE TITLE
CSV downloaded report

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#768]

**Comment by maomeara63** [comment]
When a report is downloaded, the "Sent by" field is blank. If this is by design, the field should probably not appear. But I think the partners would probably want to know who sent the texts.



![Image](https://github.com/GSA/notifications-admin/assets/65717217/95cc140b-00e9-4e66-a0b5-f75596a98c79)

**Comment by terrazoon** [comment]
I'm going to remove the column.  The values for sent_by are currently either 'ses' or 'sns', which in our case means it will always be sns, which isn't very helpful info.

**Comment by tdlowden** [comment]
@terrazoon Can we explore having the `sent by` field display the person sender regardless if it was one-off or csv upload?

Depending on LOE to make this change, we may put this in the backlog
