### ISSUE TITLE
U.S. Notify on screen

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#776]

**Comment by maomeara63** [comment]
Change "US Notify" to "Notify"



![Image](https://github.com/GSA/notifications-admin/assets/65717217/90c8381e-5e09-42e3-adf7-51e9f1f90068)

**Comment by tdlowden** [comment]
I can fix this manually for the WA service, but I will close this issue in favor of https://github.com/GSA/notifications-api/issues/446, which I just re-opened
