### ISSUE TITLE
Permissions do not reflect actual permissions changes when a user looks at the team member dashboard

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#796]
Em had changed my permissions and removed `message send` capabilities, but when I looked at the team member dashboard, it still showed I had them. Thus, I thought there was a bug in the message send flow. Instead I guess the incorrect display of permissions is, in fact, the real bug.

**Comment by A-Shumway42** [comment]
The permissions are correct in the db when granting/removing specific privileges. The UI (team member dashboard) is showing the permissions whether they have them or not.

We can have it shown in the UI where "Cannot" is appended to the front of the privilege:


![Image](https://github.com/GSA/notifications-admin/assets/90117200/983d182d-da7a-4bbd-984e-6ef872d6b550)


If I remove the label, based on how the 'tick-cross.html' is written and displaying the privileges, it will show an empty list for those privileges:


![Image](https://github.com/GSA/notifications-admin/assets/90117200/21d8b3bf-fc63-4d48-932a-92780b6490c0)

It could be a simple CSS issue and i'm overlooking how to execute it.
