### ISSUE TITLE
Clarify what happens to data after retention periods

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#807]
On the details page, we say "Data available for 7 days". This doesn't explain what happens after that point.

We should clarify that:
- Aggregate data (e.g. messages sent per service) is always available
- Successful message data is anonymized and aggregated on confirmation of delivery
- Failed message data is anonymized and aggregated after 7 days

To complete:
- [x] Draft new content
- [ ] Update the view template

**Comment by jonathanbobel** [comment]
Spoke with @maomeara63 and decided we should think about the dashboard experience instead of this quick fix. Adding more content pushed the table down the page, and that is the only thing that changes when clicking through the tabs. Going to backlog for now.
