### ISSUE TITLE
Reword "Hide personalization after sending" to make the effect clearer

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#810]
During the sending flow, we tell users that they can "Hide personalization after sending". This means that the variable data used in the template will be obscured even to the uploader. What's being hidden and from whom should be more clear.

To complete:
- [x] Draft new content
- [ ] Update template view

**Comment by maomeara63** [comment]
Proposed content:

Hide all personalized and conditional content after sending for increased privacy protection.

@em-herrick @stvnrlly Please approve.

**Comment by em-herrick** [comment]
looks good to me!

**Comment by maomeara63** [comment]
@jonathanbobel Ready for implementation
