### ISSUE TITLE
Always show the sending phone number during sending flow

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#811]
During the message sending flow, users see "From:" and "To:" fields above their selected template. These are populated with the sending number and the recipient. However, when the sending number has a nickname in the system, that's used instead of the number. It's not clear that this is what's being represented.

To avoid this, let's use _both_ the name and the number in that field when both are available.

It turns out that this is kind of complicated to implement. The data comes from the API, the template component is managed in the utilities, and the view is rendered in the UI. Below is _possibly_ the implementation steps.

To complete:
- [ ] Update `SmsSender` to support both a phone number and a nickname
- [ ] Add migration for this change to the models
- [ ] Update SMS sender DAO to provide both phone number and nickname
- [ ] Update SMS sender API to return both phone number and nickname
- [ ] Update UI-side API call to receive both phone number and nickname
- [ ] Switch from number _or_ name to number _and_ name in template view in utils
- [ ] Check uses of `sms_sender` in all repos to accord with new function

**Comment by A-Shumway42** [comment]
After spending some time with @tdlowden  on this issue, it seems the logic is already in place and the number is showing during the message flow. It appears this issue can be closed unless there is something else to be done.

**Comment by ecayer** [comment]
We think we're OK (@ccostino took a look)
