### ISSUE TITLE
Change the blanket error message language

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#847]
The catch-all error for notify.gov reads: `Sorry, there is a problem with Notify.gov`.

I'd like to make that a bit more friendly in tone and also acknowledge that the application is not delivering what the user wants. Something closer to: "Uh-oh, something happened and we can't deliver what you asked for. Email us for more information". I asked Meghan to recommend content and then Jonathan can hopefully help make the change.

![Image](https://github.com/GSA/notifications-admin/assets/6556888/8f86a442-def7-4036-8477-5a9168c48a32)

**Comment by maomeara63** [comment]
Sorry, we can't deliver what you asked for right now. Please try again later or email us for more information.
