### ISSUE TITLE
investigate why some services got archived

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#848]
Amy tried to access a service in the `demo` env and got an error. When checking in platform admin, I found a few services that had been archived and names changed, like this:

>_archived_2023-10-02_Test Suspended

I don't *think* any of the Notify team manually did this, and we need to know why it happened.

**Comment by tdlowden** [comment]
I found that you *can* manually suspend a service (located in a very hidden spot at the bottom of service settings): 

![Image](https://github.com/GSA/notifications-admin/assets/6556888/b3046842-0625-4908-a17e-2dd27296d6b1)

**Comment by terrazoon** [comment]
The button "Delete this service" invokes the archive_service mechanism, and is available to platform admins and to users with the permission to manage services (if in trial mode):

<span class="page-footer-link page-footer-delete-link-without-button">
          <a class="usa-button usa-button--secondary" href="{{ url_for('.archive_service', service_id=current_service.id) }}">
            Delete this service
          </a>
        </span>
