### ISSUE TITLE
Make individual message send reports less ephemeral

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#855]
- When you send a message and it brings you to the individual message dashboard directly afterward, you have the option to download a csv report of that message (as in, the template you just sent)

- When you click on dashboard and see your messages over 7 days, you can download an aggregated report of all messages across all templates

BUT

- Once you leave the individual message dashboard, you can never again get a csv download for that specific message. You only have the option to download the aggregated csv, but not by a specific template and batch.

the reports are all in the application already, it would just be surfacing them from the main dashboard. it could be "here are reports for each bulk message send over the last 7 days, organized by the send". I fear that with the 5 min delay on delivery status, people will navigate away from the page that is immediately after sending, and then you lose the ability to get a report of that send alone.

Goal: Make the links to individual send reports less ephemeral. Put them somewhere people can refer back to during the 7 day window

**Comment by heyitsmebev** [comment]
@tdlowden do you have a video or screenshot of the "individual message dashboard"? After I sent a text message, I was not redirected after it was sent. Is this for email messages or sms?

**Comment by tdlowden** [comment]
This may be a bit dependent on the outcomes of /api #667.

**Comment by heyitsmebev** [comment]
@tdlowden 
I created a link "view job" where it will link you to the individual job page. A link will be displayed if there is a job (upload method). Once a user arrives to the individual job page, they can view their status and download the job. Let me know your thoughts. If it looks good, I will go ahead and submit this PR. 

https://github.com/GSA/notifications-admin/assets/53159604/4b8bbad2-0f11-4681-8aa3-15cfcab6c42c

**Comment by tdlowden** [comment]
This is super cool! I love this `View Job` idea! Only thing I am thinking is that where you have it currently placed is at an individual recipient level. So, if there is  job A where there are say 500 recipients, and then a job B with 500 the next day, on the main dashboard, the recipient rows will be the most recent and `Job A` recipients will be buried.

Is there any way to create a "last 7 days jobs" table which would only have a job listing, date/time, and `View Job`? cc @jonathanbobel for thoughts here since he has been working on improving the dashboard and I don't want us to duplicate work.

But all in all, this link to take you to an individual job dashboard is 🔥!!

**Comment by heyitsmebev** [comment]
@tdlowden I like the job table you suggested. I've created a table and placed it above "recent activities". This will give users the ability to go back and look at individual jobs and to download the csv file straight from the Dashboard view. 

Also, something to keep in mind that after the redesign, I would imagine we would not have all recipients listed on the dashboard like we currently do. I could see us having a link that brings the user to a reports tab where they could download a list of all recipients. Listing all the recipients like how we currently have could get expensive if our clients have long lists. So if there's a job A of 500 recipients and Job B with just as much recipients or more, our current UI may not be the best layout. A more condensed list might be better. 


![Image](https://github.com/GSA/notifications-admin/assets/53159604/bf6ce0e6-aaa4-4355-a3b0-aa0cd6ae293f)

**Comment by em-herrick** [comment]
@heyitsmebev #1097 has a few more additional table fields we want to include on this batches table.
