### ISSUE TITLE
Make the invite link a button instead of a long ugly link

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#863]
Since an invite to a service would be expected, the email comes from Notify.gov, and one can hover over a link, I propose we change the email link to a button that says something like `Join Service`

![Image](https://github.com/GSA/notifications-admin/assets/6556888/584517fc-ef23-4abe-a571-c97a171847f5)

**Comment by heyitsmebev** [comment]
I've created a button for this template, please let me know if there's a specific styling color needed for this email. 



![Image](https://github.com/GSA/notifications-admin/assets/53159604/176be760-9583-41ac-aba7-61b4f6ab1e43)

**Comment by heyitsmebev** [comment]
@ccostino @tdlowden 

By using the markdown to adjust the link, it would look something like the image below? Is this the look we are okay with for now and later we'll work through shortening the "long-ugly" URLs? 
![image](https://github.com/GSA/notifications-admin/assets/53159604/a7c13904-f71f-4d19-8866-0b8a3afc0d30)

**Comment by ccostino** [comment]
Oof!  It shouldn't look like that, that leads me to believe we either have a syntax issue, or it's not working quite as we expected.

**Comment by heyitsmebev** [comment]
**Correction:** 

Use [Join Service](((url))) with the extra parentheses, otherwise the url link does not work.
