### ISSUE TITLE
Messages per day is really messages per send

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#871]

**Comment by maomeara63** [comment]
Messages per day (50 in Trial Mode, for example), appears to be messages per send. Tim set my service to 1, and I received an error message when I tried to send to two. But it did let me send two messages (one right after another). See [Slack Thread.](https://gsa-tts.slack.com/archives/C0107UC0W1M/p1697559741515869)

**Comment by tdlowden** [comment]
![Image](https://github.com/GSA/notifications-admin/assets/6556888/06666b35-878d-4dd5-8b67-1a091fa91d3c)

**Comment by tdlowden** [comment]
Thing to figure out:

- Does the message limit setting pertain to `messages per day` or `messages per send`?
- if per day, what defines a `day`? Is it based on GMT, UTC, no timezone?

To decide:
- do we need a daily message limit setting?

**Comment by A-Shumway42** [comment]
I am unable to look into this due to not being able to upload a csv. I haven't been able to determine why that is happening to me. If this is happening to anyone else in the `dev` env, it would help to get some extra eyes on it.

**Comment by tdlowden** [comment]
@A-Shumway42 can you pick this back up now?

**Comment by tdlowden** [comment]
@A-Shumway42 Ok, for now, let's not change the variable but make it more clear in the settings that this is a "per batch" limit, not per day

**Comment by A-Shumway42** [comment]
@tdlowden Small PR is up with the changes giving clarity on the settings.
