### ISSUE TITLE
Move `Invite a Team Member` to a more visible spot on the page

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#878]
When adding a team member, the button appears at the bottom of the list. If there are many team members, this requires a long scroll 

![Image](https://github.com/GSA/notifications-admin/assets/6556888/b5ae8cff-dea5-43a7-8656-c750b42556dd)

Suggestion for a better spot is at the top of the page, on the right. Ideally it would be frozen as you scroll, but at least making it appear at the top of the page would be more helpful 

![Image](https://github.com/GSA/notifications-admin/assets/6556888/1e0e8647-c981-4641-80da-2279805e0733)

**Comment by ccostino** [comment]
This was completed with PR #1001, which is now in production!
