### ISSUE TITLE
Make the copy template display more intuitive

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#893]
when one clicks "copy an existing template", the screen shows all templates for all services one has access to. this is confusing. 

![Image](https://github.com/GSA/notifications-admin/assets/6556888/cf080657-e3b3-4adf-8e15-85212af66e9e)

**Comment by jonathanbobel** [comment]
Ideal end state: Only have templates with no folders, or remove all folders that do not end in a template for easier navigation

![Image](https://github.com/GSA/notifications-admin/assets/1233986/4e129f9d-d5c2-4d88-abaa-dbffd8099ae4)
