### ISSUE TITLE
Create UI changes to let people know of considerations when using Non-ISO character sets

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#901]
we should flag in the UI that 1. we can't guarantee the characters will appear correctly on recipients' phones and 2. that the "cost" in terms of fragments will increase based on non-ISO character sets

Acceptance criteria:

- [ ] App can identify when a template is created that contains non ISO characters
- [ ] When that identification is made, a warning appears prominently that notes the above

**Comment by terrazoon** [comment]
Text right now:

Will be charged as 1 text message. Use of characters outside the iso-latin-1 character set may increase the message fragment count, resulting in additional charges, and these non iso-latin-1 characters may not display properly on older phones.
