### ISSUE TITLE
Review and revise "go live" email

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#924]

**Comment by maomeara63** [comment]
@tdlowden Please review questions

[Draft go-live email](https://docs.google.com/document/d/1fwm9T4v_y5tmw9q58M2P5iPhuaKlTVEqXymmEMdlODc/edit?usp=sharing)

**Comment by stvnrlly** [comment]
All default template content lives in https://github.com/GSA/notifications-api/blob/main/app/config_files/templates.json, so that's where this edit should happen. Note that after the change is deployed we'll need to run the template update command to pull that content into the database.

**Comment by heyitsmebev** [comment]
Linked PR: https://github.com/GSA/notifications-api/pull/636

**Comment by ccostino** [comment]
Follow up PR https://github.com/GSA/notifications-api/pull/660 to remove the `message_limit` variable no longer used in this template.
