### ISSUE TITLE
Explore ways to harvest opt-out data by sending number

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#935]
We can see exactly which numbers have opted out in Cloudwatch failure logs, right? How can we leverage that to provide segmented lists to partners about opt-outs specific to their phone number(s), knowing that the toll-free numbers are limited in opt-out capabilities? Can we run a check of attempted send numbers from a csv against the cloudwatch log lists and produce service-specific opt-outs?

**Comment by terrazoon** [comment]
Carlo provided me with a sample opted-out message from cloudwatch:

{
    "notification": {
        "messageId": “XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    },
    "delivery": {
        "destination": "+15555555555",
        "providerResponse": "+15555555555 is opted out",
    },
    "status": "FAILURE"
}


There is also an 'initial' opt-out message where the providerResponse is "Phone has blocked SMS".

As you can see, there is no info here related to the sender.   It is my firm belief that regarding opt-out, the user is not opting out from any particular sender, but rather is opting out from notify.gov.   I think notify.gov is a weird use case where we are providing a tool that multiple senders will use.  More commonly a sender (such as USGS for example) has a dedicated production account and a short code, so if the user opts out they are opting out from USGS, who is the sender.

There are still a couple useful things we could do:


1. When we receive the initial "Phone has blocked SMS" message, we know what the service is.  So at this point in time we actually know the user is blocking the service.  At this point in time, we could send a text message or an email to the platform admins to inform them someone just opted out.

2. Any time they do a mass send with a csv file, they will get a report that might contain some "is opted out" messages.  Whether the user is conceptually opted out of their service or another service, in actual fact they are opted out of notify.gov so functionally the recovery would be the same.  have them opt back in and get an administrator to clear them in the aws console (we need an automation step for this!).

**Comment by terrazoon** [comment]
I think we should send an "alert" when we get the "Phone has blocked SMS" message.   To the service's platform admins?  To an email address?

Otherwise, it would be on them to fish the opt-outs out of the reports we have provided.   But I think (?) they need a platform admin button to clear opt-outs from the aws console.  We have to think about that because if some crazy admin just automatically clears them all the time without consulting with users, we can get in trouble with AWS I think.  But there has to be some way to get people opted back in without requiring Carlo or Steven to do it by hand.

**Comment by tdlowden** [comment]
@terrazoon would it make sense and/or be feasible to cull the opted out carrier replies into a separate report to be available alongside the normal delivery receipt report? This way, the use would not need to fish them all out of the larger report, but it would be incumbent on them to download a report specifically of the failures due to the opted-out status?

that might depend on the uniformity of the carrier/AWS messages?

**Comment by tdlowden** [comment]
Based on https://github.com/GSA/notifications-api/issues/312, explore how to export those lists
