### ISSUE TITLE
set up appointments for demo times

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#95]
use shared google cal appointment feature

**Comment by tdlowden** [comment]
having difficulty setting this up with the shared calendar. it appears to only let me do google appointments from my personal gsa.gov account. Any other tool ideas?

**Comment by tdlowden** [comment]
block normal cal time in Studio cal and offer those times for potential demos

**Comment by em-herrick** [comment]
A broader note on scheduling-- with all of our internal meetings on T-W it seems like Thursday is the best day for "partner" calls...I wonder if we can push our sprint planning meeting to later in the day on Thurs to open up more space? 3:30-4:45?

**Comment by tdlowden** [comment]
Right now I have Mondays from 3:30-4:30 blocked as a HOLD. 

There are few other spots that seem to fit in everyone's schedules. Let's start with that time and see if we need to expand further.
