### ISSUE TITLE
Add a test or additional parameter that covers mixed English-language texts

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#952]
The recent changes in the utils repo to [fix the fragment count](https://github.com/GSA/notifications-utils/pull/80) also resulted in some tests needing to be adjusted here.  There's one more test we'd like to add, just to make sure our bases are covered:  one that covers mixed English-language texts.

## Implementation Sketch and Acceptance Criteria

- [ ] Add a new test or add additional test parameter arguments to support a mixed English-language text

## Security Considerations

- None for this change.

**Comment by ecayer** [comment]
@anagradova Does this have a pull request associated with it? Thanks!

**Comment by terrazoon** [comment]
Close as done.
