### ISSUE TITLE
Use "message parts" when we're referencing service usage rather than just "messages"

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#963]
![Image](https://github.com/GSA/notifications-admin/assets/6556888/e28e254f-39ac-469f-9433-9eefc617f876)

 in this image, you can see that on the left for the month of November, it says `1405 text messages` and on the right, it says `2598 free text messages`. I *think* the right hand column is counting message fragments, or the individual message units that we allow 250K of.

We need to:

- [ ] Confirm the above hypothesis about message fragments vs "messages contained within a single template"
- [x] Decide terminology of `fragment`, `unit`, `credit` or otherwise
- [x] Audit the places within the site where a clarification or delineation of message vs fragment must be made
- [x] Add in the chosen word for message fragments everywhere necessary
- [ ] Consider adjusting MOU and pitch language to reflect this

**Comment by tdlowden** [comment]
A decision has been made to call billed chunks of a message: `parts`.

**Comment by maomeara63** [comment]
@tdlowden Please review
Content changes:

1. /using-notify/pricing: https://docs.google.com/document/d/1MAr2oc3-D0FREYk8FPueWHHrSGJHHqopJcspzJ_zUws/edit?usp=sharing
2. /using-notify/trial-mode: https://docs.google.com/document/d/1BHeLKMbM7oboWq2lxHiaFuLjJlO5qcuZdA9l3GD9muU/edit?usp=sharing
3. New text message template (where it says "will be charged as 1 text message" change to "will be charged as 1 text message part". Note this message varies with the length of the text, so it probably has to be changed in at least two places.
4. Usage: all references to "text messages" should be "text message parts"

**Future**
Dashboard should be cleaned up to clarify where we are talking about messages and where we are talking about message parts.

**Comment by maomeara63** [comment]
@jonathanbobel There is one missing word, which I highlighted in the [Pricing copy doc](https://docs.google.com/document/d/1MAr2oc3-D0FREYk8FPueWHHrSGJHHqopJcspzJ_zUws/edit?usp=sharing). Can you add it?
