### ISSUE TITLE
The error message for unsupported characters is very hard to find

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#967]
Spotting the unsupported character error message in this screenshot is very difficult:

![Image](https://github.com/GSA/notifications-admin/assets/6556888/c6b1e9f6-e384-4229-aaec-c0c4d5f4669a)

We need to make this error:

- [x] In a more visible spot, maybe near the top
- [x] In a bolded, red font or even potentially in a banner (i leave for a designer to decide)

**Comment by tdlowden** [comment]
The error status from USWDS looks like an awesome option here https://designsystem.digital.gov/components/alert/

**Comment by tdlowden** [comment]
This should also probably apply to other possible errors app-wide? maybe that's a separate issue?

**Comment by terrazoon** [comment]
Chúng tôi nhận thấy trong tài khoản của quý vị có thể có hành vi gian lận. Vui lòng gọi số # ở mặt
sau thẻ EBT của quý vị để hủy hoặc đến văn phòng địa phương để lấy thẻ mới. Trả lời DỪNG để dừng
nhận tin.

**Comment by terrazoon** [comment]
DSHS:我们发现您的账户存在潜在欺诈行为。请致电您的 EBT 卡背面的号码废止或前往当地办公
室获取一个新账户。回复 “STOP(退订)” 退订

**Comment by terrazoon** [comment]
The error message is right under "Final - VI" and starts "You cannot use".

I looked at this with chrome developer tools and the error message is in a span with class "error-message" so I don't know why it looks like regular text instead of red, bold, etc.

**Comment by heyitsmebev** [comment]
The new error message on the edit text page: 

![Image](https://github.com/GSA/notifications-admin/assets/53159604/79bf3d9d-c370-4b64-b659-808b6df7934d)
