### ISSUE TITLE
Add content about how personalization can increase message units per message

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#974]
After we decide on a word per #963 we need to add personalization verbiage in the pricing page that explains better to users how having, for example, ((address)) in a template that is 7 characters may push nearly every message to cost more units, because the inserted `address` is `2409 Fourth Street, Springfield Township, MO 34567`

**Comment by maomeara63** [comment]
@em-herrick @stvnrlly See [Pricing](https://docs.google.com/document/d/1MAr2oc3-D0FREYk8FPueWHHrSGJHHqopJcspzJ_zUws/edit?usp=sharing) for recommended copy. (It is highlighted.)

**Comment by maomeara63** [comment]
Copy communicating the impact of personalization on message length is included in [Pricing](https://docs.google.com/document/d/1MAr2oc3-D0FREYk8FPueWHHrSGJHHqopJcspzJ_zUws/edit?usp=sharing) and [Guidance.](https://docs.google.com/document/d/1HVUepE--JufiImezrc24o9qdErNiFDNHYifyfnSaIzY/edit?usp=sharing)
