### ISSUE TITLE
Canceling a past-due scheduled message doesn't work / Sending a scheduled message doesn't work

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#98]
As a Notify user, I would like to be able to cancel scheduled messages.

_____

Today, I tried using the scheduled message feature, just to walk through the process. I chose to send a message later in the day. After going through the process, I attempted to cancel the message send (so as to not spam our team members). I got an error message:

![Image](https://user-images.githubusercontent.com/6556888/192877941-27271399-4d85-4833-9633-42cc807b4e21.png)

Also interesting is that the message, despite being past the set time to send (in GMT, at least), did not send.

Is the scheduled send aspect of Notify not yet configured?

**Comment by tdlowden** [comment]
As a follow-up... Notify still has the message scheduled (for yesterday), and tells me do. I may not be able to remove this banner indefinitely. 

![Image](https://user-images.githubusercontent.com/6556888/193103305-5ffe07a5-b7aa-4915-ae64-ca412104cd32.png)

**Comment by stvnrlly** [comment]
This seems to work now? Going to optimistically close this.

**Comment by rahearn** [comment]
Going to re-open this and investigate where these scheduled jobs get stored and how long we might be holding onto information in a case like this.

**Comment by rahearn** [comment]
Debugging notes:

that particular job still had status "scheduled" despite being past the "scheduled_for" time. Looking into why it didn't send in the first place
