### ISSUE TITLE
replace login.gov link with a nice button or something

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#987]
Eventually the existing login functionality is going to be replaced with login.gov.  Clicking on a link or a button is actually going to redirect the user to login.gov so there is no need for us to have username/password displayed in our UI.

This change should happen once login.gov is working satisfactorily on staging and should be the last step before we push to production.

**Comment by heyitsmebev** [comment]
@tdlowden 
Currently the sign-in page displays a username/password input box in our UI. Eventually we will have a button displayed to redirect users to login.gov. Is there a UI design for how this sign-in page will look or should I just remove the input fields and add in a button?


![Image](https://github.com/GSA/notifications-admin/assets/53159604/176c013e-e262-4e39-a602-f65bdbaa0aed)

**Comment by heyitsmebev** [comment]
Thanks @jonathanbobel  I'll go with this for now https://designsystem.digital.gov/templates/authentication-pages/sign-in/

**Comment by tdlowden** [comment]
Yeah I think this may need to wait until we get login implemented fully, right? Eventually, the input fields we have now will be gone altogether, but i would think that we'd redirect people to the login screen directly from the `sign-in` button on the homepage, yeah? There's no need to bring someone to the current page so they can click a nice looking button. @terrazoon am I missing anything here?

**Comment by heyitsmebev** [comment]
related ticket: https://github.com/GSA/notifications-admin/issues/993

**Comment by heyitsmebev** [comment]
Looks like we are going to remove the sign-up page so I could implement this button on the homepage when we are ready.

**Comment by tdlowden** [comment]
Closing to move toward just pointing log-in button on homepage to login.gov when implemented
