### ISSUE TITLE
User unable to complete login flow

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#988]
We've received a report of a user who was able to login to the application and perform a variety of tasks, only to be unable to login since that time.  Now when they go to login, they provide their username and password, hit submit, and nothing happens after that.  No MFA prompt is given, no check to verify email message is displayed, and no MFA codes or emails are sent out.

At this time we're suggesting two things to help test this further and/or resolve the issue:

- Opening an incognito browser window and trying to login in there to see if there's any issues with the local cookies or cache that just need to be cleared.
- Scheduled a live video chat to walk through this with the user and tail logs on the server side while they attempt to login to see if any backend errors are thrown.

To our knowledge, no state or permissions have changed with the user's account, but that is something else we may want to look at.

@em-herrick will be following up with the user to provide this information to them and possibly schedule time with us to walk through things, with @andygoldstein-flexion and @maomeara63 helping support.

**Comment by ccostino** [comment]
I'm moving this to `Blocked/Waiting` for now just in case we see something.  If we don't see or here anything of this after the start of the new year I'd be fine putting this on ice for the future.

**Comment by tdlowden** [comment]
Closing bc we can't repo
