### ISSUE TITLE
Make necessary UI changes to accompany login.gov implementation

### ISSUE THREAD

**Issue by terrazoon** [GSA/notifications-admin#993]

**Comment by heyitsmebev** [comment]
This ticket is related to [replace login.gov link with a nice button or something#987](https://github.com/GSA/notifications-admin/issues/987) 

We may not need this UI if we do not have a sign-in page moving forward.

**Comment by heyitsmebev** [comment]
We are removing the sign-in page so this will not be needed because we will have the login.gov button on the homepage.
