### ISSUE TITLE
Update tagline on beta.notify.gov

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#998]
- [ ] Switch text of Notify.gov tagline from `Send text messages to your participants` to `Reach people where they are with government-powered text messages`
- [ ] Switch text of sub tagline to: `Notify.gov is a text message service that helps federal, state, local, tribal and territorial goverments more effectively communicate with the people who use their services.`

Assigning to Tim so he can assign to the correct dev :) 

Ideally, we'd like this to happen before the Notify.gov blog post announcement goes out on Thursday Dec 14

**Comment by heyitsmebev** [comment]
Linked PR: https://github.com/GSA/notifications-admin/pull/1000
